In [23]:
# wandbのライブラリをimport
import wandb

# wandbへログイン
wandb.login()

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /Users/qiminghe/.netrc
wandb: Currently logged in as: qhe202509 (qhe202509-personal) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [24]:
# Pandasのライブラリをインポート
import pandas as pd

# 学習データを読み込んで変数 train に格納
train = pd.read_csv('./train.csv')

# 学習データの表示
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
# テストデータを読み込んで変数 test に格納
test = pd.read_csv('./test.csv')

# テストデータの表示
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [26]:
# 学習データとテストデータ数を確認
print(train.shape)
print(test.shape)

(891, 12)
(418, 11)

In [27]:
# trainの欠損値の数を調査して、表示する
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [28]:
# testの欠損値の数を調査して、表示する
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [29]:
# 新しい空のDataFrameを作成する
temp = pd.DataFrame()

# 学習データとテストデータのAge列を連結させ、tempにAge列として追加する
temp['Age'] = pd.concat([train['Age'], test['Age']])

# trainとtestのAge列について、欠損値をtempのAge列の平均値で埋める
train['Age'] = train['Age'].fillna(temp['Age'].mean())
test['Age'] = test['Age'].fillna(temp['Age'].mean())

In [30]:
# 学習データとテストデータのFare列を連結させ、tempにFare列として追加する
temp['Fare'] = pd.concat([train['Fare'], test['Fare']])

# testのみに存在するFare列の欠損値をtempのFare列の平均値で埋める
test['Fare'] = test['Fare'].fillna(temp['Fare'].mean())

In [31]:
# 学習データとテストデータのEmbarked列を連結させ、tempにEmbarked列として追加する
temp['Embarked'] = pd.concat([train['Embarked'], test['Embarked']])

# tempのEmbakedの値を集計する
temp['Embarked'].value_counts()

Embarked
S    914
C    270
Q    123
Name: count, dtype: int64

In [32]:
# trainのみに存在するEmbarked列の欠損値を'S'で埋める
train['Embarked'] = train['Embarked'].fillna('S')

In [33]:
# trainとtestから、Cabin,Name,Ticket列を削除する
train = train.drop(columns=['Cabin', 'Name', 'Ticket'])
test = test.drop(columns=['Cabin', 'Name', 'Ticket'])

In [34]:
# trainのSex列とEmbarked列をダミー変数化して、変数train2に格納する
train2 = pd.get_dummies(data=train, columns=['Sex', 'Embarked'])
print(train2.head())
# testのSex列とEmbarked列をダミー変数化して、変数test2に格納する
test2 = pd.get_dummies(data=test, columns=['Sex', 'Embarked'])
print(test2.head())

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  \
0            1         0       3  22.0      1      0   7.2500       False
1            2         1       1  38.0      1      0  71.2833        True
2            3         1       3  26.0      0      0   7.9250        True
3            4         1       1  35.0      1      0  53.1000        True
4            5         0       3  35.0      0      0   8.0500       False

   Sex_male  Embarked_C  Embarked_Q  Embarked_S
0      True       False       False        True
1     False        True       False       False
2     False       False       False        True
3     False       False       False        True
4      True       False       False        True
   PassengerId  Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
0          892       3  34.5      0      0   7.8292       False      True
1          893       3  47.0      1      0   7.0000        True     False
2          894       2  62.0      0      0   9.6875       False      True
3          895       3  27.0      0      0   8.6625       False      True
4          896       3  22.0      1      1  12.2875        True     False

   Embarked_C  Embarked_Q  Embarked_S
0       False        True       False
1       False       False        True
2       False        True       False
3       False       False        True
4       False       False        True

In [35]:
# train2の欠損値の数を調査して、表示する
train2.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Sex_female     0
Sex_male       0
Embarked_C     0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [36]:
# test2の欠損値の数を調査して、表示する
test2.isnull().sum()

PassengerId    0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Sex_female     0
Sex_male       0
Embarked_C     0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [37]:
# train2の各列の型を表示する
train2.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Sex_female        bool
Sex_male          bool
Embarked_C        bool
Embarked_Q        bool
Embarked_S        bool
dtype: object

In [38]:
# numpyのimport
import numpy as np

# train2をX_trainとY_trainに分ける
X_train = np.array(train2.drop(columns=['Survived'])).astype('float32')
Y_train = np.array(train2['Survived']).astype('float32')

# test2のデータ全体をX_testに格納する
X_test = np.array(test2).astype('float32')

In [39]:
# X_trainとY_trainの3割をX_validとY_validに分割する
from sklearn.model_selection import train_test_split

X_train, X_valid, Y_train, Y_valid = train_test_split(X_train, Y_train, test_size=0.3, random_state=0)

In [40]:
# 学習データと検証データ、テストデータの形状を確認
print("X_train=", X_train.shape, ", Y_train=", Y_train.shape)
print("X_valid=", X_valid.shape, ", Y_valid=", Y_valid.shape)
print("X_test=", X_test.shape)

X_train= (623, 11) , Y_train= (623,)
X_valid= (268, 11) , Y_valid= (268,)
X_test= (418, 11)

In [41]:
# tensorflowのimport
import tensorflow as tf

In [42]:
# モデルの構築と学習を定義する関数
def train_model():
    # wandbの初期設定
    wandb.init(
        # wandbでのプロジェクト名
        project="kaggle-titanic",
        # wandbで記録してもらいたい設定値
        config={
            "input_dense_shape": 8,
            "hidden_dense_shape": 8,
            "optimizer": "rmsprop",
            "batch_size": 32
        })

    # モデルの初期化とレイヤー定義
    model = tf.keras.Sequential([
        # 入力層 (Inputオブジェクトを使用)
        tf.keras.Input(shape=(11,)),
        tf.keras.layers.Dense(wandb.config.input_dense_shape, activation='relu'),
        # 隠れ層
        tf.keras.layers.Dense(wandb.config.hidden_dense_shape, activation='relu'),
        # 出力層
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    # モデルの構築
    model.compile(optimizer=wandb.config.optimizer,
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    # 学習の実施
    log = model.fit(X_train, Y_train, epochs=5000, batch_size=wandb.config.batch_size, verbose=True,
                    callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_loss',
                                                                min_delta=0, patience=100,
                                                                verbose=1),
                              wandb.keras.WandbMetricsLogger(log_freq='epoch')
                              ],
                    validation_data=(X_valid, Y_valid))

In [43]:
# train_modelを実行する
train_model()

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3900 - loss: 115.8914 - val_accuracy: 0.3694 - val_loss: 90.3962
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3884 - loss: 74.7434 - val_accuracy: 0.3769 - val_loss: 55.0814
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3852 - loss: 40.0225 - val_accuracy: 0.4067 - val_loss: 22.0803
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4687 - loss: 8.9061 - val_accuracy: 0.5933 - val_loss: 1.1934
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6019 - loss: 1.3311 - val_accuracy: 0.5112 - val_loss: 1.9259
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 1.2770 - val_accuracy: 0.5672 - val_loss: 1.1584
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 1.1813 - val_accuracy: 0.7239 - val_loss: 0.8723
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 1.1845 - val_accuracy: 0.5821 - val_loss: 0.9667
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 1.1187 - val_accuracy: 0.7127 - val_loss: 0.8045
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 1.0401 - val_accuracy: 0.7090 - val_loss: 0.7601
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 1.0310 - val_accuracy: 0.5037 - val_loss: 1.2452
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5907 - loss: 0.9818 - val_accuracy: 0.6642 - val_loss: 1.6237
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.9329 - val_accuracy: 0.6940 - val_loss: 0.7970
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.8743 - val_accuracy: 0.6903 - val_loss: 0.7718
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6019 - loss: 0.9846 - val_accuracy: 0.7127 - val_loss: 0.6988
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.9111 - val_accuracy: 0.7090 - val_loss: 0.6865
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.8713 - val_accuracy: 0.6978 - val_loss: 0.7057
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.8226 - val_accuracy: 0.4328 - val_loss: 1.7160
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6067 - loss: 0.9078 - val_accuracy: 0.6978 - val_loss: 0.7086
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.9509 - val_accuracy: 0.7090 - val_loss: 0.6814
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.7312 - val_accuracy: 0.6754 - val_loss: 0.8863
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.8397 - val_accuracy: 0.6604 - val_loss: 1.2421
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.9282 - val_accuracy: 0.4328 - val_loss: 1.3148
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.7829 - val_accuracy: 0.4067 - val_loss: 1.9512
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6308 - loss: 0.8626 - val_accuracy: 0.6604 - val_loss: 1.1675
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.8008 - val_accuracy: 0.4216 - val_loss: 1.5847
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.7931 - val_accuracy: 0.7239 - val_loss: 0.6256
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.7300 - val_accuracy: 0.7276 - val_loss: 0.6239
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.7789 - val_accuracy: 0.6343 - val_loss: 1.7433
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.7397 - val_accuracy: 0.7127 - val_loss: 0.6200
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.8071 - val_accuracy: 0.6978 - val_loss: 0.7199
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.7823 - val_accuracy: 0.7239 - val_loss: 0.6154
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.7606 - val_accuracy: 0.6978 - val_loss: 0.7289
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.7737 - val_accuracy: 0.6791 - val_loss: 0.6903
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.7940 - val_accuracy: 0.6567 - val_loss: 1.3031
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.8389 - val_accuracy: 0.7575 - val_loss: 0.6467
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.7409 - val_accuracy: 0.7425 - val_loss: 0.5982
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.7480 - val_accuracy: 0.4590 - val_loss: 1.0217
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.7615 - val_accuracy: 0.4515 - val_loss: 1.1500
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.7130 - val_accuracy: 0.7015 - val_loss: 0.6343
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.7255 - val_accuracy: 0.7500 - val_loss: 0.6352
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.7354 - val_accuracy: 0.7649 - val_loss: 0.6132
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.8014 - val_accuracy: 0.7052 - val_loss: 0.6351
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6970 - val_accuracy: 0.5000 - val_loss: 0.9272
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.7124 - val_accuracy: 0.6716 - val_loss: 0.8668
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.7449 - val_accuracy: 0.7463 - val_loss: 0.6412
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.7170 - val_accuracy: 0.7015 - val_loss: 0.6587
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.7268 - val_accuracy: 0.7276 - val_loss: 0.6491
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.6595 - val_accuracy: 0.6567 - val_loss: 1.2321
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6923 - val_accuracy: 0.6754 - val_loss: 0.9429
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.7750 - val_accuracy: 0.7425 - val_loss: 0.5683
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6762 - val_accuracy: 0.4888 - val_loss: 1.0086
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.6693 - val_accuracy: 0.6679 - val_loss: 1.0767
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.6919 - val_accuracy: 0.7164 - val_loss: 0.6409
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.7050 - val_accuracy: 0.6716 - val_loss: 0.9825
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.7147 - val_accuracy: 0.6530 - val_loss: 1.3734
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.6604 - val_accuracy: 0.6493 - val_loss: 1.2236
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.7059 - val_accuracy: 0.5709 - val_loss: 0.7928
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.6720 - val_accuracy: 0.6754 - val_loss: 0.8568
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.7091 - val_accuracy: 0.4478 - val_loss: 1.6250
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.7085 - val_accuracy: 0.7836 - val_loss: 0.5568
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.6424 - val_accuracy: 0.5037 - val_loss: 0.9883
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.7005 - val_accuracy: 0.6828 - val_loss: 0.8675
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.6435 - val_accuracy: 0.6567 - val_loss: 1.2858
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.7431 - val_accuracy: 0.6978 - val_loss: 0.6681
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6907 - val_accuracy: 0.7687 - val_loss: 0.5339
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.7743 - val_accuracy: 0.7910 - val_loss: 0.5381
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6128 - val_accuracy: 0.7127 - val_loss: 0.6543
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.7171 - val_accuracy: 0.7388 - val_loss: 0.5655
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.6256 - val_accuracy: 0.4813 - val_loss: 1.2240
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.8119 - val_accuracy: 0.7463 - val_loss: 0.5498
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.6513 - val_accuracy: 0.7052 - val_loss: 0.6706
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6934 - loss: 0.6938 - val_accuracy: 0.6604 - val_loss: 1.2119
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6691 - val_accuracy: 0.4590 - val_loss: 1.4196
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.7129 - val_accuracy: 0.7276 - val_loss: 0.6199
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6243 - val_accuracy: 0.6493 - val_loss: 1.5139
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6986 - val_accuracy: 0.7575 - val_loss: 0.5186
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6494 - val_accuracy: 0.6604 - val_loss: 1.1454
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5681 - val_accuracy: 0.6455 - val_loss: 1.3284
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6760 - val_accuracy: 0.7425 - val_loss: 0.5611
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.6584 - val_accuracy: 0.7612 - val_loss: 0.5250
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.6383 - val_accuracy: 0.7239 - val_loss: 0.5923
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.6617 - val_accuracy: 0.7799 - val_loss: 0.5355
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6443 - val_accuracy: 0.6791 - val_loss: 0.9648
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.6695 - val_accuracy: 0.5522 - val_loss: 0.8595
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.6719 - val_accuracy: 0.7500 - val_loss: 0.5408
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.7076 - val_accuracy: 0.7052 - val_loss: 0.7031
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.6143 - val_accuracy: 0.7612 - val_loss: 0.5144
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6462 - val_accuracy: 0.7687 - val_loss: 0.5109
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.6696 - val_accuracy: 0.7836 - val_loss: 0.5573
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.6545 - val_accuracy: 0.7239 - val_loss: 0.6781
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.6162 - val_accuracy: 0.6604 - val_loss: 1.1797
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.7137 - val_accuracy: 0.5299 - val_loss: 0.9029
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5672 - val_accuracy: 0.7687 - val_loss: 0.6015
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.6123 - val_accuracy: 0.6866 - val_loss: 0.8402
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6233 - val_accuracy: 0.7836 - val_loss: 0.5092
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.6755 - val_accuracy: 0.4739 - val_loss: 1.2251
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6525 - val_accuracy: 0.6866 - val_loss: 0.8529
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.6008 - val_accuracy: 0.7127 - val_loss: 0.7022
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6672 - val_accuracy: 0.7836 - val_loss: 0.5004
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.6084 - val_accuracy: 0.6940 - val_loss: 0.7779
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6598 - val_accuracy: 0.7090 - val_loss: 0.7232
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5802 - val_accuracy: 0.7313 - val_loss: 0.6200
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.6474 - val_accuracy: 0.7724 - val_loss: 0.5033
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.6801 - val_accuracy: 0.7649 - val_loss: 0.5106
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.6192 - val_accuracy: 0.7649 - val_loss: 0.4946
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5764 - val_accuracy: 0.6866 - val_loss: 0.8525
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.6154 - val_accuracy: 0.7575 - val_loss: 0.5020
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.6691 - val_accuracy: 0.6866 - val_loss: 0.8082
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5689 - val_accuracy: 0.4813 - val_loss: 1.1929
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.6353 - val_accuracy: 0.7761 - val_loss: 0.4922
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5976 - val_accuracy: 0.7873 - val_loss: 0.5418
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5855 - val_accuracy: 0.6604 - val_loss: 1.0500
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.6374 - val_accuracy: 0.6866 - val_loss: 0.6846
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6381 - val_accuracy: 0.7276 - val_loss: 0.6519
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6885 - val_accuracy: 0.7761 - val_loss: 0.4900
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.5597 - val_accuracy: 0.7276 - val_loss: 0.5964
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.7480 - val_accuracy: 0.7127 - val_loss: 0.7044
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.5671 - val_accuracy: 0.6082 - val_loss: 0.8036
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.6483 - val_accuracy: 0.7724 - val_loss: 0.5137
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5698 - val_accuracy: 0.7276 - val_loss: 0.6438
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.6665 - val_accuracy: 0.7388 - val_loss: 0.6333
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.6440 - val_accuracy: 0.7873 - val_loss: 0.5805
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5921 - val_accuracy: 0.6642 - val_loss: 1.0083
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6586 - val_accuracy: 0.7799 - val_loss: 0.4888
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5492 - val_accuracy: 0.7649 - val_loss: 0.4915
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.6060 - val_accuracy: 0.6493 - val_loss: 1.4985
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5992 - val_accuracy: 0.6716 - val_loss: 0.9496
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5704 - val_accuracy: 0.7649 - val_loss: 0.6025
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6205 - val_accuracy: 0.7799 - val_loss: 0.4881
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.6266 - val_accuracy: 0.7313 - val_loss: 0.6417
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.5408 - val_accuracy: 0.4813 - val_loss: 1.3297
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5783 - val_accuracy: 0.5970 - val_loss: 0.8035
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5891 - val_accuracy: 0.7388 - val_loss: 0.6350
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6044 - val_accuracy: 0.7164 - val_loss: 0.7481
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.6266 - val_accuracy: 0.7873 - val_loss: 0.5334
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.6286 - val_accuracy: 0.7239 - val_loss: 0.7184
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.6019 - val_accuracy: 0.7985 - val_loss: 0.5552
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6153 - val_accuracy: 0.7799 - val_loss: 0.5129
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5902 - val_accuracy: 0.7388 - val_loss: 0.5975
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.6292 - val_accuracy: 0.7537 - val_loss: 0.5072
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5721 - val_accuracy: 0.7201 - val_loss: 0.6891
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.6715 - val_accuracy: 0.7799 - val_loss: 0.4822
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.5476 - val_accuracy: 0.7724 - val_loss: 0.4851
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.6689 - val_accuracy: 0.6754 - val_loss: 1.1979
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.6126 - val_accuracy: 0.7313 - val_loss: 0.6192
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5844 - val_accuracy: 0.7351 - val_loss: 0.6943
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6651 - val_accuracy: 0.7761 - val_loss: 0.4904
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5366 - val_accuracy: 0.7612 - val_loss: 0.4954
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6491 - val_accuracy: 0.7948 - val_loss: 0.5466
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6447 - val_accuracy: 0.7799 - val_loss: 0.4766
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5351 - val_accuracy: 0.4552 - val_loss: 1.7425
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.6452 - val_accuracy: 0.7724 - val_loss: 0.4857
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5495 - val_accuracy: 0.7090 - val_loss: 0.7957
Epoch 155/5000

In [44]:
# wandbの動作を終了させる
wandb.finish()

In [45]:
# wandbでsweep（グリッドサーチ）を行なうための設定
sweep_config = {
    'method': 'grid',
    'name': 'kaggle-titanic-sweep',
    'metric': {
        'goal': 'maximize',
        'name': 'accuracy'
    },
    'parameters': {
        'input_dense_shape': {'values': [8, 16, 24]},
        'hidden_dense_shape': {'values': [8, 16, 24]},
        'optimizer': {'values': ['sgd', 'rmsprop', 'adam']},
        'batch_size': {'values': [16, 32, 64]}
     }
}

# sweep_configの設定値でsweepを初期化する
sweep_id = wandb.sweep(sweep=sweep_config, project="kaggle-titanic")

Create sweep with ID: vp91c749
Sweep URL: https://wandb.ai/qhe202509-personal/kaggle-titanic/sweeps/vp91c749

In [46]:
# sweepを開始する
wandb.agent(sweep_id, function=train_model)

wandb: Agent Starting Run: y8yx3t7a with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5762 - loss: 27.3514 - val_accuracy: 0.6306 - val_loss: 0.8800
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.7242 - val_accuracy: 0.6306 - val_loss: 0.7987
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.7036 - val_accuracy: 0.6269 - val_loss: 0.7627
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.6164 - loss: 0.6956 - val_accuracy: 0.6306 - val_loss: 0.7402
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6885 - val_accuracy: 0.6306 - val_loss: 0.7214
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - accuracy: 0.6148 - loss: 0.6821 - val_accuracy: 0.6306 - val_loss: 0.7065
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6779 - val_accuracy: 0.6306 - val_loss: 0.6928
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6148 - loss: 0.6744 - val_accuracy: 0.6306 - val_loss: 0.6826
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6148 - loss: 0.6723 - val_accuracy: 0.6306 - val_loss: 0.6732
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.6148 - loss: 0.6712 - val_accuracy: 0.6306 - val_loss: 0.6665
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.6116 - loss: 0.6700 - val_accuracy: 0.6306 - val_loss: 0.6652
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.6116 - loss: 0.6695 - val_accuracy: 0.6306 - val_loss: 0.6644
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6116 - loss: 0.6689 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6306 - val_loss: 0.6632
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6116 - loss: 0.6683 - val_accuracy: 0.6306 - val_loss: 0.6625
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.6116 - loss: 0.6679 - val_accuracy: 0.6306 - val_loss: 0.6622
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6306 - val_loss: 0.6618
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6116 - loss: 0.6675 - val_accuracy: 0.6306 - val_loss: 0.6618
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.6116 - loss: 0.6674 - val_accuracy: 0.6306 - val_loss: 0.6619
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6116 - loss: 0.6673 - val_accuracy: 0.6306 - val_loss: 0.6621
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.6132 - loss: 0.6672 - val_accuracy: 0.6306 - val_loss: 0.6617
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6116 - loss: 0.6671 - val_accuracy: 0.6306 - val_loss: 0.6620
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.6116 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6621
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6116 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6619
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.6116 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6619
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6615
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6614
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6116 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6619
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6618
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6618
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6132 - loss: 0.6673 - val_accuracy: 0.6306 - val_loss: 0.6641
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6633
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6637
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6641
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6633
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6630
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6635
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6643
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6636
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6643
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6650
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6647
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6644
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6657
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6647
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6635
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6652
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6651
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6664
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6132 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6674
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6680
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6677
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6132 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6690
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6677
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6671
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6657
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6667
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6670
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6132 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6684
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6148 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6676
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6132 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6680
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.6148 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6671
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6132 - loss: 0.6654 - val_accuracy: 0.6306 - val_loss: 0.6674
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6306 - val_loss: 0.6699
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6269 - val_loss: 0.6714
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6306 - val_loss: 0.6696
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6148 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6697
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6148 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6701
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6132 - loss: 0.6655 - val_accuracy: 0.6306 - val_loss: 0.6699
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6148 - loss: 0.6653 - val_accuracy: 0.6269 - val_loss: 0.6707
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.6709
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6148 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6696
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.6713
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.6711
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.6148 - loss: 0.6653 - val_accuracy: 0.6269 - val_loss: 0.6726
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.6132 - loss: 0.6653 - val_accuracy: 0.6269 - val_loss: 0.6710
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6164 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.6739
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6148 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.6699
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.6132 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.6672
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6667
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6148 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.6671
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6148 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.6659
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6148 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.6679
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6696
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.6148 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.6694
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.6132 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.6681
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6132 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.6670
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6662
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6690
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6684
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6164 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6652
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.6632
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.6621
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.6672
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6164 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6604
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.6671
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6620
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.6590
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.6578
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6595
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.6576
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.6565
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.6560
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.6618
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.6601
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6148 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.6587
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.6584
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.6561
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6269 - val_loss: 0.6562
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6269 - val_loss: 0.6597
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6148 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6559
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.6554
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.6555
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.6560
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6555
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.6563
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.6561
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.6554
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.6555
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.6558
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6553
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6556
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6554
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6559
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6164 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.6556
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.6554
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6560
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6561
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6555
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6554
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.6579
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.6572
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6180 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.6572
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.6180 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.6590
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6164 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.6553
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6180 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.6556
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6180 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6554
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.6180 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6554
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6554
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6568
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.6570
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6556
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.6180 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6568
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6553
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6562
Epoch 153/5000

wandb: Agent Starting Run: 0ksvc9w0 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 32.7832 - val_accuracy: 0.5634 - val_loss: 15.3496
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5297 - loss: 6.9876 - val_accuracy: 0.5224 - val_loss: 4.0817
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.4944 - loss: 3.3332 - val_accuracy: 0.5261 - val_loss: 2.9438
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.4992 - loss: 2.4492 - val_accuracy: 0.5187 - val_loss: 2.0265
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.4799 - loss: 1.6380 - val_accuracy: 0.4776 - val_loss: 1.4412
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5201 - loss: 1.2400 - val_accuracy: 0.5299 - val_loss: 0.9880
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.5634 - loss: 0.9892 - val_accuracy: 0.6269 - val_loss: 0.8289
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6148 - loss: 0.7956 - val_accuracy: 0.4216 - val_loss: 1.1289
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.6196 - loss: 0.7796 - val_accuracy: 0.6866 - val_loss: 0.5910
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6565 - loss: 0.7327 - val_accuracy: 0.6269 - val_loss: 0.9954
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6469 - loss: 0.7517 - val_accuracy: 0.5522 - val_loss: 0.8318
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6469 - loss: 0.6985 - val_accuracy: 0.6007 - val_loss: 0.7527
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6276 - loss: 0.7532 - val_accuracy: 0.6791 - val_loss: 0.7305
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.7140 - val_accuracy: 0.6343 - val_loss: 0.9194
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.7369 - val_accuracy: 0.7015 - val_loss: 0.6388
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.6597 - loss: 0.6713 - val_accuracy: 0.7313 - val_loss: 0.5516
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6886 - loss: 0.6603 - val_accuracy: 0.4552 - val_loss: 1.4690
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6549 - loss: 0.7095 - val_accuracy: 0.7239 - val_loss: 0.5881
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7175 - loss: 0.6568 - val_accuracy: 0.7351 - val_loss: 0.5592
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6453 - loss: 0.7030 - val_accuracy: 0.6903 - val_loss: 0.7219
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7030 - loss: 0.5819 - val_accuracy: 0.7500 - val_loss: 0.5202
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6661 - loss: 0.6941 - val_accuracy: 0.5896 - val_loss: 0.7665
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6870 - loss: 0.6570 - val_accuracy: 0.7164 - val_loss: 0.6081
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.6854 - loss: 0.6432 - val_accuracy: 0.7425 - val_loss: 0.5521
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6918 - loss: 0.6884 - val_accuracy: 0.7910 - val_loss: 0.5127
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6664 - val_accuracy: 0.7873 - val_loss: 0.5099
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7047 - loss: 0.6260 - val_accuracy: 0.7164 - val_loss: 0.6308
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7127 - loss: 0.6270 - val_accuracy: 0.7761 - val_loss: 0.5269
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6982 - loss: 0.6106 - val_accuracy: 0.7910 - val_loss: 0.4955
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7127 - loss: 0.6669 - val_accuracy: 0.7463 - val_loss: 0.5433
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.7159 - loss: 0.6148 - val_accuracy: 0.7425 - val_loss: 0.5530
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6070 - val_accuracy: 0.7463 - val_loss: 0.5381
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6966 - loss: 0.6317 - val_accuracy: 0.7836 - val_loss: 0.5011
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7079 - loss: 0.6180 - val_accuracy: 0.7985 - val_loss: 0.4974
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7303 - loss: 0.5914 - val_accuracy: 0.7463 - val_loss: 0.5730
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7175 - loss: 0.6125 - val_accuracy: 0.6754 - val_loss: 0.7521
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7191 - loss: 0.6151 - val_accuracy: 0.7948 - val_loss: 0.4903
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7191 - loss: 0.5878 - val_accuracy: 0.7575 - val_loss: 0.5187
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7207 - loss: 0.6539 - val_accuracy: 0.7612 - val_loss: 0.4869
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7335 - loss: 0.5901 - val_accuracy: 0.7239 - val_loss: 0.6078
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.7400 - loss: 0.5761 - val_accuracy: 0.7799 - val_loss: 0.4873
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.7143 - loss: 0.6396 - val_accuracy: 0.7985 - val_loss: 0.4739
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.7191 - loss: 0.6260 - val_accuracy: 0.7500 - val_loss: 0.5233
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.7239 - loss: 0.6126 - val_accuracy: 0.6866 - val_loss: 0.6386
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7400 - loss: 0.5870 - val_accuracy: 0.7873 - val_loss: 0.4916
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7271 - loss: 0.6126 - val_accuracy: 0.7910 - val_loss: 0.4833
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7448 - loss: 0.5760 - val_accuracy: 0.7164 - val_loss: 0.6126
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.7191 - loss: 0.5872 - val_accuracy: 0.7164 - val_loss: 0.6548
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.6360 - val_accuracy: 0.7836 - val_loss: 0.5163
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7448 - loss: 0.5943 - val_accuracy: 0.7164 - val_loss: 0.7150
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7496 - loss: 0.5925 - val_accuracy: 0.7127 - val_loss: 0.6286
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7432 - loss: 0.5879 - val_accuracy: 0.7836 - val_loss: 0.5594
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7416 - loss: 0.5628 - val_accuracy: 0.7985 - val_loss: 0.4791
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7223 - loss: 0.6066 - val_accuracy: 0.7799 - val_loss: 0.4992
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7287 - loss: 0.6030 - val_accuracy: 0.7276 - val_loss: 0.6519
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.7576 - loss: 0.5501 - val_accuracy: 0.6940 - val_loss: 0.8114
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7608 - loss: 0.5582 - val_accuracy: 0.6194 - val_loss: 0.7765
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7335 - loss: 0.6243 - val_accuracy: 0.7873 - val_loss: 0.4860
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.7512 - loss: 0.5874 - val_accuracy: 0.7985 - val_loss: 0.4849
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.7608 - loss: 0.5778 - val_accuracy: 0.6754 - val_loss: 0.8694
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.7560 - loss: 0.5788 - val_accuracy: 0.7724 - val_loss: 0.5031
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5710 - val_accuracy: 0.7910 - val_loss: 0.5345
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.7448 - loss: 0.5755 - val_accuracy: 0.7873 - val_loss: 0.4855
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7416 - loss: 0.5827 - val_accuracy: 0.7201 - val_loss: 0.6762
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.7512 - loss: 0.5843 - val_accuracy: 0.7799 - val_loss: 0.4779
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7640 - loss: 0.5599 - val_accuracy: 0.7761 - val_loss: 0.4803
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7576 - loss: 0.5599 - val_accuracy: 0.7948 - val_loss: 0.4992
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7303 - loss: 0.6084 - val_accuracy: 0.7724 - val_loss: 0.4929
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7640 - loss: 0.5727 - val_accuracy: 0.7649 - val_loss: 0.5356
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7512 - loss: 0.5611 - val_accuracy: 0.5858 - val_loss: 0.8420
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7576 - loss: 0.5542 - val_accuracy: 0.7948 - val_loss: 0.4972
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7640 - loss: 0.5468 - val_accuracy: 0.7948 - val_loss: 0.5183
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.7335 - loss: 0.6101 - val_accuracy: 0.7575 - val_loss: 0.5730
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7689 - loss: 0.5703 - val_accuracy: 0.7612 - val_loss: 0.5550
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7769 - loss: 0.5364 - val_accuracy: 0.6194 - val_loss: 0.8040
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7705 - loss: 0.5548 - val_accuracy: 0.7761 - val_loss: 0.4846
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.7624 - loss: 0.5497 - val_accuracy: 0.7052 - val_loss: 0.7791
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7705 - loss: 0.5533 - val_accuracy: 0.7575 - val_loss: 0.5539
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7464 - loss: 0.5835 - val_accuracy: 0.7724 - val_loss: 0.5099
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7673 - loss: 0.5605 - val_accuracy: 0.7425 - val_loss: 0.6470
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7689 - loss: 0.5536 - val_accuracy: 0.7910 - val_loss: 0.5331
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7608 - loss: 0.5650 - val_accuracy: 0.7799 - val_loss: 0.4911
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.7705 - loss: 0.5520 - val_accuracy: 0.7687 - val_loss: 0.6036
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5728 - val_accuracy: 0.7873 - val_loss: 0.5171
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7817 - loss: 0.5316 - val_accuracy: 0.7500 - val_loss: 0.6215
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7689 - loss: 0.5710 - val_accuracy: 0.7873 - val_loss: 0.5006
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7769 - loss: 0.5226 - val_accuracy: 0.7799 - val_loss: 0.5000
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7640 - loss: 0.5378 - val_accuracy: 0.7910 - val_loss: 0.5087
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7769 - loss: 0.5489 - val_accuracy: 0.7463 - val_loss: 0.6239
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7721 - loss: 0.5508 - val_accuracy: 0.7724 - val_loss: 0.5248
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7769 - loss: 0.5515 - val_accuracy: 0.5896 - val_loss: 0.8481
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.7624 - loss: 0.5800 - val_accuracy: 0.7836 - val_loss: 0.5300
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7689 - loss: 0.5418 - val_accuracy: 0.7463 - val_loss: 0.6322
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7737 - loss: 0.5615 - val_accuracy: 0.7612 - val_loss: 0.5651
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7608 - loss: 0.5771 - val_accuracy: 0.7761 - val_loss: 0.5000
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7849 - loss: 0.5039 - val_accuracy: 0.5821 - val_loss: 0.8582
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7673 - loss: 0.6038 - val_accuracy: 0.7500 - val_loss: 0.7136
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7769 - loss: 0.5109 - val_accuracy: 0.7575 - val_loss: 0.6212
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7624 - loss: 0.5591 - val_accuracy: 0.7910 - val_loss: 0.5350
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7737 - loss: 0.5542 - val_accuracy: 0.6530 - val_loss: 0.7542
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5392 - val_accuracy: 0.7463 - val_loss: 0.6249
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7640 - loss: 0.5399 - val_accuracy: 0.7873 - val_loss: 0.4976
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7689 - loss: 0.5586 - val_accuracy: 0.7127 - val_loss: 0.8360
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7464 - loss: 0.5984 - val_accuracy: 0.7575 - val_loss: 0.5849
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7689 - loss: 0.5577 - val_accuracy: 0.7985 - val_loss: 0.5905
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7913 - loss: 0.5184 - val_accuracy: 0.7724 - val_loss: 0.5300
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7705 - loss: 0.5739 - val_accuracy: 0.7500 - val_loss: 0.6233
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7801 - loss: 0.5170 - val_accuracy: 0.7799 - val_loss: 0.6030
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.7528 - loss: 0.5607 - val_accuracy: 0.7799 - val_loss: 0.4941
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7865 - loss: 0.5158 - val_accuracy: 0.7910 - val_loss: 0.4867
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7721 - loss: 0.5300 - val_accuracy: 0.6455 - val_loss: 0.7815
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7705 - loss: 0.5609 - val_accuracy: 0.7799 - val_loss: 0.4969
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.7576 - loss: 0.5329 - val_accuracy: 0.7836 - val_loss: 0.4986
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.7753 - loss: 0.5288 - val_accuracy: 0.7724 - val_loss: 0.5081
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7705 - loss: 0.5588 - val_accuracy: 0.7687 - val_loss: 0.5724
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.7833 - loss: 0.5230 - val_accuracy: 0.7873 - val_loss: 0.5074
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5218 - val_accuracy: 0.7836 - val_loss: 0.5250
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7705 - loss: 0.5487 - val_accuracy: 0.6791 - val_loss: 0.9098
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7881 - loss: 0.5099 - val_accuracy: 0.4701 - val_loss: 1.6189
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7753 - loss: 0.5264 - val_accuracy: 0.7612 - val_loss: 0.5925
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7785 - loss: 0.5209 - val_accuracy: 0.7500 - val_loss: 0.7187
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7817 - loss: 0.5143 - val_accuracy: 0.6903 - val_loss: 0.7190
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.7705 - loss: 0.5384 - val_accuracy: 0.7873 - val_loss: 0.5088
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7496 - loss: 0.5412 - val_accuracy: 0.7799 - val_loss: 0.4921
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7689 - loss: 0.5443 - val_accuracy: 0.7873 - val_loss: 0.5018
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7817 - loss: 0.5512 - val_accuracy: 0.7761 - val_loss: 0.5037
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7673 - loss: 0.5501 - val_accuracy: 0.7836 - val_loss: 0.5206
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7753 - loss: 0.5073 - val_accuracy: 0.6642 - val_loss: 0.9860
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7833 - loss: 0.5096 - val_accuracy: 0.6455 - val_loss: 0.7594
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5278 - val_accuracy: 0.7127 - val_loss: 0.7080
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.7496 - loss: 0.5666 - val_accuracy: 0.7761 - val_loss: 0.4829
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7769 - loss: 0.5318 - val_accuracy: 0.7575 - val_loss: 0.6024
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7785 - loss: 0.5264 - val_accuracy: 0.7873 - val_loss: 0.5193
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7592 - loss: 0.5490 - val_accuracy: 0.6754 - val_loss: 0.7180
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7608 - loss: 0.5443 - val_accuracy: 0.7537 - val_loss: 0.6239
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.7865 - loss: 0.5168 - val_accuracy: 0.7313 - val_loss: 0.7608
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7785 - loss: 0.5343 - val_accuracy: 0.7799 - val_loss: 0.5114
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7897 - loss: 0.5185 - val_accuracy: 0.7799 - val_loss: 0.5051
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7624 - loss: 0.5549 - val_accuracy: 0.5896 - val_loss: 0.8661
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7785 - loss: 0.5284 - val_accuracy: 0.7836 - val_loss: 0.5301
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7640 - loss: 0.5663 - val_accuracy: 0.7687 - val_loss: 0.4968
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5453 - val_accuracy: 0.7537 - val_loss: 0.6401
Epoch 142: early stopping

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: g3g9rk2a with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 48.9469 - val_accuracy: 0.6269 - val_loss: 41.1949
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 36.0961 - val_accuracy: 0.6269 - val_loss: 31.1179
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 27.5617 - val_accuracy: 0.6269 - val_loss: 23.1093
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 18.1913 - val_accuracy: 0.6269 - val_loss: 12.5428
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 7.6706 - val_accuracy: 0.6269 - val_loss: 3.6209
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5875 - loss: 1.8123 - val_accuracy: 0.5709 - val_loss: 0.9395
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.5859 - loss: 0.7959 - val_accuracy: 0.5373 - val_loss: 0.7997
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.6180 - loss: 0.7071 - val_accuracy: 0.6119 - val_loss: 0.7233
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.6180 - loss: 0.6784 - val_accuracy: 0.6269 - val_loss: 0.7087
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.6340 - loss: 0.6704 - val_accuracy: 0.6343 - val_loss: 0.7429
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.6517 - loss: 0.6562 - val_accuracy: 0.6567 - val_loss: 0.6819
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6565 - loss: 0.6468 - val_accuracy: 0.6604 - val_loss: 0.6880
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.6693 - loss: 0.6457 - val_accuracy: 0.5560 - val_loss: 0.7142
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6437 - loss: 0.6550 - val_accuracy: 0.6679 - val_loss: 0.6734
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.6693 - loss: 0.6478 - val_accuracy: 0.6828 - val_loss: 0.6666
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.6709 - loss: 0.6447 - val_accuracy: 0.6791 - val_loss: 0.6657
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.6790 - loss: 0.6320 - val_accuracy: 0.6828 - val_loss: 0.6608
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6774 - loss: 0.6328 - val_accuracy: 0.6791 - val_loss: 0.6639
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6774 - loss: 0.6344 - val_accuracy: 0.6828 - val_loss: 0.6599
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6822 - loss: 0.6325 - val_accuracy: 0.6791 - val_loss: 0.6570
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6918 - loss: 0.6319 - val_accuracy: 0.6828 - val_loss: 0.6591
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6742 - loss: 0.6272 - val_accuracy: 0.6828 - val_loss: 0.6560
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6774 - loss: 0.6258 - val_accuracy: 0.6828 - val_loss: 0.6542
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6902 - loss: 0.6240 - val_accuracy: 0.6791 - val_loss: 0.6553
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6918 - loss: 0.6237 - val_accuracy: 0.6828 - val_loss: 0.6536
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6774 - loss: 0.6207 - val_accuracy: 0.6940 - val_loss: 0.6704
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.6870 - loss: 0.6286 - val_accuracy: 0.6754 - val_loss: 0.6599
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.6250 - val_accuracy: 0.6754 - val_loss: 0.6432
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6854 - loss: 0.6265 - val_accuracy: 0.6791 - val_loss: 0.6449
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.6742 - loss: 0.6295 - val_accuracy: 0.6754 - val_loss: 0.6424
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6854 - loss: 0.6148 - val_accuracy: 0.6791 - val_loss: 0.6456
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6950 - loss: 0.6155 - val_accuracy: 0.6791 - val_loss: 0.6413
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6950 - loss: 0.6142 - val_accuracy: 0.6866 - val_loss: 0.6470
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6854 - loss: 0.6176 - val_accuracy: 0.6791 - val_loss: 0.6399
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6918 - loss: 0.6138 - val_accuracy: 0.6866 - val_loss: 0.6384
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6886 - loss: 0.6171 - val_accuracy: 0.6791 - val_loss: 0.6349
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6982 - loss: 0.6067 - val_accuracy: 0.6828 - val_loss: 0.6324
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6902 - loss: 0.6069 - val_accuracy: 0.6828 - val_loss: 0.6310
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6918 - loss: 0.6045 - val_accuracy: 0.6828 - val_loss: 0.6337
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6902 - loss: 0.6063 - val_accuracy: 0.6791 - val_loss: 0.6298
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.6028 - val_accuracy: 0.6828 - val_loss: 0.6281
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7014 - loss: 0.6013 - val_accuracy: 0.6903 - val_loss: 0.6262
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.6061 - val_accuracy: 0.6978 - val_loss: 0.6423
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6886 - loss: 0.6049 - val_accuracy: 0.7127 - val_loss: 0.6333
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.6982 - loss: 0.5982 - val_accuracy: 0.6866 - val_loss: 0.6220
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7095 - loss: 0.5953 - val_accuracy: 0.6978 - val_loss: 0.6224
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7127 - loss: 0.5926 - val_accuracy: 0.7015 - val_loss: 0.6210
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6966 - loss: 0.5959 - val_accuracy: 0.6903 - val_loss: 0.6154
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7095 - loss: 0.5960 - val_accuracy: 0.6978 - val_loss: 0.6441
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7014 - loss: 0.6015 - val_accuracy: 0.6940 - val_loss: 0.6161
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.6982 - loss: 0.5870 - val_accuracy: 0.7164 - val_loss: 0.6170
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.7127 - loss: 0.5870 - val_accuracy: 0.7052 - val_loss: 0.6122
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7159 - loss: 0.5862 - val_accuracy: 0.6940 - val_loss: 0.6102
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7047 - loss: 0.5848 - val_accuracy: 0.7052 - val_loss: 0.6097
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7127 - loss: 0.5818 - val_accuracy: 0.7127 - val_loss: 0.6090
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7207 - loss: 0.5802 - val_accuracy: 0.7052 - val_loss: 0.6065
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.7191 - loss: 0.5784 - val_accuracy: 0.7015 - val_loss: 0.6026
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7175 - loss: 0.5762 - val_accuracy: 0.7127 - val_loss: 0.6024
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5763 - val_accuracy: 0.7090 - val_loss: 0.5945
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7175 - loss: 0.5753 - val_accuracy: 0.7201 - val_loss: 0.5941
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7159 - loss: 0.5709 - val_accuracy: 0.7052 - val_loss: 0.5859
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7127 - loss: 0.5767 - val_accuracy: 0.7052 - val_loss: 0.5823
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7111 - loss: 0.5712 - val_accuracy: 0.7388 - val_loss: 0.5931
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7191 - loss: 0.5728 - val_accuracy: 0.7052 - val_loss: 0.5784
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7207 - loss: 0.5713 - val_accuracy: 0.7127 - val_loss: 0.5729
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7111 - loss: 0.5692 - val_accuracy: 0.7090 - val_loss: 0.5700
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7191 - loss: 0.5654 - val_accuracy: 0.7127 - val_loss: 0.5675
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7239 - loss: 0.5623 - val_accuracy: 0.7164 - val_loss: 0.5645
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7287 - loss: 0.5583 - val_accuracy: 0.7127 - val_loss: 0.5630
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7159 - loss: 0.5655 - val_accuracy: 0.7164 - val_loss: 0.5612
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7223 - loss: 0.5569 - val_accuracy: 0.7313 - val_loss: 0.5665
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5551 - val_accuracy: 0.7388 - val_loss: 0.5591
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7287 - loss: 0.5548 - val_accuracy: 0.7351 - val_loss: 0.5561
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7303 - loss: 0.5525 - val_accuracy: 0.7201 - val_loss: 0.5486
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7239 - loss: 0.5521 - val_accuracy: 0.7276 - val_loss: 0.5586
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.5560 - val_accuracy: 0.7164 - val_loss: 0.5886
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7416 - loss: 0.5460 - val_accuracy: 0.7388 - val_loss: 0.5491
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7287 - loss: 0.5464 - val_accuracy: 0.7276 - val_loss: 0.5432
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7319 - loss: 0.5362 - val_accuracy: 0.7388 - val_loss: 0.5414
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.7400 - loss: 0.5367 - val_accuracy: 0.7425 - val_loss: 0.5694
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7448 - loss: 0.5430 - val_accuracy: 0.7500 - val_loss: 0.5504
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7464 - loss: 0.5390 - val_accuracy: 0.7425 - val_loss: 0.5404
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7464 - loss: 0.5398 - val_accuracy: 0.7463 - val_loss: 0.5335
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7592 - loss: 0.5298 - val_accuracy: 0.7351 - val_loss: 0.5510
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.7432 - loss: 0.5393 - val_accuracy: 0.7276 - val_loss: 0.5413
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.7544 - loss: 0.5301 - val_accuracy: 0.7388 - val_loss: 0.5388
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.7849 - loss: 0.5261 - val_accuracy: 0.7575 - val_loss: 0.5383
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.7464 - loss: 0.5245 - val_accuracy: 0.7127 - val_loss: 0.5640
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5188 - val_accuracy: 0.7463 - val_loss: 0.5275
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7640 - loss: 0.5134 - val_accuracy: 0.7500 - val_loss: 0.5620
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7544 - loss: 0.5256 - val_accuracy: 0.7687 - val_loss: 0.5228
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7512 - loss: 0.5170 - val_accuracy: 0.7612 - val_loss: 0.5265
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7512 - loss: 0.5264 - val_accuracy: 0.7612 - val_loss: 0.5245
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7624 - loss: 0.5218 - val_accuracy: 0.7388 - val_loss: 0.5239
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7592 - loss: 0.5072 - val_accuracy: 0.7724 - val_loss: 0.5239
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7689 - loss: 0.5080 - val_accuracy: 0.7388 - val_loss: 0.5221
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7689 - loss: 0.5050 - val_accuracy: 0.7463 - val_loss: 0.5301
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.4994 - val_accuracy: 0.7910 - val_loss: 0.5331
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7640 - loss: 0.5044 - val_accuracy: 0.7575 - val_loss: 0.5206
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7769 - loss: 0.5077 - val_accuracy: 0.7612 - val_loss: 0.5195
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7721 - loss: 0.5068 - val_accuracy: 0.7575 - val_loss: 0.5168
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5041 - val_accuracy: 0.7799 - val_loss: 0.5233
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5039 - val_accuracy: 0.7612 - val_loss: 0.5206
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7753 - loss: 0.5035 - val_accuracy: 0.7201 - val_loss: 0.5664
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7753 - loss: 0.5044 - val_accuracy: 0.7910 - val_loss: 0.5281
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7865 - loss: 0.5039 - val_accuracy: 0.7649 - val_loss: 0.5151
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.7673 - loss: 0.5029 - val_accuracy: 0.7724 - val_loss: 0.5270
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7881 - loss: 0.4959 - val_accuracy: 0.7724 - val_loss: 0.5107
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7833 - loss: 0.4947 - val_accuracy: 0.7649 - val_loss: 0.5187
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7833 - loss: 0.4868 - val_accuracy: 0.7649 - val_loss: 0.5272
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7673 - loss: 0.5186 - val_accuracy: 0.7575 - val_loss: 0.5238
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7721 - loss: 0.5008 - val_accuracy: 0.7500 - val_loss: 0.5226
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7753 - loss: 0.5034 - val_accuracy: 0.7463 - val_loss: 0.5112
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7769 - loss: 0.4970 - val_accuracy: 0.7612 - val_loss: 0.5123
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4910 - val_accuracy: 0.7724 - val_loss: 0.5047
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7753 - loss: 0.4888 - val_accuracy: 0.7425 - val_loss: 0.5140
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7913 - loss: 0.4808 - val_accuracy: 0.7388 - val_loss: 0.5183
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7978 - loss: 0.4890 - val_accuracy: 0.7425 - val_loss: 0.5178
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7769 - loss: 0.4909 - val_accuracy: 0.7612 - val_loss: 0.5192
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7785 - loss: 0.4964 - val_accuracy: 0.7836 - val_loss: 0.5178
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7833 - loss: 0.4885 - val_accuracy: 0.8060 - val_loss: 0.5443
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7978 - loss: 0.4830 - val_accuracy: 0.7873 - val_loss: 0.5043
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.7753 - loss: 0.4932 - val_accuracy: 0.7687 - val_loss: 0.5114
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7945 - loss: 0.4833 - val_accuracy: 0.7537 - val_loss: 0.5169
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.8026 - loss: 0.4785 - val_accuracy: 0.7687 - val_loss: 0.5118
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7737 - loss: 0.4847 - val_accuracy: 0.7873 - val_loss: 0.5573
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7817 - loss: 0.4941 - val_accuracy: 0.7537 - val_loss: 0.5115
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7737 - loss: 0.4884 - val_accuracy: 0.7687 - val_loss: 0.5041
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7897 - loss: 0.4736 - val_accuracy: 0.7724 - val_loss: 0.5091
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.4875 - val_accuracy: 0.7687 - val_loss: 0.5065
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7881 - loss: 0.4737 - val_accuracy: 0.7910 - val_loss: 0.5232
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.8074 - loss: 0.4717 - val_accuracy: 0.7575 - val_loss: 0.5009
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7994 - loss: 0.4852 - val_accuracy: 0.7873 - val_loss: 0.5257
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7737 - loss: 0.4838 - val_accuracy: 0.7425 - val_loss: 0.5255
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4744 - val_accuracy: 0.7463 - val_loss: 0.5121
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.7849 - loss: 0.4771 - val_accuracy: 0.7761 - val_loss: 0.4989
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7978 - loss: 0.4741 - val_accuracy: 0.7687 - val_loss: 0.5096
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7994 - loss: 0.4734 - val_accuracy: 0.7724 - val_loss: 0.5208
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7929 - loss: 0.4743 - val_accuracy: 0.7649 - val_loss: 0.5017
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.8010 - loss: 0.4721 - val_accuracy: 0.7724 - val_loss: 0.5592
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7913 - loss: 0.4871 - val_accuracy: 0.7388 - val_loss: 0.5302
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7978 - loss: 0.4785 - val_accuracy: 0.7687 - val_loss: 0.4978
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.8074 - loss: 0.4662 - val_accuracy: 0.7687 - val_loss: 0.5395
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.8010 - loss: 0.4725 - val_accuracy: 0.7687 - val_loss: 0.4987
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.8106 - loss: 0.4704 - val_accuracy: 0.7873 - val_loss: 0.5048
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7961 - loss: 0.4785 - val_accuracy: 0.7724 - val_loss: 0.4973
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7833 - loss: 0.4757 - val_accuracy: 0.7724 - val_loss: 0.5281
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7978 - loss: 0.4721 - val_accuracy: 0.7649 - val_loss: 0.4981
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.7929 - loss: 0.4770 - val_accuracy: 0.7873 - val_loss: 0.5019
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7897 - loss: 0.4664 - val_accuracy: 0.7575 - val_loss: 0.5176
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.8010 - loss: 0.4662 - val_accuracy: 0.7724 - val_loss: 0.4985
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7801 - loss: 0.4685 - val_accuracy: 0.7612 - val_loss: 0.5029
Epoch 153/5000

wandb: Agent Starting Run: gu481c0e with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5506 - loss: 10.6803 - val_accuracy: 0.6269 - val_loss: 0.6890
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6877 - val_accuracy: 0.6269 - val_loss: 0.6847
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.6116 - loss: 0.6843 - val_accuracy: 0.6269 - val_loss: 0.6810
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6116 - loss: 0.6814 - val_accuracy: 0.6269 - val_loss: 0.6780
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.6116 - loss: 0.6791 - val_accuracy: 0.6269 - val_loss: 0.6755
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6116 - loss: 0.6772 - val_accuracy: 0.6269 - val_loss: 0.6733
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.6116 - loss: 0.6756 - val_accuracy: 0.6269 - val_loss: 0.6715
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.6116 - loss: 0.6743 - val_accuracy: 0.6269 - val_loss: 0.6700
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6116 - loss: 0.6732 - val_accuracy: 0.6269 - val_loss: 0.6687
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6116 - loss: 0.6723 - val_accuracy: 0.6269 - val_loss: 0.6677
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6716 - val_accuracy: 0.6269 - val_loss: 0.6668
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6116 - loss: 0.6710 - val_accuracy: 0.6269 - val_loss: 0.6660
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6116 - loss: 0.6706 - val_accuracy: 0.6269 - val_loss: 0.6653
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6116 - loss: 0.6701 - val_accuracy: 0.6269 - val_loss: 0.6648
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.6116 - loss: 0.6698 - val_accuracy: 0.6269 - val_loss: 0.6643
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.6116 - loss: 0.6695 - val_accuracy: 0.6269 - val_loss: 0.6639
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6116 - loss: 0.6693 - val_accuracy: 0.6269 - val_loss: 0.6635
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6116 - loss: 0.6690 - val_accuracy: 0.6269 - val_loss: 0.6632
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.6116 - loss: 0.6689 - val_accuracy: 0.6269 - val_loss: 0.6630
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.6116 - loss: 0.6687 - val_accuracy: 0.6269 - val_loss: 0.6627
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6116 - loss: 0.6686 - val_accuracy: 0.6269 - val_loss: 0.6625
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6116 - loss: 0.6685 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.6116 - loss: 0.6685 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6269 - val_loss: 0.6621
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6269 - val_loss: 0.6620
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6269 - val_loss: 0.6619
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6116 - loss: 0.6683 - val_accuracy: 0.6269 - val_loss: 0.6618
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6683 - val_accuracy: 0.6269 - val_loss: 0.6617
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6617
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6616
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6615
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6615
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6615
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 153/5000

wandb: Agent Starting Run: 91amt0s3 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5714 - loss: 4.7119 - val_accuracy: 0.5261 - val_loss: 1.2688
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6035 - loss: 1.2426 - val_accuracy: 0.6194 - val_loss: 0.8850
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6340 - loss: 0.9455 - val_accuracy: 0.6642 - val_loss: 0.7568
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6388 - loss: 0.8627 - val_accuracy: 0.4590 - val_loss: 1.2862
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.6308 - loss: 0.8096 - val_accuracy: 0.5896 - val_loss: 0.8283
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.8133 - val_accuracy: 0.5522 - val_loss: 0.8595
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.6870 - loss: 0.7077 - val_accuracy: 0.6119 - val_loss: 1.0110
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.6549 - loss: 0.7551 - val_accuracy: 0.5746 - val_loss: 0.8636
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6613 - loss: 0.7250 - val_accuracy: 0.6567 - val_loss: 0.7731
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.6677 - loss: 0.6919 - val_accuracy: 0.6903 - val_loss: 0.6646
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.6501 - loss: 0.7063 - val_accuracy: 0.7052 - val_loss: 0.6241
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.6661 - loss: 0.7026 - val_accuracy: 0.7090 - val_loss: 0.6381
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.6661 - loss: 0.6631 - val_accuracy: 0.4925 - val_loss: 1.1506
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.6822 - loss: 0.6568 - val_accuracy: 0.7090 - val_loss: 0.6383
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6742 - loss: 0.6820 - val_accuracy: 0.5336 - val_loss: 0.8768
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.6870 - loss: 0.6553 - val_accuracy: 0.7015 - val_loss: 0.6522
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7030 - loss: 0.6638 - val_accuracy: 0.7351 - val_loss: 0.5846
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.7143 - loss: 0.6248 - val_accuracy: 0.7201 - val_loss: 0.6305
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.6918 - loss: 0.6681 - val_accuracy: 0.5784 - val_loss: 0.8570
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.7047 - loss: 0.6264 - val_accuracy: 0.7313 - val_loss: 0.5950
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.7271 - loss: 0.5750 - val_accuracy: 0.6231 - val_loss: 1.4485
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6806 - loss: 0.6666 - val_accuracy: 0.5522 - val_loss: 0.7881
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6982 - loss: 0.6154 - val_accuracy: 0.7351 - val_loss: 0.5882
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6918 - loss: 0.6081 - val_accuracy: 0.7351 - val_loss: 0.5595
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7335 - loss: 0.6435 - val_accuracy: 0.6903 - val_loss: 0.6866
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7079 - loss: 0.6114 - val_accuracy: 0.7239 - val_loss: 0.5894
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7127 - loss: 0.6165 - val_accuracy: 0.7201 - val_loss: 0.6013
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7335 - loss: 0.5582 - val_accuracy: 0.7351 - val_loss: 0.5497
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7255 - loss: 0.5971 - val_accuracy: 0.7351 - val_loss: 0.5473
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.7271 - loss: 0.5998 - val_accuracy: 0.6493 - val_loss: 0.7489
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7239 - loss: 0.5839 - val_accuracy: 0.7351 - val_loss: 0.5398
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7368 - loss: 0.5910 - val_accuracy: 0.7351 - val_loss: 0.6483
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7528 - loss: 0.5974 - val_accuracy: 0.6269 - val_loss: 0.7417
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 0.7512 - loss: 0.5739 - val_accuracy: 0.7388 - val_loss: 0.5359
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.7271 - loss: 0.5930 - val_accuracy: 0.6828 - val_loss: 0.7782
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7303 - loss: 0.5541 - val_accuracy: 0.7425 - val_loss: 0.5328
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7319 - loss: 0.5810 - val_accuracy: 0.5672 - val_loss: 0.8548
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7640 - loss: 0.5546 - val_accuracy: 0.7500 - val_loss: 0.5614
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7191 - loss: 0.6031 - val_accuracy: 0.7313 - val_loss: 0.6475
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7432 - loss: 0.5805 - val_accuracy: 0.6978 - val_loss: 0.7081
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7448 - loss: 0.5439 - val_accuracy: 0.7015 - val_loss: 0.6933
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7448 - loss: 0.5843 - val_accuracy: 0.7313 - val_loss: 0.5362
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7319 - loss: 0.5781 - val_accuracy: 0.6940 - val_loss: 0.6452
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7560 - loss: 0.5288 - val_accuracy: 0.7276 - val_loss: 0.5835
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7592 - loss: 0.5435 - val_accuracy: 0.6418 - val_loss: 0.9997
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7608 - loss: 0.5771 - val_accuracy: 0.6866 - val_loss: 0.6798
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7432 - loss: 0.5731 - val_accuracy: 0.6903 - val_loss: 0.6992
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7576 - loss: 0.5827 - val_accuracy: 0.7500 - val_loss: 0.5412
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5337 - val_accuracy: 0.7201 - val_loss: 0.5836
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7432 - loss: 0.5362 - val_accuracy: 0.7537 - val_loss: 0.5337
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5379 - val_accuracy: 0.7201 - val_loss: 0.6893
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7448 - loss: 0.5747 - val_accuracy: 0.5746 - val_loss: 0.8535
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7657 - loss: 0.5064 - val_accuracy: 0.6940 - val_loss: 0.6995
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7592 - loss: 0.5531 - val_accuracy: 0.6716 - val_loss: 0.8841
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7592 - loss: 0.5429 - val_accuracy: 0.7351 - val_loss: 0.5770
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7657 - loss: 0.5371 - val_accuracy: 0.7575 - val_loss: 0.5339
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7689 - loss: 0.5506 - val_accuracy: 0.7463 - val_loss: 0.5569
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7657 - loss: 0.5355 - val_accuracy: 0.7537 - val_loss: 0.6131
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7528 - loss: 0.5456 - val_accuracy: 0.7463 - val_loss: 0.6101
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7737 - loss: 0.5061 - val_accuracy: 0.7276 - val_loss: 0.6411
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7560 - loss: 0.5147 - val_accuracy: 0.7164 - val_loss: 0.6533
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7640 - loss: 0.5285 - val_accuracy: 0.7276 - val_loss: 0.6071
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7657 - loss: 0.5183 - val_accuracy: 0.6903 - val_loss: 0.7422
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7560 - loss: 0.5078 - val_accuracy: 0.7575 - val_loss: 0.5244
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.7801 - loss: 0.5029 - val_accuracy: 0.7164 - val_loss: 0.6243
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7544 - loss: 0.5270 - val_accuracy: 0.7537 - val_loss: 0.5159
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7753 - loss: 0.5263 - val_accuracy: 0.7388 - val_loss: 0.5612
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7929 - loss: 0.4999 - val_accuracy: 0.7612 - val_loss: 0.5711
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7785 - loss: 0.4996 - val_accuracy: 0.7575 - val_loss: 0.5357
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7865 - loss: 0.5204 - val_accuracy: 0.7537 - val_loss: 0.5155
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7705 - loss: 0.5154 - val_accuracy: 0.7724 - val_loss: 0.5497
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7769 - loss: 0.5407 - val_accuracy: 0.7425 - val_loss: 0.5485
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7737 - loss: 0.5238 - val_accuracy: 0.7687 - val_loss: 0.5176
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7833 - loss: 0.5116 - val_accuracy: 0.7015 - val_loss: 0.6866
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7721 - loss: 0.5165 - val_accuracy: 0.7388 - val_loss: 0.5912
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7881 - loss: 0.4961 - val_accuracy: 0.7649 - val_loss: 0.5222
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.8010 - loss: 0.5096 - val_accuracy: 0.7463 - val_loss: 0.5699
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7849 - loss: 0.5086 - val_accuracy: 0.7612 - val_loss: 0.5311
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7801 - loss: 0.4946 - val_accuracy: 0.7537 - val_loss: 0.5183
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5150 - val_accuracy: 0.7687 - val_loss: 0.5290
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7673 - loss: 0.5313 - val_accuracy: 0.7575 - val_loss: 0.5146
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7897 - loss: 0.4953 - val_accuracy: 0.7649 - val_loss: 0.5253
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7753 - loss: 0.4962 - val_accuracy: 0.7313 - val_loss: 0.5574
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7817 - loss: 0.5041 - val_accuracy: 0.7649 - val_loss: 0.5188
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7817 - loss: 0.4988 - val_accuracy: 0.7463 - val_loss: 0.5536
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7721 - loss: 0.5061 - val_accuracy: 0.6903 - val_loss: 0.6509
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7897 - loss: 0.5293 - val_accuracy: 0.7500 - val_loss: 0.5435
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7994 - loss: 0.4789 - val_accuracy: 0.7537 - val_loss: 0.5435
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7769 - loss: 0.4777 - val_accuracy: 0.6903 - val_loss: 0.7017
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5224 - val_accuracy: 0.6455 - val_loss: 0.7029
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7945 - loss: 0.4957 - val_accuracy: 0.7425 - val_loss: 0.5440
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.7785 - loss: 0.5047 - val_accuracy: 0.7201 - val_loss: 0.6132
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7961 - loss: 0.4928 - val_accuracy: 0.7724 - val_loss: 0.5152
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7849 - loss: 0.5192 - val_accuracy: 0.7724 - val_loss: 0.5329
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7978 - loss: 0.4741 - val_accuracy: 0.7612 - val_loss: 0.5636
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7769 - loss: 0.5018 - val_accuracy: 0.7575 - val_loss: 0.5370
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7817 - loss: 0.4992 - val_accuracy: 0.7649 - val_loss: 0.5190
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7705 - loss: 0.5140 - val_accuracy: 0.7687 - val_loss: 0.5173
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7881 - loss: 0.4795 - val_accuracy: 0.7537 - val_loss: 0.5422
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7849 - loss: 0.4955 - val_accuracy: 0.7351 - val_loss: 0.5645
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.8026 - loss: 0.4879 - val_accuracy: 0.7537 - val_loss: 0.5256
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7994 - loss: 0.4745 - val_accuracy: 0.7201 - val_loss: 0.6558
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.7929 - loss: 0.4763 - val_accuracy: 0.7724 - val_loss: 0.5238
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7945 - loss: 0.4926 - val_accuracy: 0.7687 - val_loss: 0.5052
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7961 - loss: 0.4812 - val_accuracy: 0.7351 - val_loss: 0.6254
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7705 - loss: 0.4935 - val_accuracy: 0.7761 - val_loss: 0.5218
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7865 - loss: 0.4714 - val_accuracy: 0.7052 - val_loss: 0.6689
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7913 - loss: 0.4830 - val_accuracy: 0.7537 - val_loss: 0.5228
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7978 - loss: 0.4980 - val_accuracy: 0.7425 - val_loss: 0.5480
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7865 - loss: 0.4773 - val_accuracy: 0.7500 - val_loss: 0.5329
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7833 - loss: 0.4960 - val_accuracy: 0.7612 - val_loss: 0.5215
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.7929 - loss: 0.4929 - val_accuracy: 0.7649 - val_loss: 0.5080
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7945 - loss: 0.4690 - val_accuracy: 0.7313 - val_loss: 0.5937
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7913 - loss: 0.5033 - val_accuracy: 0.7463 - val_loss: 0.5153
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.8058 - loss: 0.4780 - val_accuracy: 0.7761 - val_loss: 0.5442
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7913 - loss: 0.4863 - val_accuracy: 0.7575 - val_loss: 0.5093
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7897 - loss: 0.4778 - val_accuracy: 0.7649 - val_loss: 0.5889
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7817 - loss: 0.4801 - val_accuracy: 0.7537 - val_loss: 0.5099
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7865 - loss: 0.4897 - val_accuracy: 0.7351 - val_loss: 0.6184
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7849 - loss: 0.4622 - val_accuracy: 0.7463 - val_loss: 0.5581
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7785 - loss: 0.4913 - val_accuracy: 0.7537 - val_loss: 0.5551
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4680 - val_accuracy: 0.7836 - val_loss: 0.5353
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7897 - loss: 0.4653 - val_accuracy: 0.5970 - val_loss: 0.7954
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7994 - loss: 0.4736 - val_accuracy: 0.7612 - val_loss: 0.5122
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7945 - loss: 0.4847 - val_accuracy: 0.7537 - val_loss: 0.5188
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.7961 - loss: 0.4823 - val_accuracy: 0.7724 - val_loss: 0.5659
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.8010 - loss: 0.4629 - val_accuracy: 0.7425 - val_loss: 0.5183
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7961 - loss: 0.4794 - val_accuracy: 0.7575 - val_loss: 0.5023
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7865 - loss: 0.4895 - val_accuracy: 0.7612 - val_loss: 0.5140
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7897 - loss: 0.4759 - val_accuracy: 0.7612 - val_loss: 0.5049
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.7817 - loss: 0.4882 - val_accuracy: 0.7351 - val_loss: 0.6216
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.8010 - loss: 0.4698 - val_accuracy: 0.6903 - val_loss: 0.7659
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7913 - loss: 0.4759 - val_accuracy: 0.7687 - val_loss: 0.5132
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7994 - loss: 0.4757 - val_accuracy: 0.7687 - val_loss: 0.5560
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7945 - loss: 0.4705 - val_accuracy: 0.7388 - val_loss: 0.5746
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.8026 - loss: 0.4875 - val_accuracy: 0.7537 - val_loss: 0.5229
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7849 - loss: 0.4685 - val_accuracy: 0.7463 - val_loss: 0.5509
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7978 - loss: 0.4729 - val_accuracy: 0.7313 - val_loss: 0.5783
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.7817 - loss: 0.4730 - val_accuracy: 0.7761 - val_loss: 0.5279
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7994 - loss: 0.4655 - val_accuracy: 0.7425 - val_loss: 0.5455
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7929 - loss: 0.4660 - val_accuracy: 0.7799 - val_loss: 0.5324
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7785 - loss: 0.4776 - val_accuracy: 0.6007 - val_loss: 0.7688
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7817 - loss: 0.4951 - val_accuracy: 0.7761 - val_loss: 0.5301
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7913 - loss: 0.4766 - val_accuracy: 0.7351 - val_loss: 0.5826
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7881 - loss: 0.4747 - val_accuracy: 0.7649 - val_loss: 0.5186
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7913 - loss: 0.4782 - val_accuracy: 0.7537 - val_loss: 0.5183
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7961 - loss: 0.4738 - val_accuracy: 0.7388 - val_loss: 0.5592
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7913 - loss: 0.4631 - val_accuracy: 0.7500 - val_loss: 0.5252
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.8026 - loss: 0.4436 - val_accuracy: 0.7761 - val_loss: 0.5373
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7994 - loss: 0.4785 - val_accuracy: 0.7649 - val_loss: 0.5396
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.8154 - loss: 0.4589 - val_accuracy: 0.7388 - val_loss: 0.5179
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7881 - loss: 0.4648 - val_accuracy: 0.7873 - val_loss: 0.5357
Epoch 153/5000

wandb: Agent Starting Run: 8k7irls9 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3868 - loss: 55.3015 - val_accuracy: 0.3694 - val_loss: 23.5540
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4960 - loss: 7.0344 - val_accuracy: 0.5970 - val_loss: 1.5063
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.6100 - loss: 1.5338 - val_accuracy: 0.6231 - val_loss: 1.2102
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6100 - loss: 1.1913 - val_accuracy: 0.6119 - val_loss: 1.0604
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.9590 - val_accuracy: 0.6306 - val_loss: 0.8962
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.8107 - val_accuracy: 0.6754 - val_loss: 0.7799
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6421 - loss: 0.7469 - val_accuracy: 0.6791 - val_loss: 0.7350
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.6661 - loss: 0.6803 - val_accuracy: 0.6903 - val_loss: 0.6949
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.6485 - val_accuracy: 0.6903 - val_loss: 0.6553
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.6686 - val_accuracy: 0.7052 - val_loss: 0.6312
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.6116 - val_accuracy: 0.6903 - val_loss: 0.5943
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.6405 - val_accuracy: 0.6903 - val_loss: 0.5865
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.5992 - val_accuracy: 0.6493 - val_loss: 0.7188
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - accuracy: 0.7030 - loss: 0.5869 - val_accuracy: 0.6530 - val_loss: 0.6928
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.6806 - loss: 0.6168 - val_accuracy: 0.7127 - val_loss: 0.5562
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.7159 - loss: 0.5589 - val_accuracy: 0.7052 - val_loss: 0.5613
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6517 - loss: 0.6160 - val_accuracy: 0.7239 - val_loss: 0.6215
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.6758 - loss: 0.5960 - val_accuracy: 0.6791 - val_loss: 0.5877
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7143 - loss: 0.5494 - val_accuracy: 0.7351 - val_loss: 0.5533
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.7207 - loss: 0.5456 - val_accuracy: 0.7239 - val_loss: 0.5384
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7255 - loss: 0.5439 - val_accuracy: 0.6903 - val_loss: 0.5563
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7368 - loss: 0.5329 - val_accuracy: 0.7724 - val_loss: 0.5434
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7335 - loss: 0.5302 - val_accuracy: 0.7537 - val_loss: 0.5407
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7464 - loss: 0.5359 - val_accuracy: 0.6754 - val_loss: 0.6147
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7143 - loss: 0.5493 - val_accuracy: 0.7500 - val_loss: 0.5955
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5281 - val_accuracy: 0.7015 - val_loss: 0.5460
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7368 - loss: 0.5540 - val_accuracy: 0.7649 - val_loss: 0.5269
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6918 - loss: 0.5869 - val_accuracy: 0.7164 - val_loss: 0.5506
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7287 - loss: 0.5446 - val_accuracy: 0.7239 - val_loss: 0.5351
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7432 - loss: 0.5701 - val_accuracy: 0.7500 - val_loss: 0.5002
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7239 - loss: 0.5797 - val_accuracy: 0.7425 - val_loss: 0.5910
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7801 - loss: 0.5257 - val_accuracy: 0.7687 - val_loss: 0.5135
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7544 - loss: 0.5506 - val_accuracy: 0.7649 - val_loss: 0.5096
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6870 - loss: 0.6334 - val_accuracy: 0.7127 - val_loss: 0.5742
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7303 - loss: 0.6477 - val_accuracy: 0.5821 - val_loss: 0.7141
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7544 - loss: 0.5308 - val_accuracy: 0.7687 - val_loss: 0.5419
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7753 - loss: 0.4926 - val_accuracy: 0.7313 - val_loss: 0.5148
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.4845 - val_accuracy: 0.7537 - val_loss: 0.5083
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7464 - loss: 0.5197 - val_accuracy: 0.7425 - val_loss: 0.5062
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7817 - loss: 0.4898 - val_accuracy: 0.7425 - val_loss: 0.5016
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7432 - loss: 0.5529 - val_accuracy: 0.7500 - val_loss: 0.4967
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.7416 - loss: 0.5556 - val_accuracy: 0.7687 - val_loss: 0.5712
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.7352 - loss: 0.5512 - val_accuracy: 0.7425 - val_loss: 0.5989
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.7352 - loss: 0.5944 - val_accuracy: 0.7575 - val_loss: 0.5346
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7287 - loss: 0.5936 - val_accuracy: 0.7127 - val_loss: 0.5481
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7737 - loss: 0.5212 - val_accuracy: 0.7463 - val_loss: 0.5016
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7705 - loss: 0.5222 - val_accuracy: 0.7201 - val_loss: 0.5577
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.7769 - loss: 0.4891 - val_accuracy: 0.7500 - val_loss: 0.5044
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.7817 - loss: 0.5031 - val_accuracy: 0.7463 - val_loss: 0.4889
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.7576 - loss: 0.5158 - val_accuracy: 0.7500 - val_loss: 0.4919
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7785 - loss: 0.4923 - val_accuracy: 0.6866 - val_loss: 0.6299
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.7576 - loss: 0.5263 - val_accuracy: 0.7500 - val_loss: 0.5059
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5005 - val_accuracy: 0.7388 - val_loss: 0.4953
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.8010 - loss: 0.4709 - val_accuracy: 0.7649 - val_loss: 0.5429
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7865 - loss: 0.4904 - val_accuracy: 0.7612 - val_loss: 0.5274
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4589 - val_accuracy: 0.7537 - val_loss: 0.5018
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7897 - loss: 0.4633 - val_accuracy: 0.7425 - val_loss: 0.5055
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7865 - loss: 0.4812 - val_accuracy: 0.7425 - val_loss: 0.4902
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.8042 - loss: 0.4624 - val_accuracy: 0.7500 - val_loss: 0.4922
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7689 - loss: 0.5462 - val_accuracy: 0.7687 - val_loss: 0.5536
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7592 - loss: 0.5412 - val_accuracy: 0.5597 - val_loss: 0.8568
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7528 - loss: 0.5595 - val_accuracy: 0.7724 - val_loss: 0.5236
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7849 - loss: 0.4901 - val_accuracy: 0.7649 - val_loss: 0.4916
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7881 - loss: 0.4578 - val_accuracy: 0.7388 - val_loss: 0.6006
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7994 - loss: 0.4729 - val_accuracy: 0.7575 - val_loss: 0.4910
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8074 - loss: 0.4668 - val_accuracy: 0.7761 - val_loss: 0.5350
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7817 - loss: 0.5226 - val_accuracy: 0.7351 - val_loss: 0.5411
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8058 - loss: 0.4741 - val_accuracy: 0.7575 - val_loss: 0.4984
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7994 - loss: 0.4649 - val_accuracy: 0.7612 - val_loss: 0.4974
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7817 - loss: 0.5029 - val_accuracy: 0.7201 - val_loss: 0.6214
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.8090 - loss: 0.4729 - val_accuracy: 0.7724 - val_loss: 0.5361
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7737 - loss: 0.5134 - val_accuracy: 0.7649 - val_loss: 0.4957
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5458 - val_accuracy: 0.7500 - val_loss: 0.5141
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7978 - loss: 0.4594 - val_accuracy: 0.7351 - val_loss: 0.5596
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.8058 - loss: 0.4653 - val_accuracy: 0.7687 - val_loss: 0.5619
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7978 - loss: 0.4673 - val_accuracy: 0.7612 - val_loss: 0.4887
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7721 - loss: 0.5069 - val_accuracy: 0.7313 - val_loss: 0.5608
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.8090 - loss: 0.4611 - val_accuracy: 0.7612 - val_loss: 0.5028
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.8090 - loss: 0.4467 - val_accuracy: 0.7575 - val_loss: 0.5010
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.8074 - loss: 0.4611 - val_accuracy: 0.7500 - val_loss: 0.5052
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7994 - loss: 0.4646 - val_accuracy: 0.7873 - val_loss: 0.5400
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.8074 - loss: 0.4643 - val_accuracy: 0.7127 - val_loss: 0.6354
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8042 - loss: 0.4607 - val_accuracy: 0.7687 - val_loss: 0.4990
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8010 - loss: 0.4827 - val_accuracy: 0.7687 - val_loss: 0.5495
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7881 - loss: 0.4988 - val_accuracy: 0.7239 - val_loss: 0.6268
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7608 - loss: 0.5573 - val_accuracy: 0.7649 - val_loss: 0.5144
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4543 - val_accuracy: 0.7537 - val_loss: 0.4987
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.8042 - loss: 0.4578 - val_accuracy: 0.7724 - val_loss: 0.5405
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5521 - val_accuracy: 0.7799 - val_loss: 0.5135
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7801 - loss: 0.4960 - val_accuracy: 0.7575 - val_loss: 0.5117
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7785 - loss: 0.5042 - val_accuracy: 0.7612 - val_loss: 0.5096
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.8026 - loss: 0.4534 - val_accuracy: 0.7724 - val_loss: 0.5008
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7961 - loss: 0.4772 - val_accuracy: 0.7575 - val_loss: 0.5362
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7849 - loss: 0.4746 - val_accuracy: 0.7724 - val_loss: 0.5016
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7753 - loss: 0.5020 - val_accuracy: 0.7761 - val_loss: 0.5064
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7978 - loss: 0.4896 - val_accuracy: 0.7687 - val_loss: 0.5250
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.8010 - loss: 0.4684 - val_accuracy: 0.7388 - val_loss: 0.5815
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7865 - loss: 0.5223 - val_accuracy: 0.7575 - val_loss: 0.5121
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4867 - val_accuracy: 0.7612 - val_loss: 0.5074
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7913 - loss: 0.4595 - val_accuracy: 0.7799 - val_loss: 0.5724
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7785 - loss: 0.5111 - val_accuracy: 0.7537 - val_loss: 0.5476
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.8010 - loss: 0.4649 - val_accuracy: 0.7239 - val_loss: 0.6549
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8010 - loss: 0.4776 - val_accuracy: 0.7687 - val_loss: 0.5018
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7978 - loss: 0.4549 - val_accuracy: 0.7649 - val_loss: 0.5092
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7769 - loss: 0.4945 - val_accuracy: 0.7724 - val_loss: 0.5055
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7929 - loss: 0.4833 - val_accuracy: 0.5597 - val_loss: 0.9202
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.7737 - loss: 0.5002 - val_accuracy: 0.7612 - val_loss: 0.5191
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.8058 - loss: 0.4819 - val_accuracy: 0.7687 - val_loss: 0.5359
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.8074 - loss: 0.4429 - val_accuracy: 0.7612 - val_loss: 0.5093
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4809 - val_accuracy: 0.7425 - val_loss: 0.5817
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8010 - loss: 0.4515 - val_accuracy: 0.7724 - val_loss: 0.5142
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.8042 - loss: 0.4363 - val_accuracy: 0.7612 - val_loss: 0.5510
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7994 - loss: 0.4473 - val_accuracy: 0.7090 - val_loss: 0.6651
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8106 - loss: 0.4463 - val_accuracy: 0.7649 - val_loss: 0.5262
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7994 - loss: 0.4464 - val_accuracy: 0.7687 - val_loss: 0.5366
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7945 - loss: 0.4967 - val_accuracy: 0.7239 - val_loss: 0.6577
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7833 - loss: 0.5091 - val_accuracy: 0.7836 - val_loss: 0.5932
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8042 - loss: 0.4604 - val_accuracy: 0.7761 - val_loss: 0.5671
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4615 - val_accuracy: 0.7761 - val_loss: 0.6149
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.7961 - loss: 0.4795 - val_accuracy: 0.7463 - val_loss: 0.5997
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7978 - loss: 0.5064 - val_accuracy: 0.7687 - val_loss: 0.5352
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.8074 - loss: 0.4557 - val_accuracy: 0.7127 - val_loss: 0.6907
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7753 - loss: 0.4933 - val_accuracy: 0.7612 - val_loss: 0.5382
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7849 - loss: 0.4842 - val_accuracy: 0.7687 - val_loss: 0.5274
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.8058 - loss: 0.4469 - val_accuracy: 0.7687 - val_loss: 0.5404
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.8138 - loss: 0.4731 - val_accuracy: 0.7873 - val_loss: 0.5745
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7978 - loss: 0.4586 - val_accuracy: 0.7575 - val_loss: 0.5753
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7897 - loss: 0.4638 - val_accuracy: 0.7612 - val_loss: 0.5887
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4732 - val_accuracy: 0.7724 - val_loss: 0.5227
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.8122 - loss: 0.4499 - val_accuracy: 0.7425 - val_loss: 0.6044
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7913 - loss: 0.4463 - val_accuracy: 0.7351 - val_loss: 0.6557
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7929 - loss: 0.5175 - val_accuracy: 0.7724 - val_loss: 0.5348
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8058 - loss: 0.4464 - val_accuracy: 0.6866 - val_loss: 0.7071
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.8026 - loss: 0.4622 - val_accuracy: 0.7761 - val_loss: 0.5294
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.8010 - loss: 0.4471 - val_accuracy: 0.7649 - val_loss: 0.5716
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.8026 - loss: 0.4431 - val_accuracy: 0.7761 - val_loss: 0.5325
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.8010 - loss: 0.4608 - val_accuracy: 0.7351 - val_loss: 0.6265
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4662 - val_accuracy: 0.7799 - val_loss: 0.5306
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7769 - loss: 0.4820 - val_accuracy: 0.7724 - val_loss: 0.5380
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7865 - loss: 0.4706 - val_accuracy: 0.7164 - val_loss: 0.6949
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7929 - loss: 0.4543 - val_accuracy: 0.7799 - val_loss: 0.6334
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.8106 - loss: 0.4490 - val_accuracy: 0.7761 - val_loss: 0.6355
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7929 - loss: 0.4967 - val_accuracy: 0.7649 - val_loss: 0.5351
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7881 - loss: 0.5348 - val_accuracy: 0.5299 - val_loss: 1.0427
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7673 - loss: 0.5395 - val_accuracy: 0.7201 - val_loss: 0.7733
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7897 - loss: 0.5134 - val_accuracy: 0.7799 - val_loss: 0.5389
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7961 - loss: 0.4669 - val_accuracy: 0.7799 - val_loss: 0.5830
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4375 - val_accuracy: 0.7724 - val_loss: 0.5471
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.8010 - loss: 0.4579 - val_accuracy: 0.7799 - val_loss: 0.6248
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7961 - loss: 0.4727 - val_accuracy: 0.7687 - val_loss: 0.5580
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7801 - loss: 0.4871 - val_accuracy: 0.7425 - val_loss: 0.6639
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.8058 - loss: 0.4387 - val_accuracy: 0.7388 - val_loss: 0.6472
Epoch 153/5000

wandb: Agent Starting Run: 20s4iti8 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5875 - loss: 1.8617 - val_accuracy: 0.6269 - val_loss: 0.6863
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6944 - val_accuracy: 0.6306 - val_loss: 0.6820
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - accuracy: 0.6116 - loss: 0.6840 - val_accuracy: 0.6306 - val_loss: 0.6790
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6116 - loss: 0.6809 - val_accuracy: 0.6306 - val_loss: 0.6759
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.6116 - loss: 0.6787 - val_accuracy: 0.6306 - val_loss: 0.6734
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.6116 - loss: 0.6767 - val_accuracy: 0.6306 - val_loss: 0.6712
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.6116 - loss: 0.6752 - val_accuracy: 0.6306 - val_loss: 0.6695
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.6116 - loss: 0.6739 - val_accuracy: 0.6306 - val_loss: 0.6681
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.6116 - loss: 0.6728 - val_accuracy: 0.6306 - val_loss: 0.6668
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6116 - loss: 0.6719 - val_accuracy: 0.6306 - val_loss: 0.6657
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.6116 - loss: 0.6711 - val_accuracy: 0.6306 - val_loss: 0.6648
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - accuracy: 0.6116 - loss: 0.6705 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6700 - val_accuracy: 0.6306 - val_loss: 0.6634
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6696 - val_accuracy: 0.6306 - val_loss: 0.6628
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.6116 - loss: 0.6692 - val_accuracy: 0.6306 - val_loss: 0.6625
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6690 - val_accuracy: 0.6306 - val_loss: 0.6620
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.6132 - loss: 0.6687 - val_accuracy: 0.6306 - val_loss: 0.6616
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6306 - val_loss: 0.6615
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6132 - loss: 0.6684 - val_accuracy: 0.6306 - val_loss: 0.6611
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6132 - loss: 0.6681 - val_accuracy: 0.6306 - val_loss: 0.6608
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6132 - loss: 0.6682 - val_accuracy: 0.6306 - val_loss: 0.6607
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6132 - loss: 0.6677 - val_accuracy: 0.6306 - val_loss: 0.6607
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6132 - loss: 0.6678 - val_accuracy: 0.6306 - val_loss: 0.6604
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.6132 - loss: 0.6676 - val_accuracy: 0.6306 - val_loss: 0.6602
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6132 - loss: 0.6673 - val_accuracy: 0.6306 - val_loss: 0.6603
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.6132 - loss: 0.6676 - val_accuracy: 0.6306 - val_loss: 0.6600
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.6132 - loss: 0.6675 - val_accuracy: 0.6306 - val_loss: 0.6601
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6132 - loss: 0.6674 - val_accuracy: 0.6306 - val_loss: 0.6600
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.6132 - loss: 0.6674 - val_accuracy: 0.6306 - val_loss: 0.6600
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6673 - val_accuracy: 0.6306 - val_loss: 0.6598
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6132 - loss: 0.6673 - val_accuracy: 0.6306 - val_loss: 0.6599
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6132 - loss: 0.6672 - val_accuracy: 0.6306 - val_loss: 0.6597
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6132 - loss: 0.6672 - val_accuracy: 0.6306 - val_loss: 0.6598
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6132 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6598
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6132 - loss: 0.6671 - val_accuracy: 0.6306 - val_loss: 0.6597
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6132 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6148 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6132 - loss: 0.6671 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6132 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6596
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6132 - loss: 0.6671 - val_accuracy: 0.6306 - val_loss: 0.6596
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6132 - loss: 0.6671 - val_accuracy: 0.6306 - val_loss: 0.6596
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6148 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6132 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6132 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6132 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6597
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6132 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.6132 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6132 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6598
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6148 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6132 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6148 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6148 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6148 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6148 - loss: 0.6668 - val_accuracy: 0.6269 - val_loss: 0.6595
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6148 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6597
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6596
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6132 - loss: 0.6661 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6593
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 153/5000

wandb: Agent Starting Run: r2wk6t7n with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 3.3351 - val_accuracy: 0.6940 - val_loss: 1.9740
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 2.0717 - val_accuracy: 0.6642 - val_loss: 1.6835
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.6276 - loss: 1.8646 - val_accuracy: 0.7015 - val_loss: 1.3588
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6661 - loss: 1.4398 - val_accuracy: 0.6716 - val_loss: 1.1964
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.6388 - loss: 1.3648 - val_accuracy: 0.5299 - val_loss: 1.6918
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.6613 - loss: 1.1317 - val_accuracy: 0.6642 - val_loss: 0.9294
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.6356 - loss: 1.2055 - val_accuracy: 0.6642 - val_loss: 0.9831
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6597 - loss: 0.9869 - val_accuracy: 0.5448 - val_loss: 1.2124
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6629 - loss: 1.0329 - val_accuracy: 0.4851 - val_loss: 1.4592
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6501 - loss: 0.9467 - val_accuracy: 0.6903 - val_loss: 0.7967
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.6453 - loss: 0.9952 - val_accuracy: 0.6530 - val_loss: 1.2607
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6244 - loss: 1.0526 - val_accuracy: 0.7201 - val_loss: 0.6329
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.6870 - loss: 0.8032 - val_accuracy: 0.6754 - val_loss: 0.9689
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6774 - loss: 0.8589 - val_accuracy: 0.6791 - val_loss: 0.9111
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6597 - loss: 0.8750 - val_accuracy: 0.6903 - val_loss: 0.9290
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.6950 - loss: 0.7990 - val_accuracy: 0.7090 - val_loss: 0.6103
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6790 - loss: 0.8284 - val_accuracy: 0.6567 - val_loss: 1.4008
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7014 - loss: 0.7744 - val_accuracy: 0.7463 - val_loss: 0.5718
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.6870 - loss: 0.8088 - val_accuracy: 0.7575 - val_loss: 0.5634
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.6838 - loss: 0.7987 - val_accuracy: 0.6791 - val_loss: 0.9202
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.7345 - val_accuracy: 0.7687 - val_loss: 0.5524
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.7860 - val_accuracy: 0.7537 - val_loss: 0.5442
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.6822 - loss: 0.8623 - val_accuracy: 0.7015 - val_loss: 0.7174
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.7030 - loss: 0.8601 - val_accuracy: 0.7687 - val_loss: 0.5296
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7271 - loss: 0.7349 - val_accuracy: 0.7463 - val_loss: 0.5252
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7095 - loss: 0.7643 - val_accuracy: 0.6455 - val_loss: 0.7410
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7111 - loss: 0.7529 - val_accuracy: 0.6455 - val_loss: 1.6452
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7095 - loss: 0.7646 - val_accuracy: 0.7575 - val_loss: 0.5162
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - accuracy: 0.7159 - loss: 0.7860 - val_accuracy: 0.7799 - val_loss: 0.5170
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7095 - loss: 0.7127 - val_accuracy: 0.4888 - val_loss: 1.1992
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6918 - loss: 0.7586 - val_accuracy: 0.7612 - val_loss: 0.5218
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7416 - loss: 0.6950 - val_accuracy: 0.7090 - val_loss: 0.6490
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7223 - loss: 0.7567 - val_accuracy: 0.7575 - val_loss: 0.5210
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 0.7175 - loss: 0.7447 - val_accuracy: 0.7015 - val_loss: 0.7458
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.7223 - loss: 0.7452 - val_accuracy: 0.7910 - val_loss: 0.6229
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7319 - loss: 0.7024 - val_accuracy: 0.7201 - val_loss: 0.6405
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.7223 - loss: 0.7325 - val_accuracy: 0.6791 - val_loss: 0.8649
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7143 - loss: 0.7409 - val_accuracy: 0.7761 - val_loss: 0.5313
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7239 - loss: 0.7630 - val_accuracy: 0.7761 - val_loss: 0.5722
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.7368 - loss: 0.6872 - val_accuracy: 0.7388 - val_loss: 0.5685
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.7640 - loss: 0.6217 - val_accuracy: 0.6828 - val_loss: 0.9045
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7175 - loss: 0.7153 - val_accuracy: 0.7313 - val_loss: 0.6035
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7480 - loss: 0.6374 - val_accuracy: 0.6343 - val_loss: 0.7824
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7496 - loss: 0.7180 - val_accuracy: 0.7724 - val_loss: 0.5638
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7368 - loss: 0.7070 - val_accuracy: 0.7687 - val_loss: 0.5466
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.7432 - loss: 0.6623 - val_accuracy: 0.7425 - val_loss: 0.6888
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7384 - loss: 0.6679 - val_accuracy: 0.7239 - val_loss: 0.6497
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7239 - loss: 0.6756 - val_accuracy: 0.7239 - val_loss: 0.6507
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.7303 - loss: 0.6982 - val_accuracy: 0.5634 - val_loss: 0.9194
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7287 - loss: 0.7364 - val_accuracy: 0.7575 - val_loss: 0.5586
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.7480 - loss: 0.6631 - val_accuracy: 0.6642 - val_loss: 1.3366
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.7496 - loss: 0.6784 - val_accuracy: 0.7575 - val_loss: 0.5627
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7560 - loss: 0.6251 - val_accuracy: 0.7687 - val_loss: 0.6054
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.7432 - loss: 0.7105 - val_accuracy: 0.7537 - val_loss: 0.5687
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7496 - loss: 0.6922 - val_accuracy: 0.7612 - val_loss: 0.5593
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.7368 - loss: 0.7296 - val_accuracy: 0.7612 - val_loss: 0.5578
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7512 - loss: 0.7178 - val_accuracy: 0.7537 - val_loss: 0.5778
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7448 - loss: 0.6592 - val_accuracy: 0.6791 - val_loss: 1.0074
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.7480 - loss: 0.6914 - val_accuracy: 0.7575 - val_loss: 0.5695
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.7432 - loss: 0.6945 - val_accuracy: 0.7724 - val_loss: 0.6113
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7657 - loss: 0.6452 - val_accuracy: 0.7500 - val_loss: 0.7249
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.7576 - loss: 0.6355 - val_accuracy: 0.5448 - val_loss: 1.0590
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.7464 - loss: 0.6532 - val_accuracy: 0.6754 - val_loss: 0.9602
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.7416 - loss: 0.6804 - val_accuracy: 0.7052 - val_loss: 0.7634
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.7223 - loss: 0.7300 - val_accuracy: 0.7575 - val_loss: 0.5992
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7640 - loss: 0.6374 - val_accuracy: 0.6642 - val_loss: 1.2950
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7448 - loss: 0.6959 - val_accuracy: 0.7575 - val_loss: 0.6063
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7560 - loss: 0.6866 - val_accuracy: 0.7761 - val_loss: 0.7093
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7673 - loss: 0.6289 - val_accuracy: 0.7164 - val_loss: 0.7221
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7576 - loss: 0.6551 - val_accuracy: 0.7649 - val_loss: 0.6040
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7528 - loss: 0.6367 - val_accuracy: 0.7313 - val_loss: 0.7561
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7640 - loss: 0.6426 - val_accuracy: 0.7351 - val_loss: 0.6678
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7592 - loss: 0.6379 - val_accuracy: 0.6828 - val_loss: 0.8303
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 0.7319 - loss: 0.6822 - val_accuracy: 0.7575 - val_loss: 0.6182
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7737 - loss: 0.6187 - val_accuracy: 0.5821 - val_loss: 0.9672
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.7592 - loss: 0.6408 - val_accuracy: 0.6679 - val_loss: 1.0849
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.7416 - loss: 0.6579 - val_accuracy: 0.6455 - val_loss: 1.4637
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7384 - loss: 0.6952 - val_accuracy: 0.7612 - val_loss: 0.6281
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7640 - loss: 0.6333 - val_accuracy: 0.7612 - val_loss: 0.6020
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7689 - loss: 0.6257 - val_accuracy: 0.5261 - val_loss: 1.1585
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7255 - loss: 0.6903 - val_accuracy: 0.7649 - val_loss: 0.6321
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7769 - loss: 0.5904 - val_accuracy: 0.4590 - val_loss: 2.0078
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7657 - loss: 0.6488 - val_accuracy: 0.7351 - val_loss: 0.6906
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7512 - loss: 0.6657 - val_accuracy: 0.7575 - val_loss: 0.6109
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7592 - loss: 0.5991 - val_accuracy: 0.7799 - val_loss: 0.6866
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7271 - loss: 0.6927 - val_accuracy: 0.7537 - val_loss: 0.6284
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.7480 - loss: 0.6650 - val_accuracy: 0.7500 - val_loss: 0.6739
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7319 - loss: 0.6510 - val_accuracy: 0.7090 - val_loss: 0.8127
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7737 - loss: 0.6355 - val_accuracy: 0.6978 - val_loss: 0.8684
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.7416 - loss: 0.6758 - val_accuracy: 0.7575 - val_loss: 0.6482
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7544 - loss: 0.6127 - val_accuracy: 0.7351 - val_loss: 0.7768
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.7560 - loss: 0.6953 - val_accuracy: 0.6642 - val_loss: 1.1037
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7657 - loss: 0.6363 - val_accuracy: 0.6418 - val_loss: 0.8951
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7833 - loss: 0.5821 - val_accuracy: 0.7015 - val_loss: 0.8051
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7512 - loss: 0.6472 - val_accuracy: 0.5784 - val_loss: 1.0126
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.7384 - loss: 0.6444 - val_accuracy: 0.7425 - val_loss: 0.7880
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7721 - loss: 0.6158 - val_accuracy: 0.6716 - val_loss: 1.2268
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7512 - loss: 0.6511 - val_accuracy: 0.7463 - val_loss: 0.6388
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.7673 - loss: 0.6077 - val_accuracy: 0.6940 - val_loss: 0.8941
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7705 - loss: 0.6196 - val_accuracy: 0.7388 - val_loss: 0.7973
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.7865 - loss: 0.6169 - val_accuracy: 0.7799 - val_loss: 0.7087
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7785 - loss: 0.6268 - val_accuracy: 0.7612 - val_loss: 0.6465
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7624 - loss: 0.5931 - val_accuracy: 0.7537 - val_loss: 0.6284
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.7737 - loss: 0.6137 - val_accuracy: 0.7612 - val_loss: 0.6325
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.7560 - loss: 0.5942 - val_accuracy: 0.6978 - val_loss: 0.8859
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.7432 - loss: 0.6703 - val_accuracy: 0.7425 - val_loss: 0.7252
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7769 - loss: 0.5783 - val_accuracy: 0.7015 - val_loss: 0.9648
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7528 - loss: 0.6202 - val_accuracy: 0.7537 - val_loss: 0.6277
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - accuracy: 0.7817 - loss: 0.6482 - val_accuracy: 0.7724 - val_loss: 0.7375
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 0.7833 - loss: 0.5660 - val_accuracy: 0.6978 - val_loss: 0.8301
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7673 - loss: 0.6209 - val_accuracy: 0.7537 - val_loss: 0.6697
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7833 - loss: 0.5695 - val_accuracy: 0.6903 - val_loss: 0.9374
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.7544 - loss: 0.6462 - val_accuracy: 0.7015 - val_loss: 0.8807
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7528 - loss: 0.5925 - val_accuracy: 0.7612 - val_loss: 0.6528
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7721 - loss: 0.5938 - val_accuracy: 0.7836 - val_loss: 0.7447
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7528 - loss: 0.6326 - val_accuracy: 0.7612 - val_loss: 0.6440
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7737 - loss: 0.6125 - val_accuracy: 0.7537 - val_loss: 0.6417
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7721 - loss: 0.5929 - val_accuracy: 0.6978 - val_loss: 0.8503
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7897 - loss: 0.4869 - val_accuracy: 0.6754 - val_loss: 1.1324
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.7640 - loss: 0.6281 - val_accuracy: 0.7575 - val_loss: 0.6480
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7560 - loss: 0.5783 - val_accuracy: 0.7052 - val_loss: 0.8685
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7624 - loss: 0.6339 - val_accuracy: 0.7500 - val_loss: 0.7275
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7817 - loss: 0.5944 - val_accuracy: 0.7388 - val_loss: 0.7322
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7560 - loss: 0.6116 - val_accuracy: 0.7052 - val_loss: 1.0325
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7737 - loss: 0.5833 - val_accuracy: 0.5672 - val_loss: 1.0589
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7384 - loss: 0.6743 - val_accuracy: 0.6978 - val_loss: 0.8564
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7801 - loss: 0.5576 - val_accuracy: 0.7575 - val_loss: 0.6536
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7689 - loss: 0.5923 - val_accuracy: 0.7575 - val_loss: 0.6574
Epoch 128: early stopping

wandb: Agent Starting Run: 2mtg89fw with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4029 - loss: 20.8457 - val_accuracy: 0.5336 - val_loss: 2.4672
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4687 - loss: 1.6001 - val_accuracy: 0.4403 - val_loss: 1.4247
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.4462 - loss: 1.0960 - val_accuracy: 0.4851 - val_loss: 1.0663
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.5169 - loss: 0.9011 - val_accuracy: 0.5448 - val_loss: 0.8726
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.5891 - loss: 0.7413 - val_accuracy: 0.5634 - val_loss: 0.7674
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6372 - loss: 0.6799 - val_accuracy: 0.6604 - val_loss: 0.7015
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.6645 - loss: 0.6541 - val_accuracy: 0.7164 - val_loss: 0.6646
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6902 - loss: 0.6301 - val_accuracy: 0.7052 - val_loss: 0.6422
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6934 - loss: 0.6013 - val_accuracy: 0.6903 - val_loss: 0.6314
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.6758 - loss: 0.6071 - val_accuracy: 0.6940 - val_loss: 0.6233
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.7030 - loss: 0.5911 - val_accuracy: 0.7127 - val_loss: 0.6174
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6966 - loss: 0.6005 - val_accuracy: 0.7052 - val_loss: 0.6118
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7143 - loss: 0.5691 - val_accuracy: 0.7313 - val_loss: 0.6057
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7143 - loss: 0.5833 - val_accuracy: 0.6978 - val_loss: 0.6282
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.7143 - loss: 0.5736 - val_accuracy: 0.7537 - val_loss: 0.6161
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6998 - loss: 0.5639 - val_accuracy: 0.7687 - val_loss: 0.6245
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6934 - loss: 0.6265 - val_accuracy: 0.7351 - val_loss: 0.5915
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7255 - loss: 0.5599 - val_accuracy: 0.7239 - val_loss: 0.5805
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6966 - loss: 0.5694 - val_accuracy: 0.7351 - val_loss: 0.5740
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.6886 - loss: 0.6170 - val_accuracy: 0.7313 - val_loss: 0.5687
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7544 - loss: 0.5386 - val_accuracy: 0.7313 - val_loss: 0.5636
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7143 - loss: 0.5531 - val_accuracy: 0.7164 - val_loss: 0.5650
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7271 - loss: 0.5498 - val_accuracy: 0.7463 - val_loss: 0.5437
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7528 - loss: 0.5255 - val_accuracy: 0.7090 - val_loss: 0.5675
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7127 - loss: 0.5592 - val_accuracy: 0.6493 - val_loss: 0.6781
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.7271 - loss: 0.5393 - val_accuracy: 0.7425 - val_loss: 0.5414
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7448 - loss: 0.5188 - val_accuracy: 0.7537 - val_loss: 0.5473
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7608 - loss: 0.4991 - val_accuracy: 0.7575 - val_loss: 0.5428
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7640 - loss: 0.5147 - val_accuracy: 0.7687 - val_loss: 0.5655
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.7657 - loss: 0.5118 - val_accuracy: 0.7463 - val_loss: 0.5351
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7624 - loss: 0.5160 - val_accuracy: 0.7276 - val_loss: 0.5576
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.7673 - loss: 0.4894 - val_accuracy: 0.7761 - val_loss: 0.5607
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7400 - loss: 0.5398 - val_accuracy: 0.7015 - val_loss: 0.6308
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7608 - loss: 0.5180 - val_accuracy: 0.7388 - val_loss: 0.5349
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7753 - loss: 0.4827 - val_accuracy: 0.7388 - val_loss: 0.5336
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7833 - loss: 0.4888 - val_accuracy: 0.7015 - val_loss: 0.6334
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.7624 - loss: 0.5126 - val_accuracy: 0.7761 - val_loss: 0.5559
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7673 - loss: 0.5082 - val_accuracy: 0.7500 - val_loss: 0.5373
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.7512 - loss: 0.5264 - val_accuracy: 0.7575 - val_loss: 0.5341
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7769 - loss: 0.4807 - val_accuracy: 0.7836 - val_loss: 0.5593
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7849 - loss: 0.4937 - val_accuracy: 0.7799 - val_loss: 0.5848
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7801 - loss: 0.4777 - val_accuracy: 0.7201 - val_loss: 0.6035
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.7608 - loss: 0.5054 - val_accuracy: 0.7761 - val_loss: 0.6012
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.7849 - loss: 0.4723 - val_accuracy: 0.7687 - val_loss: 0.5384
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.8074 - loss: 0.4639 - val_accuracy: 0.7239 - val_loss: 0.5899
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7849 - loss: 0.4700 - val_accuracy: 0.7425 - val_loss: 0.5526
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.7769 - loss: 0.4948 - val_accuracy: 0.7724 - val_loss: 0.5255
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7849 - loss: 0.4833 - val_accuracy: 0.7687 - val_loss: 0.5255
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 0.8010 - loss: 0.4623 - val_accuracy: 0.7687 - val_loss: 0.5487
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.7801 - loss: 0.4887 - val_accuracy: 0.7537 - val_loss: 0.5441
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7881 - loss: 0.5091 - val_accuracy: 0.7388 - val_loss: 0.5952
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7785 - loss: 0.4931 - val_accuracy: 0.7500 - val_loss: 0.5222
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7961 - loss: 0.4613 - val_accuracy: 0.7313 - val_loss: 0.5620
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7785 - loss: 0.4853 - val_accuracy: 0.7313 - val_loss: 0.6222
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7528 - loss: 0.5339 - val_accuracy: 0.7649 - val_loss: 0.5117
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.8010 - loss: 0.4723 - val_accuracy: 0.7612 - val_loss: 0.5492
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7801 - loss: 0.4923 - val_accuracy: 0.7612 - val_loss: 0.6040
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.8042 - loss: 0.4576 - val_accuracy: 0.7612 - val_loss: 0.5298
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.8058 - loss: 0.4564 - val_accuracy: 0.7649 - val_loss: 0.5301
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7929 - loss: 0.4662 - val_accuracy: 0.7687 - val_loss: 0.5172
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8090 - loss: 0.4535 - val_accuracy: 0.7687 - val_loss: 0.5475
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7833 - loss: 0.4970 - val_accuracy: 0.7500 - val_loss: 0.5215
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7994 - loss: 0.4639 - val_accuracy: 0.7612 - val_loss: 0.5130
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.8074 - loss: 0.4754 - val_accuracy: 0.7687 - val_loss: 0.5416
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8058 - loss: 0.4551 - val_accuracy: 0.7724 - val_loss: 0.5103
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7929 - loss: 0.4686 - val_accuracy: 0.7500 - val_loss: 0.5720
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7785 - loss: 0.4900 - val_accuracy: 0.7799 - val_loss: 0.5620
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.8026 - loss: 0.4537 - val_accuracy: 0.7649 - val_loss: 0.5196
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7994 - loss: 0.4713 - val_accuracy: 0.7687 - val_loss: 0.5312
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7881 - loss: 0.4985 - val_accuracy: 0.7463 - val_loss: 0.6174
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.8090 - loss: 0.4553 - val_accuracy: 0.7724 - val_loss: 0.5243
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.8026 - loss: 0.4625 - val_accuracy: 0.7537 - val_loss: 0.5478
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.8058 - loss: 0.4434 - val_accuracy: 0.7724 - val_loss: 0.5245
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.8058 - loss: 0.4535 - val_accuracy: 0.7649 - val_loss: 0.5224
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.8042 - loss: 0.4546 - val_accuracy: 0.7687 - val_loss: 0.5210
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.8138 - loss: 0.4408 - val_accuracy: 0.7687 - val_loss: 0.5393
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.8026 - loss: 0.4496 - val_accuracy: 0.7612 - val_loss: 0.5514
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7994 - loss: 0.4550 - val_accuracy: 0.7612 - val_loss: 0.5200
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4620 - val_accuracy: 0.7724 - val_loss: 0.5171
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7978 - loss: 0.4410 - val_accuracy: 0.7612 - val_loss: 0.5191
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.8042 - loss: 0.4470 - val_accuracy: 0.7724 - val_loss: 0.5622
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.7897 - loss: 0.4637 - val_accuracy: 0.7799 - val_loss: 0.5369
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.8010 - loss: 0.4491 - val_accuracy: 0.7724 - val_loss: 0.5329
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7945 - loss: 0.4936 - val_accuracy: 0.7612 - val_loss: 0.5160
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7705 - loss: 0.5041 - val_accuracy: 0.7724 - val_loss: 0.5149
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7945 - loss: 0.4566 - val_accuracy: 0.7724 - val_loss: 0.5299
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.8090 - loss: 0.4478 - val_accuracy: 0.7612 - val_loss: 0.5421
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7994 - loss: 0.4613 - val_accuracy: 0.7761 - val_loss: 0.5302
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7994 - loss: 0.4533 - val_accuracy: 0.7687 - val_loss: 0.5070
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.8058 - loss: 0.4485 - val_accuracy: 0.7724 - val_loss: 0.5290
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7737 - loss: 0.5166 - val_accuracy: 0.7799 - val_loss: 0.6099
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7945 - loss: 0.4664 - val_accuracy: 0.7649 - val_loss: 0.5184
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.8074 - loss: 0.4428 - val_accuracy: 0.7313 - val_loss: 0.6453
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7994 - loss: 0.4538 - val_accuracy: 0.7724 - val_loss: 0.5275
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.8026 - loss: 0.4489 - val_accuracy: 0.7724 - val_loss: 0.5311
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7994 - loss: 0.4622 - val_accuracy: 0.7724 - val_loss: 0.5161
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.8058 - loss: 0.4526 - val_accuracy: 0.7649 - val_loss: 0.5084
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7945 - loss: 0.4458 - val_accuracy: 0.7761 - val_loss: 0.5297
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.8026 - loss: 0.4425 - val_accuracy: 0.7687 - val_loss: 0.5147
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.8058 - loss: 0.4543 - val_accuracy: 0.7687 - val_loss: 0.5350
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.8058 - loss: 0.4466 - val_accuracy: 0.7687 - val_loss: 0.5175
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7881 - loss: 0.4597 - val_accuracy: 0.7313 - val_loss: 0.6434
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7769 - loss: 0.4909 - val_accuracy: 0.7761 - val_loss: 0.5137
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.8026 - loss: 0.4640 - val_accuracy: 0.7799 - val_loss: 0.5607
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.8074 - loss: 0.4585 - val_accuracy: 0.7687 - val_loss: 0.5181
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.8058 - loss: 0.4420 - val_accuracy: 0.7724 - val_loss: 0.5119
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7929 - loss: 0.4652 - val_accuracy: 0.7649 - val_loss: 0.5158
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.7897 - loss: 0.4702 - val_accuracy: 0.7537 - val_loss: 0.6210
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.8042 - loss: 0.4586 - val_accuracy: 0.7836 - val_loss: 0.5280
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.8026 - loss: 0.4624 - val_accuracy: 0.7724 - val_loss: 0.5052
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.8010 - loss: 0.4703 - val_accuracy: 0.7799 - val_loss: 0.5412
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.8026 - loss: 0.4541 - val_accuracy: 0.7724 - val_loss: 0.5296
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7913 - loss: 0.4669 - val_accuracy: 0.7799 - val_loss: 0.5639
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.8058 - loss: 0.4370 - val_accuracy: 0.7724 - val_loss: 0.5217
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7978 - loss: 0.4459 - val_accuracy: 0.7761 - val_loss: 0.5260
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.8042 - loss: 0.4596 - val_accuracy: 0.7687 - val_loss: 0.5219
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.8074 - loss: 0.4531 - val_accuracy: 0.7687 - val_loss: 0.5159
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.8010 - loss: 0.4449 - val_accuracy: 0.7612 - val_loss: 0.5289
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.8122 - loss: 0.4396 - val_accuracy: 0.7388 - val_loss: 0.6553
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7961 - loss: 0.4611 - val_accuracy: 0.7687 - val_loss: 0.5133
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7929 - loss: 0.4551 - val_accuracy: 0.7649 - val_loss: 0.5306
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7994 - loss: 0.4518 - val_accuracy: 0.7724 - val_loss: 0.5189
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7833 - loss: 0.4750 - val_accuracy: 0.7761 - val_loss: 0.5213
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.8026 - loss: 0.4504 - val_accuracy: 0.7761 - val_loss: 0.5250
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7945 - loss: 0.4734 - val_accuracy: 0.7836 - val_loss: 0.5201
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.8090 - loss: 0.4437 - val_accuracy: 0.7500 - val_loss: 0.5717
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.7865 - loss: 0.4748 - val_accuracy: 0.7687 - val_loss: 0.5286
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.8058 - loss: 0.4486 - val_accuracy: 0.7687 - val_loss: 0.5371
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.8138 - loss: 0.4639 - val_accuracy: 0.7649 - val_loss: 0.5085
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.8042 - loss: 0.4516 - val_accuracy: 0.7761 - val_loss: 0.5167
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7945 - loss: 0.4474 - val_accuracy: 0.7799 - val_loss: 0.5308
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7961 - loss: 0.4538 - val_accuracy: 0.7761 - val_loss: 0.5547
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7994 - loss: 0.4375 - val_accuracy: 0.7873 - val_loss: 0.5393
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8122 - loss: 0.4563 - val_accuracy: 0.7687 - val_loss: 0.5228
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.8106 - loss: 0.4497 - val_accuracy: 0.7649 - val_loss: 0.5307
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.8058 - loss: 0.4552 - val_accuracy: 0.7836 - val_loss: 0.5658
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.7945 - loss: 0.4575 - val_accuracy: 0.7649 - val_loss: 0.5285
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7673 - loss: 0.5530 - val_accuracy: 0.7687 - val_loss: 0.5500
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7239 - loss: 0.5746 - val_accuracy: 0.7799 - val_loss: 0.6147
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7945 - loss: 0.4964 - val_accuracy: 0.7612 - val_loss: 0.5722
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7994 - loss: 0.4370 - val_accuracy: 0.7463 - val_loss: 0.5739
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7865 - loss: 0.4770 - val_accuracy: 0.7687 - val_loss: 0.5261
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.8026 - loss: 0.4485 - val_accuracy: 0.7649 - val_loss: 0.5333
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8058 - loss: 0.4577 - val_accuracy: 0.7799 - val_loss: 0.5389
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.8090 - loss: 0.4532 - val_accuracy: 0.7724 - val_loss: 0.5280
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7994 - loss: 0.4633 - val_accuracy: 0.7761 - val_loss: 0.5559
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7929 - loss: 0.4737 - val_accuracy: 0.7649 - val_loss: 0.5174
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.8010 - loss: 0.4443 - val_accuracy: 0.7612 - val_loss: 0.5318
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.8170 - loss: 0.4476 - val_accuracy: 0.7761 - val_loss: 0.5341
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.8170 - loss: 0.4328 - val_accuracy: 0.7575 - val_loss: 0.5295
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.8058 - loss: 0.4525 - val_accuracy: 0.7761 - val_loss: 0.5307
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.8058 - loss: 0.4336 - val_accuracy: 0.7649 - val_loss: 0.5252
Epoch 153/5000

wandb: Agent Starting Run: goarakq9 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5987 - loss: 3.1459 - val_accuracy: 0.6269 - val_loss: 0.7666
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.6100 - loss: 0.6970 - val_accuracy: 0.6306 - val_loss: 0.7193
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6116 - loss: 0.6828 - val_accuracy: 0.6306 - val_loss: 0.7147
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6148 - loss: 0.6796 - val_accuracy: 0.6306 - val_loss: 0.7109
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6148 - loss: 0.6770 - val_accuracy: 0.6269 - val_loss: 0.7078
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6148 - loss: 0.6750 - val_accuracy: 0.6269 - val_loss: 0.7052
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6164 - loss: 0.6734 - val_accuracy: 0.6269 - val_loss: 0.7026
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.6148 - loss: 0.6718 - val_accuracy: 0.6269 - val_loss: 0.7005
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6148 - loss: 0.6706 - val_accuracy: 0.6306 - val_loss: 0.6984
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6148 - loss: 0.6698 - val_accuracy: 0.6306 - val_loss: 0.6972
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.6148 - loss: 0.6689 - val_accuracy: 0.6306 - val_loss: 0.6966
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.6148 - loss: 0.6684 - val_accuracy: 0.6306 - val_loss: 0.6957
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.6132 - loss: 0.6678 - val_accuracy: 0.6306 - val_loss: 0.6953
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.6148 - loss: 0.6674 - val_accuracy: 0.6306 - val_loss: 0.6948
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6148 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6940
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6937
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6937
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6933
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6924
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6923
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6148 - loss: 0.6656 - val_accuracy: 0.6269 - val_loss: 0.6922
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6148 - loss: 0.6656 - val_accuracy: 0.6269 - val_loss: 0.6919
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6269 - val_loss: 0.6917
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6306 - val_loss: 0.6914
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.6148 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.6911
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6148 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.6913
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.6148 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6911
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step - accuracy: 0.6148 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.6912
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.6148 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.6909
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6908
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6148 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6906
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6906
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.6906
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.6908
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.6132 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6906
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 786us/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6906
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6908
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.6908
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 783us/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.6905
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6909
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.6909
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.6132 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6907
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6907
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6231 - val_loss: 0.6979
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6231 - val_loss: 0.6990
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6231 - val_loss: 0.7021
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.6180 - loss: 0.6649 - val_accuracy: 0.6231 - val_loss: 0.6978
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.6929
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.6926
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6132 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.6923
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.6919
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - accuracy: 0.6132 - loss: 0.6649 - val_accuracy: 0.6231 - val_loss: 0.6939
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6937
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.6868
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6231 - val_loss: 0.6899
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6231 - val_loss: 0.6913
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.6212 - loss: 0.6967 - val_accuracy: 0.6269 - val_loss: 0.6955
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.6132 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6945
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 0.6132 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.6940
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.6132 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6936
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.6148 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6932
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6924
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6306 - val_loss: 0.6921
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 786us/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6306 - val_loss: 0.6919
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.6164 - loss: 0.6654 - val_accuracy: 0.6306 - val_loss: 0.6916
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 774us/step - accuracy: 0.6164 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6920
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - accuracy: 0.6164 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.6923
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6164 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6923
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6164 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6924
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6164 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6928
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.6164 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6916
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.6164 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6917
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 783us/step - accuracy: 0.6164 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6922
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6164 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6926
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6164 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.6917
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6164 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.6919
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6908
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6915
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6132 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.6924
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6269 - val_loss: 0.6910
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6632 - val_accuracy: 0.6306 - val_loss: 0.6919
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step - accuracy: 0.6196 - loss: 0.6629 - val_accuracy: 0.6269 - val_loss: 0.6917
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6269 - val_loss: 0.6909
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6132 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.6922
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.6100 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6893
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.6904
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6892
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.6914
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6164 - loss: 0.6637 - val_accuracy: 0.6269 - val_loss: 0.6925
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6100 - loss: 0.6684 - val_accuracy: 0.6269 - val_loss: 0.6912
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6148 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6905
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6164 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.6913
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6899
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6905
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6164 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6895
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6164 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.6907
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6892
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6902
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6914
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.6914
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6889
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 786us/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.6897
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6902
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.6885
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6893
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.6894
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.6896
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.6901
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.6882
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.6889
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6896
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6269 - val_loss: 0.6897
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6882
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6884
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.6893
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6893
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6164 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.6892
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6891
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6896
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 786us/step - accuracy: 0.6164 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.6896
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6899
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6898
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6899
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6887
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.6890
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6893
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6897
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6900
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6902
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.6902
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.6913
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6908
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6164 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.6893
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6896
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6902
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.6906
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6904
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.6906
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6907
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.6911
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6884
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6890
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6902
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6902
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6899
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6910
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6889
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6902
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.6904
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6908
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6164 - loss: 0.6635 - val_accuracy: 0.6269 - val_loss: 0.6912
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6915
Epoch 153/5000

wandb: Agent Starting Run: 115yb7pk with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3852 - loss: 56.3654 - val_accuracy: 0.4030 - val_loss: 24.0732
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4751 - loss: 7.0005 - val_accuracy: 0.6791 - val_loss: 1.1372
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5923 - loss: 1.1802 - val_accuracy: 0.5037 - val_loss: 1.3694
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.5859 - loss: 1.1759 - val_accuracy: 0.5560 - val_loss: 0.9479
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.5923 - loss: 1.0902 - val_accuracy: 0.6791 - val_loss: 0.8489
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.9801 - val_accuracy: 0.6269 - val_loss: 0.7295
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5955 - loss: 1.0066 - val_accuracy: 0.7090 - val_loss: 0.7089
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.6148 - loss: 0.9177 - val_accuracy: 0.7015 - val_loss: 0.6602
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.8372 - val_accuracy: 0.5560 - val_loss: 0.9161
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.6083 - loss: 0.9100 - val_accuracy: 0.6642 - val_loss: 0.9794
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.6067 - loss: 0.8418 - val_accuracy: 0.6604 - val_loss: 1.0018
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.6260 - loss: 0.8369 - val_accuracy: 0.7127 - val_loss: 0.6138
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6228 - loss: 0.8185 - val_accuracy: 0.6642 - val_loss: 0.7548
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.6180 - loss: 0.8077 - val_accuracy: 0.6642 - val_loss: 0.8769
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6067 - loss: 0.8128 - val_accuracy: 0.7015 - val_loss: 0.6417
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.6292 - loss: 0.8280 - val_accuracy: 0.7351 - val_loss: 0.5661
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6308 - loss: 0.7882 - val_accuracy: 0.7388 - val_loss: 0.5609
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.8028 - val_accuracy: 0.7463 - val_loss: 0.5640
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6276 - loss: 0.7662 - val_accuracy: 0.7052 - val_loss: 0.5717
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.6404 - loss: 0.7286 - val_accuracy: 0.6978 - val_loss: 0.6006
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6067 - loss: 0.7928 - val_accuracy: 0.5000 - val_loss: 0.9298
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6565 - loss: 0.7290 - val_accuracy: 0.5000 - val_loss: 0.8686
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6388 - loss: 0.7533 - val_accuracy: 0.6940 - val_loss: 0.5754
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6372 - loss: 0.7578 - val_accuracy: 0.7537 - val_loss: 0.5534
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.6581 - loss: 0.7066 - val_accuracy: 0.7052 - val_loss: 0.5519
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.7460 - val_accuracy: 0.6754 - val_loss: 0.6594
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6533 - loss: 0.7023 - val_accuracy: 0.6269 - val_loss: 0.6505
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6437 - loss: 0.6673 - val_accuracy: 0.6530 - val_loss: 1.0158
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6613 - loss: 0.6930 - val_accuracy: 0.6231 - val_loss: 0.6573
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6613 - loss: 0.6810 - val_accuracy: 0.7015 - val_loss: 0.5916
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6806 - loss: 0.6698 - val_accuracy: 0.6493 - val_loss: 0.8475
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6581 - loss: 0.7085 - val_accuracy: 0.7425 - val_loss: 0.5221
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6485 - loss: 0.7206 - val_accuracy: 0.7425 - val_loss: 0.5219
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6453 - loss: 0.7183 - val_accuracy: 0.7500 - val_loss: 0.5143
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6838 - loss: 0.6363 - val_accuracy: 0.6493 - val_loss: 0.9527
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.7135 - val_accuracy: 0.7164 - val_loss: 0.5407
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6966 - loss: 0.6340 - val_accuracy: 0.6604 - val_loss: 0.8099
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.6742 - loss: 0.6653 - val_accuracy: 0.6978 - val_loss: 0.5662
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6693 - loss: 0.7082 - val_accuracy: 0.6828 - val_loss: 0.7478
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.6998 - loss: 0.6259 - val_accuracy: 0.6828 - val_loss: 0.7768
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6790 - loss: 0.6765 - val_accuracy: 0.6754 - val_loss: 0.6841
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7063 - loss: 0.6465 - val_accuracy: 0.6343 - val_loss: 1.4238
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6902 - loss: 0.6931 - val_accuracy: 0.7052 - val_loss: 0.6124
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6966 - loss: 0.6383 - val_accuracy: 0.7575 - val_loss: 0.4985
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6870 - loss: 0.6791 - val_accuracy: 0.7313 - val_loss: 0.5253
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7159 - loss: 0.6432 - val_accuracy: 0.7985 - val_loss: 0.5159
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7095 - loss: 0.6151 - val_accuracy: 0.6567 - val_loss: 0.9815
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6758 - loss: 0.6512 - val_accuracy: 0.7910 - val_loss: 0.5010
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7063 - loss: 0.6540 - val_accuracy: 0.6903 - val_loss: 0.6454
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7271 - loss: 0.6263 - val_accuracy: 0.7873 - val_loss: 0.5057
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6822 - loss: 0.6441 - val_accuracy: 0.7873 - val_loss: 0.5181
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7207 - loss: 0.6030 - val_accuracy: 0.7090 - val_loss: 0.5732
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6822 - loss: 0.6814 - val_accuracy: 0.7910 - val_loss: 0.5000
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7368 - loss: 0.5996 - val_accuracy: 0.5224 - val_loss: 0.8657
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6854 - loss: 0.6402 - val_accuracy: 0.6754 - val_loss: 0.7351
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7207 - loss: 0.6046 - val_accuracy: 0.5522 - val_loss: 0.7809
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7047 - loss: 0.5791 - val_accuracy: 0.5597 - val_loss: 0.7816
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7079 - loss: 0.6428 - val_accuracy: 0.6530 - val_loss: 0.6478
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7400 - loss: 0.6059 - val_accuracy: 0.7724 - val_loss: 0.5069
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6998 - loss: 0.6076 - val_accuracy: 0.7873 - val_loss: 0.5289
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7207 - loss: 0.5852 - val_accuracy: 0.6754 - val_loss: 0.8065
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7159 - loss: 0.6251 - val_accuracy: 0.7425 - val_loss: 0.4908
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7223 - loss: 0.6162 - val_accuracy: 0.7761 - val_loss: 0.4790
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7159 - loss: 0.6079 - val_accuracy: 0.7873 - val_loss: 0.4887
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7480 - loss: 0.5777 - val_accuracy: 0.7612 - val_loss: 0.5748
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7159 - loss: 0.6245 - val_accuracy: 0.6604 - val_loss: 1.1238
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7319 - loss: 0.5870 - val_accuracy: 0.7239 - val_loss: 0.5445
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7207 - loss: 0.5903 - val_accuracy: 0.7351 - val_loss: 0.5422
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7143 - loss: 0.6170 - val_accuracy: 0.7276 - val_loss: 0.5298
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7191 - loss: 0.5806 - val_accuracy: 0.7313 - val_loss: 0.5131
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7335 - loss: 0.6016 - val_accuracy: 0.7388 - val_loss: 0.4980
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7271 - loss: 0.6130 - val_accuracy: 0.7836 - val_loss: 0.5316
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7255 - loss: 0.5953 - val_accuracy: 0.7351 - val_loss: 0.5110
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7287 - loss: 0.5683 - val_accuracy: 0.7649 - val_loss: 0.4996
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7319 - loss: 0.5720 - val_accuracy: 0.7090 - val_loss: 0.6034
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7416 - loss: 0.5740 - val_accuracy: 0.7239 - val_loss: 0.5159
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.7239 - loss: 0.5996 - val_accuracy: 0.7724 - val_loss: 0.4698
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7095 - loss: 0.6205 - val_accuracy: 0.7612 - val_loss: 0.4848
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7400 - loss: 0.5443 - val_accuracy: 0.7687 - val_loss: 0.4854
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.7801 - loss: 0.5268 - val_accuracy: 0.7500 - val_loss: 0.4922
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.7352 - loss: 0.5776 - val_accuracy: 0.7799 - val_loss: 0.5547
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7560 - loss: 0.5716 - val_accuracy: 0.7761 - val_loss: 0.4952
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7352 - loss: 0.5873 - val_accuracy: 0.7015 - val_loss: 0.6190
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7624 - loss: 0.5308 - val_accuracy: 0.7724 - val_loss: 0.4718
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.7608 - loss: 0.5611 - val_accuracy: 0.7836 - val_loss: 0.5137
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7352 - loss: 0.6316 - val_accuracy: 0.7724 - val_loss: 0.4675
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7512 - loss: 0.5511 - val_accuracy: 0.7836 - val_loss: 0.4912
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.7464 - loss: 0.5578 - val_accuracy: 0.7201 - val_loss: 0.5495
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7448 - loss: 0.5686 - val_accuracy: 0.7687 - val_loss: 0.4755
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7528 - loss: 0.5673 - val_accuracy: 0.7276 - val_loss: 0.5451
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7352 - loss: 0.6127 - val_accuracy: 0.7239 - val_loss: 0.5577
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7673 - loss: 0.5437 - val_accuracy: 0.7761 - val_loss: 0.4681
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7608 - loss: 0.5846 - val_accuracy: 0.7687 - val_loss: 0.4707
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7432 - loss: 0.5678 - val_accuracy: 0.5858 - val_loss: 0.7853
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7480 - loss: 0.5851 - val_accuracy: 0.7388 - val_loss: 0.5227
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7352 - loss: 0.5665 - val_accuracy: 0.6716 - val_loss: 0.9273
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7512 - loss: 0.5936 - val_accuracy: 0.7836 - val_loss: 0.5294
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7592 - loss: 0.5422 - val_accuracy: 0.7649 - val_loss: 0.4759
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.7737 - loss: 0.5398 - val_accuracy: 0.6716 - val_loss: 0.6545
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7464 - loss: 0.5420 - val_accuracy: 0.7724 - val_loss: 0.4883
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7544 - loss: 0.5766 - val_accuracy: 0.7351 - val_loss: 0.5190
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7544 - loss: 0.5520 - val_accuracy: 0.7239 - val_loss: 0.5978
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7448 - loss: 0.5963 - val_accuracy: 0.7761 - val_loss: 0.4684
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7592 - loss: 0.5428 - val_accuracy: 0.7687 - val_loss: 0.5705
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7657 - loss: 0.5622 - val_accuracy: 0.7724 - val_loss: 0.4679
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7560 - loss: 0.5567 - val_accuracy: 0.7799 - val_loss: 0.4914
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7624 - loss: 0.5663 - val_accuracy: 0.7612 - val_loss: 0.5825
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7384 - loss: 0.5669 - val_accuracy: 0.7761 - val_loss: 0.4739
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7640 - loss: 0.5428 - val_accuracy: 0.7724 - val_loss: 0.5736
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.7496 - loss: 0.5656 - val_accuracy: 0.7724 - val_loss: 0.4781
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7576 - loss: 0.5677 - val_accuracy: 0.7276 - val_loss: 0.5865
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7560 - loss: 0.5518 - val_accuracy: 0.7724 - val_loss: 0.4713
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7576 - loss: 0.5517 - val_accuracy: 0.6754 - val_loss: 0.8613
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7544 - loss: 0.5379 - val_accuracy: 0.7761 - val_loss: 0.4719
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7576 - loss: 0.5410 - val_accuracy: 0.7015 - val_loss: 0.7156
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7624 - loss: 0.5456 - val_accuracy: 0.7761 - val_loss: 0.4755
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7624 - loss: 0.5591 - val_accuracy: 0.7687 - val_loss: 0.4752
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7608 - loss: 0.5360 - val_accuracy: 0.7761 - val_loss: 0.4962
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7624 - loss: 0.5551 - val_accuracy: 0.7276 - val_loss: 0.5692
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.7480 - loss: 0.5593 - val_accuracy: 0.7649 - val_loss: 0.4823
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.7833 - loss: 0.5203 - val_accuracy: 0.7463 - val_loss: 0.5094
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7592 - loss: 0.5782 - val_accuracy: 0.7687 - val_loss: 0.4812
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7368 - loss: 0.5875 - val_accuracy: 0.7724 - val_loss: 0.4741
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7865 - loss: 0.5212 - val_accuracy: 0.7687 - val_loss: 0.4921
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7384 - loss: 0.5772 - val_accuracy: 0.7239 - val_loss: 0.6172
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7657 - loss: 0.5588 - val_accuracy: 0.7761 - val_loss: 0.4724
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7544 - loss: 0.5249 - val_accuracy: 0.7463 - val_loss: 0.5533
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7480 - loss: 0.5653 - val_accuracy: 0.7799 - val_loss: 0.4923
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7785 - loss: 0.5071 - val_accuracy: 0.7015 - val_loss: 0.7287
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7448 - loss: 0.5405 - val_accuracy: 0.7425 - val_loss: 0.5456
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7528 - loss: 0.5646 - val_accuracy: 0.7836 - val_loss: 0.5248
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7576 - loss: 0.5524 - val_accuracy: 0.6866 - val_loss: 0.8009
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.7721 - loss: 0.5460 - val_accuracy: 0.7127 - val_loss: 0.6156
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.7657 - loss: 0.5524 - val_accuracy: 0.7761 - val_loss: 0.4731
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.7592 - loss: 0.5339 - val_accuracy: 0.7687 - val_loss: 0.4756
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.7432 - loss: 0.5569 - val_accuracy: 0.7090 - val_loss: 0.6795
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7833 - loss: 0.5631 - val_accuracy: 0.7910 - val_loss: 0.5579
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7512 - loss: 0.5388 - val_accuracy: 0.7799 - val_loss: 0.5732
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7640 - loss: 0.5481 - val_accuracy: 0.7687 - val_loss: 0.4851
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7769 - loss: 0.5201 - val_accuracy: 0.7313 - val_loss: 0.5679
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7592 - loss: 0.5180 - val_accuracy: 0.7463 - val_loss: 0.5467
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7640 - loss: 0.5376 - val_accuracy: 0.7649 - val_loss: 0.4854
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7801 - loss: 0.5350 - val_accuracy: 0.7015 - val_loss: 0.6290
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.7817 - loss: 0.5528 - val_accuracy: 0.7649 - val_loss: 0.4788
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7592 - loss: 0.5255 - val_accuracy: 0.7276 - val_loss: 0.5898
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7640 - loss: 0.5471 - val_accuracy: 0.7761 - val_loss: 0.4994
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7528 - loss: 0.5551 - val_accuracy: 0.7799 - val_loss: 0.4948
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.7849 - loss: 0.5084 - val_accuracy: 0.6828 - val_loss: 0.6603
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.7705 - loss: 0.5143 - val_accuracy: 0.7649 - val_loss: 0.5264
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7576 - loss: 0.5355 - val_accuracy: 0.7313 - val_loss: 0.5729
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7673 - loss: 0.5421 - val_accuracy: 0.7761 - val_loss: 0.5010
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7673 - loss: 0.5322 - val_accuracy: 0.5410 - val_loss: 0.9578
Epoch 153/5000

wandb: Agent Starting Run: d7tvgjcj with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 2.4766 - val_accuracy: 0.7015 - val_loss: 2.0145
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 1.6912 - val_accuracy: 0.7090 - val_loss: 1.3987
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.6726 - loss: 1.3132 - val_accuracy: 0.6157 - val_loss: 1.2604
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6501 - loss: 1.0854 - val_accuracy: 0.7239 - val_loss: 0.9529
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.6629 - loss: 0.8752 - val_accuracy: 0.6828 - val_loss: 1.1285
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.6228 - loss: 0.8654 - val_accuracy: 0.7090 - val_loss: 0.7590
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6292 - loss: 0.7894 - val_accuracy: 0.6903 - val_loss: 0.7851
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6003 - loss: 0.8554 - val_accuracy: 0.6194 - val_loss: 0.7943
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.6859 - val_accuracy: 0.6604 - val_loss: 0.9189
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6806 - loss: 0.6873 - val_accuracy: 0.7313 - val_loss: 0.6775
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6822 - loss: 0.6281 - val_accuracy: 0.7388 - val_loss: 0.6497
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7239 - loss: 0.5898 - val_accuracy: 0.6978 - val_loss: 0.6637
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6822 - loss: 0.6302 - val_accuracy: 0.6604 - val_loss: 0.7597
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.6726 - loss: 0.6649 - val_accuracy: 0.7239 - val_loss: 0.6187
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6838 - loss: 0.6214 - val_accuracy: 0.7351 - val_loss: 0.6417
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7287 - loss: 0.5606 - val_accuracy: 0.6082 - val_loss: 0.7323
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7159 - loss: 0.5830 - val_accuracy: 0.7164 - val_loss: 0.6264
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6742 - loss: 0.6409 - val_accuracy: 0.7388 - val_loss: 0.5952
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.5736 - val_accuracy: 0.7276 - val_loss: 0.6000
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6838 - loss: 0.6333 - val_accuracy: 0.7164 - val_loss: 0.6117
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7608 - loss: 0.5261 - val_accuracy: 0.7388 - val_loss: 0.5837
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7657 - loss: 0.5371 - val_accuracy: 0.6791 - val_loss: 0.6826
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6608 - val_accuracy: 0.5970 - val_loss: 0.7746
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7640 - loss: 0.5319 - val_accuracy: 0.7463 - val_loss: 0.5716
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.7721 - loss: 0.5037 - val_accuracy: 0.7687 - val_loss: 0.6274
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7432 - loss: 0.5326 - val_accuracy: 0.7500 - val_loss: 0.5786
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7416 - loss: 0.5736 - val_accuracy: 0.6866 - val_loss: 0.7067
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7384 - loss: 0.5483 - val_accuracy: 0.4888 - val_loss: 1.0072
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7030 - loss: 0.6393 - val_accuracy: 0.7052 - val_loss: 0.6630
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.7560 - loss: 0.5353 - val_accuracy: 0.7724 - val_loss: 0.6152
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7207 - loss: 0.5596 - val_accuracy: 0.6679 - val_loss: 0.7083
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7817 - loss: 0.5204 - val_accuracy: 0.7575 - val_loss: 0.5825
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7560 - loss: 0.5317 - val_accuracy: 0.7687 - val_loss: 0.6089
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7544 - loss: 0.5395 - val_accuracy: 0.7015 - val_loss: 0.6588
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7576 - loss: 0.5223 - val_accuracy: 0.7575 - val_loss: 0.5990
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4738 - val_accuracy: 0.7463 - val_loss: 0.5713
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.7945 - loss: 0.5069 - val_accuracy: 0.7276 - val_loss: 0.6652
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7657 - loss: 0.5441 - val_accuracy: 0.6828 - val_loss: 0.7419
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.7801 - loss: 0.5165 - val_accuracy: 0.7687 - val_loss: 0.5584
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7865 - loss: 0.5075 - val_accuracy: 0.7575 - val_loss: 0.5629
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.7978 - loss: 0.4750 - val_accuracy: 0.7239 - val_loss: 0.6033
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.7721 - loss: 0.5125 - val_accuracy: 0.7724 - val_loss: 0.5576
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.7753 - loss: 0.4959 - val_accuracy: 0.7575 - val_loss: 0.5532
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.7945 - loss: 0.4922 - val_accuracy: 0.7313 - val_loss: 0.6070
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6934 - loss: 0.7407 - val_accuracy: 0.7612 - val_loss: 0.5541
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7640 - loss: 0.5947 - val_accuracy: 0.7239 - val_loss: 0.6159
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7512 - loss: 0.5688 - val_accuracy: 0.7052 - val_loss: 0.7046
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7705 - loss: 0.5071 - val_accuracy: 0.7425 - val_loss: 0.6531
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.7865 - loss: 0.5011 - val_accuracy: 0.7575 - val_loss: 0.5532
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7881 - loss: 0.4643 - val_accuracy: 0.7761 - val_loss: 0.6086
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.8026 - loss: 0.4731 - val_accuracy: 0.7761 - val_loss: 0.5718
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.7801 - loss: 0.5151 - val_accuracy: 0.7575 - val_loss: 0.5707
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4685 - val_accuracy: 0.6231 - val_loss: 0.7969
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.7705 - loss: 0.5370 - val_accuracy: 0.7463 - val_loss: 0.5762
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7897 - loss: 0.4732 - val_accuracy: 0.7612 - val_loss: 0.5671
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7897 - loss: 0.4945 - val_accuracy: 0.7388 - val_loss: 0.5977
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.7817 - loss: 0.4763 - val_accuracy: 0.7724 - val_loss: 0.5836
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.8106 - loss: 0.4505 - val_accuracy: 0.7836 - val_loss: 0.6294
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.7753 - loss: 0.5137 - val_accuracy: 0.7687 - val_loss: 0.5567
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7929 - loss: 0.5321 - val_accuracy: 0.6343 - val_loss: 0.7831
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7657 - loss: 0.5849 - val_accuracy: 0.7687 - val_loss: 0.5641
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.7640 - loss: 0.5200 - val_accuracy: 0.7463 - val_loss: 0.5789
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.7961 - loss: 0.4750 - val_accuracy: 0.7612 - val_loss: 0.5540
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.7608 - loss: 0.5444 - val_accuracy: 0.7015 - val_loss: 0.7589
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7560 - loss: 0.5532 - val_accuracy: 0.7649 - val_loss: 0.5657
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7929 - loss: 0.5117 - val_accuracy: 0.7612 - val_loss: 0.5509
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.7705 - loss: 0.5319 - val_accuracy: 0.7575 - val_loss: 0.5534
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7865 - loss: 0.4925 - val_accuracy: 0.7687 - val_loss: 0.5513
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7961 - loss: 0.4578 - val_accuracy: 0.7612 - val_loss: 0.5624
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.8074 - loss: 0.4741 - val_accuracy: 0.7873 - val_loss: 0.6411
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5912 - val_accuracy: 0.7724 - val_loss: 0.5582
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7961 - loss: 0.5099 - val_accuracy: 0.7836 - val_loss: 0.6023
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7785 - loss: 0.4996 - val_accuracy: 0.7687 - val_loss: 0.5625
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.7865 - loss: 0.4843 - val_accuracy: 0.7575 - val_loss: 0.5505
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.8074 - loss: 0.4730 - val_accuracy: 0.7015 - val_loss: 0.7238
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.7785 - loss: 0.5100 - val_accuracy: 0.5933 - val_loss: 0.8743
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7801 - loss: 0.5203 - val_accuracy: 0.7575 - val_loss: 0.5701
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.7657 - loss: 0.5317 - val_accuracy: 0.7388 - val_loss: 0.6171
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7721 - loss: 0.5526 - val_accuracy: 0.7612 - val_loss: 0.6523
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.7978 - loss: 0.5014 - val_accuracy: 0.7724 - val_loss: 0.6398
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7801 - loss: 0.5380 - val_accuracy: 0.7649 - val_loss: 0.5583
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7801 - loss: 0.5114 - val_accuracy: 0.7612 - val_loss: 0.5474
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.7913 - loss: 0.4816 - val_accuracy: 0.7687 - val_loss: 0.5609
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7785 - loss: 0.5248 - val_accuracy: 0.7649 - val_loss: 0.5542
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.7881 - loss: 0.4979 - val_accuracy: 0.7724 - val_loss: 0.5947
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.8058 - loss: 0.4930 - val_accuracy: 0.6343 - val_loss: 0.7886
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7881 - loss: 0.5167 - val_accuracy: 0.7351 - val_loss: 0.6187
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4598 - val_accuracy: 0.7799 - val_loss: 0.6110
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7978 - loss: 0.4585 - val_accuracy: 0.6940 - val_loss: 0.7647
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4773 - val_accuracy: 0.7687 - val_loss: 0.5557
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.8042 - loss: 0.4746 - val_accuracy: 0.7500 - val_loss: 0.5982
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5180 - val_accuracy: 0.7201 - val_loss: 0.6993
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.7689 - loss: 0.5253 - val_accuracy: 0.7313 - val_loss: 0.6183
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.5068 - val_accuracy: 0.6903 - val_loss: 0.8469
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7929 - loss: 0.4932 - val_accuracy: 0.7052 - val_loss: 0.6982
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.7913 - loss: 0.4883 - val_accuracy: 0.7649 - val_loss: 0.5499
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8058 - loss: 0.4568 - val_accuracy: 0.7575 - val_loss: 0.5456
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7785 - loss: 0.5023 - val_accuracy: 0.7052 - val_loss: 0.6900
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7544 - loss: 0.5479 - val_accuracy: 0.7649 - val_loss: 0.5648
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.7352 - loss: 0.6682 - val_accuracy: 0.7575 - val_loss: 0.5405
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.7335 - loss: 0.7394 - val_accuracy: 0.7276 - val_loss: 0.7380
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7817 - loss: 0.5035 - val_accuracy: 0.7463 - val_loss: 0.5889
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.7657 - loss: 0.5194 - val_accuracy: 0.7724 - val_loss: 0.5829
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.7994 - loss: 0.4876 - val_accuracy: 0.7425 - val_loss: 0.6271
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4710 - val_accuracy: 0.7425 - val_loss: 0.6028
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.7881 - loss: 0.4991 - val_accuracy: 0.7761 - val_loss: 0.5746
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.7961 - loss: 0.4599 - val_accuracy: 0.7649 - val_loss: 0.5516
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.5037 - val_accuracy: 0.7388 - val_loss: 0.6358
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4697 - val_accuracy: 0.7388 - val_loss: 0.6174
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5444 - val_accuracy: 0.7612 - val_loss: 0.5594
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.7785 - loss: 0.4953 - val_accuracy: 0.7687 - val_loss: 0.5679
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.5070 - val_accuracy: 0.7761 - val_loss: 0.6065
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.8010 - loss: 0.4761 - val_accuracy: 0.7537 - val_loss: 0.5672
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4662 - val_accuracy: 0.7164 - val_loss: 0.6990
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4795 - val_accuracy: 0.7799 - val_loss: 0.6131
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5723 - val_accuracy: 0.7612 - val_loss: 0.5642
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4998 - val_accuracy: 0.7649 - val_loss: 0.5580
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.7961 - loss: 0.4536 - val_accuracy: 0.7799 - val_loss: 0.6160
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.8042 - loss: 0.4598 - val_accuracy: 0.7799 - val_loss: 0.6133
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5120 - val_accuracy: 0.7649 - val_loss: 0.5354
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.7148 - val_accuracy: 0.7052 - val_loss: 0.7275
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5749 - val_accuracy: 0.7724 - val_loss: 0.5667
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4908 - val_accuracy: 0.7910 - val_loss: 0.6212
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.5163 - val_accuracy: 0.7836 - val_loss: 0.6080
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.7721 - loss: 0.5528 - val_accuracy: 0.7612 - val_loss: 0.6035
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4955 - val_accuracy: 0.7463 - val_loss: 0.5880
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.8058 - loss: 0.4560 - val_accuracy: 0.7313 - val_loss: 0.6172
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4906 - val_accuracy: 0.7575 - val_loss: 0.5884
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.7945 - loss: 0.4888 - val_accuracy: 0.7724 - val_loss: 0.5696
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.8074 - loss: 0.4563 - val_accuracy: 0.7463 - val_loss: 0.6089
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.7913 - loss: 0.4647 - val_accuracy: 0.7425 - val_loss: 0.6284
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4648 - val_accuracy: 0.7649 - val_loss: 0.5563
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.7673 - loss: 0.5665 - val_accuracy: 0.7463 - val_loss: 0.6134
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5153 - val_accuracy: 0.7612 - val_loss: 0.5825
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.7897 - loss: 0.4874 - val_accuracy: 0.7351 - val_loss: 0.6211
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4833 - val_accuracy: 0.7164 - val_loss: 0.7648
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5839 - val_accuracy: 0.7612 - val_loss: 0.5450
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.8026 - loss: 0.4643 - val_accuracy: 0.6866 - val_loss: 0.9049
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.7929 - loss: 0.4876 - val_accuracy: 0.7575 - val_loss: 0.6847
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7961 - loss: 0.4654 - val_accuracy: 0.7687 - val_loss: 0.5707
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4621 - val_accuracy: 0.7799 - val_loss: 0.6071
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7817 - loss: 0.5020 - val_accuracy: 0.7761 - val_loss: 0.5772
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8090 - loss: 0.4463 - val_accuracy: 0.7724 - val_loss: 0.5945
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.8106 - loss: 0.4659 - val_accuracy: 0.7612 - val_loss: 0.5568
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8074 - loss: 0.4651 - val_accuracy: 0.7388 - val_loss: 0.6678
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.8154 - loss: 0.4774 - val_accuracy: 0.7687 - val_loss: 0.5550
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.8026 - loss: 0.4757 - val_accuracy: 0.7761 - val_loss: 0.5903
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8010 - loss: 0.4620 - val_accuracy: 0.7687 - val_loss: 0.5694
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7913 - loss: 0.4848 - val_accuracy: 0.7649 - val_loss: 0.5636
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.8058 - loss: 0.4664 - val_accuracy: 0.7799 - val_loss: 0.5732
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.7978 - loss: 0.4845 - val_accuracy: 0.7575 - val_loss: 0.5563
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7961 - loss: 0.4603 - val_accuracy: 0.7799 - val_loss: 0.6040
Epoch 153/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: pcw9csi9 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6019 - loss: 8.3154 - val_accuracy: 0.6306 - val_loss: 0.7174
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6148 - loss: 0.6929 - val_accuracy: 0.6343 - val_loss: 0.7109
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6148 - loss: 0.6854 - val_accuracy: 0.6343 - val_loss: 0.6719
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6180 - loss: 0.6744 - val_accuracy: 0.6269 - val_loss: 0.6898
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6180 - loss: 0.6719 - val_accuracy: 0.6306 - val_loss: 0.6782
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.6196 - loss: 0.6729 - val_accuracy: 0.6306 - val_loss: 0.6774
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - accuracy: 0.6148 - loss: 0.6717 - val_accuracy: 0.6306 - val_loss: 0.6732
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 0.6180 - loss: 0.6675 - val_accuracy: 0.6343 - val_loss: 0.6741
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6306 - val_loss: 0.6786
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step - accuracy: 0.6196 - loss: 0.6681 - val_accuracy: 0.6306 - val_loss: 0.6579
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.6180 - loss: 0.6656 - val_accuracy: 0.6343 - val_loss: 0.6695
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6164 - loss: 0.6694 - val_accuracy: 0.6306 - val_loss: 0.6600
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6196 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6606
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6212 - loss: 0.6633 - val_accuracy: 0.6306 - val_loss: 0.6689
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - accuracy: 0.6180 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6671
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step - accuracy: 0.6212 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6662
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.6180 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.6623
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.6196 - loss: 0.6671 - val_accuracy: 0.6343 - val_loss: 0.6547
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.6180 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6647
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - accuracy: 0.6196 - loss: 0.6618 - val_accuracy: 0.6306 - val_loss: 0.6674
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6164 - loss: 0.6661 - val_accuracy: 0.6269 - val_loss: 0.6615
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 779us/step - accuracy: 0.6228 - loss: 0.6628 - val_accuracy: 0.6269 - val_loss: 0.6607
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6196 - loss: 0.6634 - val_accuracy: 0.6306 - val_loss: 0.6712
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6196 - loss: 0.6626 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6196 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.6180 - loss: 0.6654 - val_accuracy: 0.6306 - val_loss: 0.6660
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - accuracy: 0.6196 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.6656
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - accuracy: 0.6196 - loss: 0.6655 - val_accuracy: 0.6343 - val_loss: 0.6644
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - accuracy: 0.6180 - loss: 0.6654 - val_accuracy: 0.6343 - val_loss: 0.6647
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6343 - val_loss: 0.6654
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6196 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.6553
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6244 - loss: 0.6620 - val_accuracy: 0.6343 - val_loss: 0.6649
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.6212 - loss: 0.6631 - val_accuracy: 0.6343 - val_loss: 0.6582
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step - accuracy: 0.6228 - loss: 0.6623 - val_accuracy: 0.6269 - val_loss: 0.6625
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step - accuracy: 0.6196 - loss: 0.6626 - val_accuracy: 0.6381 - val_loss: 0.6601
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6381 - val_loss: 0.6626
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.6228 - loss: 0.6682 - val_accuracy: 0.6381 - val_loss: 0.6543
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step - accuracy: 0.6164 - loss: 0.6630 - val_accuracy: 0.6343 - val_loss: 0.6592
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 783us/step - accuracy: 0.6196 - loss: 0.6654 - val_accuracy: 0.6343 - val_loss: 0.6600
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 783us/step - accuracy: 0.6260 - loss: 0.6605 - val_accuracy: 0.6381 - val_loss: 0.6623
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 0.6180 - loss: 0.6643 - val_accuracy: 0.6381 - val_loss: 0.6619
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - accuracy: 0.6180 - loss: 0.6628 - val_accuracy: 0.6381 - val_loss: 0.6547
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.6228 - loss: 0.6619 - val_accuracy: 0.6343 - val_loss: 0.6601
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6196 - loss: 0.6614 - val_accuracy: 0.6343 - val_loss: 0.6602
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6343 - val_loss: 0.6587
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.6196 - loss: 0.6626 - val_accuracy: 0.6343 - val_loss: 0.6591
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 0.6244 - loss: 0.6620 - val_accuracy: 0.6343 - val_loss: 0.6614
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6244 - loss: 0.6603 - val_accuracy: 0.6343 - val_loss: 0.6626
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6228 - loss: 0.6611 - val_accuracy: 0.6306 - val_loss: 0.6572
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6228 - loss: 0.6614 - val_accuracy: 0.6343 - val_loss: 0.6605
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.6244 - loss: 0.6624 - val_accuracy: 0.6306 - val_loss: 0.6594
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6228 - loss: 0.6617 - val_accuracy: 0.6306 - val_loss: 0.6590
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6228 - loss: 0.6622 - val_accuracy: 0.6306 - val_loss: 0.6576
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6260 - loss: 0.6590 - val_accuracy: 0.6306 - val_loss: 0.6630
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6244 - loss: 0.6599 - val_accuracy: 0.6306 - val_loss: 0.6576
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - accuracy: 0.6260 - loss: 0.6593 - val_accuracy: 0.6306 - val_loss: 0.6623
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - accuracy: 0.6244 - loss: 0.6597 - val_accuracy: 0.6343 - val_loss: 0.6590
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.6260 - loss: 0.6607 - val_accuracy: 0.6306 - val_loss: 0.6612
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.6244 - loss: 0.6609 - val_accuracy: 0.6306 - val_loss: 0.6598
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.6244 - loss: 0.6590 - val_accuracy: 0.6306 - val_loss: 0.6572
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6260 - loss: 0.6608 - val_accuracy: 0.6306 - val_loss: 0.6579
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6244 - loss: 0.6608 - val_accuracy: 0.6306 - val_loss: 0.6600
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6244 - loss: 0.6594 - val_accuracy: 0.6306 - val_loss: 0.6600
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.6212 - loss: 0.6599 - val_accuracy: 0.6306 - val_loss: 0.6582
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 0.6276 - loss: 0.6592 - val_accuracy: 0.6306 - val_loss: 0.6585
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 0.6276 - loss: 0.7073 - val_accuracy: 0.6306 - val_loss: 0.6588
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6244 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.6577
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6244 - loss: 0.6633 - val_accuracy: 0.6306 - val_loss: 0.6571
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6212 - loss: 0.6615 - val_accuracy: 0.6306 - val_loss: 0.6608
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6244 - loss: 0.6623 - val_accuracy: 0.6306 - val_loss: 0.6632
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6260 - loss: 0.6608 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.6228 - loss: 0.6623 - val_accuracy: 0.6306 - val_loss: 0.6589
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6343 - val_loss: 0.6598
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6306 - val_loss: 0.6620
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6196 - loss: 0.6607 - val_accuracy: 0.6306 - val_loss: 0.6584
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.6212 - loss: 0.6624 - val_accuracy: 0.6306 - val_loss: 0.6595
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6212 - loss: 0.6603 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6164 - loss: 0.6618 - val_accuracy: 0.6269 - val_loss: 0.6610
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.6180 - loss: 0.6622 - val_accuracy: 0.6269 - val_loss: 0.6629
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - accuracy: 0.6212 - loss: 0.6604 - val_accuracy: 0.6269 - val_loss: 0.6572
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6228 - loss: 0.6599 - val_accuracy: 0.6269 - val_loss: 0.6629
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6228 - loss: 0.6597 - val_accuracy: 0.6269 - val_loss: 0.6596
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6212 - loss: 0.6597 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6633
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.6196 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.6595
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 0.6244 - loss: 0.6580 - val_accuracy: 0.6306 - val_loss: 0.6578
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.6212 - loss: 0.6606 - val_accuracy: 0.6269 - val_loss: 0.6621
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6228 - loss: 0.6593 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6269 - val_loss: 0.6609
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6228 - loss: 0.6607 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.6244 - loss: 0.6596 - val_accuracy: 0.6269 - val_loss: 0.6619
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 0.6228 - loss: 0.6593 - val_accuracy: 0.6269 - val_loss: 0.6593
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - accuracy: 0.6228 - loss: 0.6592 - val_accuracy: 0.6269 - val_loss: 0.6646
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6164 - loss: 0.6613 - val_accuracy: 0.6269 - val_loss: 0.6619
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6212 - loss: 0.6593 - val_accuracy: 0.6269 - val_loss: 0.6606
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.6244 - loss: 0.6597 - val_accuracy: 0.6269 - val_loss: 0.6637
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.6212 - loss: 0.6590 - val_accuracy: 0.6269 - val_loss: 0.6619
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - accuracy: 0.6228 - loss: 0.6613 - val_accuracy: 0.6269 - val_loss: 0.6601
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6196 - loss: 0.6608 - val_accuracy: 0.6269 - val_loss: 0.6602
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6244 - loss: 0.6604 - val_accuracy: 0.6269 - val_loss: 0.6599
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.6228 - loss: 0.6607 - val_accuracy: 0.6269 - val_loss: 0.6595
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6244 - loss: 0.6600 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6228 - loss: 0.6591 - val_accuracy: 0.6269 - val_loss: 0.6632
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.6228 - loss: 0.6592 - val_accuracy: 0.6269 - val_loss: 0.6594
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6228 - loss: 0.6596 - val_accuracy: 0.6269 - val_loss: 0.6631
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.6196 - loss: 0.6604 - val_accuracy: 0.6269 - val_loss: 0.6646
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6228 - loss: 0.6591 - val_accuracy: 0.6269 - val_loss: 0.6589
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6244 - loss: 0.6576 - val_accuracy: 0.6306 - val_loss: 0.6585
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6212 - loss: 0.6591 - val_accuracy: 0.6269 - val_loss: 0.6603
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6212 - loss: 0.6601 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.6228 - loss: 0.6602 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - accuracy: 0.6212 - loss: 0.6591 - val_accuracy: 0.6269 - val_loss: 0.6635
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6228 - loss: 0.6589 - val_accuracy: 0.6269 - val_loss: 0.6600
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6212 - loss: 0.6599 - val_accuracy: 0.6269 - val_loss: 0.6605
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6196 - loss: 0.6600 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.6228 - loss: 0.6591 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step - accuracy: 0.6212 - loss: 0.6587 - val_accuracy: 0.6269 - val_loss: 0.6601
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6244 - loss: 0.6589 - val_accuracy: 0.6269 - val_loss: 0.6648
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6180 - loss: 0.6594 - val_accuracy: 0.6269 - val_loss: 0.6633
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.6228 - loss: 0.6588 - val_accuracy: 0.6269 - val_loss: 0.6655
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.6228 - loss: 0.6584 - val_accuracy: 0.6269 - val_loss: 0.6626
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6228 - loss: 0.6601 - val_accuracy: 0.6269 - val_loss: 0.6637
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6212 - loss: 0.6594 - val_accuracy: 0.6269 - val_loss: 0.6655
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.6212 - loss: 0.6594 - val_accuracy: 0.6306 - val_loss: 0.6641
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6244 - loss: 0.6580 - val_accuracy: 0.6269 - val_loss: 0.6607
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6212 - loss: 0.6594 - val_accuracy: 0.6269 - val_loss: 0.6619
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6244 - loss: 0.6581 - val_accuracy: 0.6269 - val_loss: 0.6663
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.6228 - loss: 0.6581 - val_accuracy: 0.6269 - val_loss: 0.6605
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - accuracy: 0.6212 - loss: 0.6584 - val_accuracy: 0.6306 - val_loss: 0.6641
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6212 - loss: 0.6580 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6228 - loss: 0.6592 - val_accuracy: 0.6269 - val_loss: 0.6607
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6244 - loss: 0.6582 - val_accuracy: 0.6269 - val_loss: 0.6641
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6212 - loss: 0.6578 - val_accuracy: 0.6269 - val_loss: 0.6618
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.6260 - loss: 0.6581 - val_accuracy: 0.6269 - val_loss: 0.6654
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6212 - loss: 0.6578 - val_accuracy: 0.6269 - val_loss: 0.6616
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 0.6228 - loss: 0.6590 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - accuracy: 0.6260 - loss: 0.6583 - val_accuracy: 0.6269 - val_loss: 0.6655
Epoch 137: early stopping

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: hsqbdjfr with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5875 - loss: 1.2283 - val_accuracy: 0.6754 - val_loss: 0.8278
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.6019 - loss: 1.0754 - val_accuracy: 0.4515 - val_loss: 1.1483
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6180 - loss: 0.9853 - val_accuracy: 0.6940 - val_loss: 0.7089
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.6228 - loss: 0.9178 - val_accuracy: 0.7127 - val_loss: 0.7340
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.9152 - val_accuracy: 0.7127 - val_loss: 0.6557
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6019 - loss: 0.8959 - val_accuracy: 0.6679 - val_loss: 0.8922
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.8581 - val_accuracy: 0.5075 - val_loss: 0.8369
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.6340 - loss: 0.8865 - val_accuracy: 0.7313 - val_loss: 0.6280
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6356 - loss: 0.7161 - val_accuracy: 0.4515 - val_loss: 1.7448
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6308 - loss: 0.8359 - val_accuracy: 0.4776 - val_loss: 0.9536
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6196 - loss: 0.8702 - val_accuracy: 0.6828 - val_loss: 0.6896
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6597 - loss: 0.7851 - val_accuracy: 0.7052 - val_loss: 0.6381
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6517 - loss: 0.7837 - val_accuracy: 0.6567 - val_loss: 0.9908
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6693 - loss: 0.8016 - val_accuracy: 0.7351 - val_loss: 0.5701
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6661 - loss: 0.7371 - val_accuracy: 0.5970 - val_loss: 0.7098
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6533 - loss: 0.7822 - val_accuracy: 0.6791 - val_loss: 0.7045
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6870 - loss: 0.7355 - val_accuracy: 0.5970 - val_loss: 0.7058
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6629 - loss: 0.7639 - val_accuracy: 0.6828 - val_loss: 0.7681
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6902 - loss: 0.7336 - val_accuracy: 0.6828 - val_loss: 0.7241
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6709 - loss: 0.7413 - val_accuracy: 0.7575 - val_loss: 0.5192
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.6950 - loss: 0.7089 - val_accuracy: 0.6940 - val_loss: 0.6741
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6998 - loss: 0.7109 - val_accuracy: 0.6493 - val_loss: 1.0720
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.6854 - loss: 0.7396 - val_accuracy: 0.6828 - val_loss: 0.6835
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6870 - loss: 0.7240 - val_accuracy: 0.6679 - val_loss: 0.7454
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6822 - loss: 0.6988 - val_accuracy: 0.6007 - val_loss: 0.7014
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7159 - loss: 0.6637 - val_accuracy: 0.6679 - val_loss: 0.6621
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7014 - loss: 0.6878 - val_accuracy: 0.7127 - val_loss: 0.5623
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7191 - loss: 0.6723 - val_accuracy: 0.7351 - val_loss: 0.5313
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.6822 - loss: 0.7197 - val_accuracy: 0.6642 - val_loss: 1.0027
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.7127 - loss: 0.6796 - val_accuracy: 0.6903 - val_loss: 0.7458
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7159 - loss: 0.7034 - val_accuracy: 0.7313 - val_loss: 0.5819
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7207 - loss: 0.6975 - val_accuracy: 0.7127 - val_loss: 0.6121
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7384 - loss: 0.6078 - val_accuracy: 0.7575 - val_loss: 0.4883
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7191 - loss: 0.6557 - val_accuracy: 0.7500 - val_loss: 0.5296
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.6536 - val_accuracy: 0.7463 - val_loss: 0.4988
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.7063 - loss: 0.6907 - val_accuracy: 0.7351 - val_loss: 0.5247
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7512 - loss: 0.5925 - val_accuracy: 0.5336 - val_loss: 0.9290
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7319 - loss: 0.6510 - val_accuracy: 0.7052 - val_loss: 0.6764
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7239 - loss: 0.6553 - val_accuracy: 0.5933 - val_loss: 0.8029
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7239 - loss: 0.6959 - val_accuracy: 0.7313 - val_loss: 0.6295
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7480 - loss: 0.6263 - val_accuracy: 0.7649 - val_loss: 0.4920
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7432 - loss: 0.6634 - val_accuracy: 0.7425 - val_loss: 0.5092
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7448 - loss: 0.5935 - val_accuracy: 0.7687 - val_loss: 0.4849
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7239 - loss: 0.6375 - val_accuracy: 0.6754 - val_loss: 1.0086
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.7544 - loss: 0.6120 - val_accuracy: 0.7724 - val_loss: 0.4778
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7335 - loss: 0.6876 - val_accuracy: 0.7910 - val_loss: 0.5464
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7480 - loss: 0.6207 - val_accuracy: 0.7575 - val_loss: 0.5019
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7512 - loss: 0.6053 - val_accuracy: 0.7276 - val_loss: 0.5864
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7592 - loss: 0.6075 - val_accuracy: 0.7090 - val_loss: 0.6854
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7319 - loss: 0.6610 - val_accuracy: 0.7799 - val_loss: 0.4877
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7255 - loss: 0.6076 - val_accuracy: 0.7463 - val_loss: 0.5115
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.7303 - loss: 0.6574 - val_accuracy: 0.7575 - val_loss: 0.4809
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7560 - loss: 0.6052 - val_accuracy: 0.6940 - val_loss: 0.6645
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7480 - loss: 0.6389 - val_accuracy: 0.7276 - val_loss: 0.5538
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7368 - loss: 0.6034 - val_accuracy: 0.7201 - val_loss: 0.6359
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.7400 - loss: 0.6048 - val_accuracy: 0.6679 - val_loss: 0.7053
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 0.7544 - loss: 0.5931 - val_accuracy: 0.6940 - val_loss: 0.9402
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7560 - loss: 0.5940 - val_accuracy: 0.7313 - val_loss: 0.6727
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.7480 - loss: 0.6025 - val_accuracy: 0.7575 - val_loss: 0.5221
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7608 - loss: 0.5712 - val_accuracy: 0.7164 - val_loss: 0.6460
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7384 - loss: 0.6294 - val_accuracy: 0.7649 - val_loss: 0.4736
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7464 - loss: 0.6073 - val_accuracy: 0.7239 - val_loss: 0.6290
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7384 - loss: 0.6346 - val_accuracy: 0.7575 - val_loss: 0.4958
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7657 - loss: 0.5705 - val_accuracy: 0.6903 - val_loss: 0.7880
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7753 - loss: 0.5587 - val_accuracy: 0.6978 - val_loss: 1.1019
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7560 - loss: 0.6499 - val_accuracy: 0.7761 - val_loss: 0.4683
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.7512 - loss: 0.5807 - val_accuracy: 0.7239 - val_loss: 0.6986
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7624 - loss: 0.5449 - val_accuracy: 0.7388 - val_loss: 0.5182
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7592 - loss: 0.6060 - val_accuracy: 0.6903 - val_loss: 0.9050
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7544 - loss: 0.5911 - val_accuracy: 0.7948 - val_loss: 0.5068
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.7592 - loss: 0.5911 - val_accuracy: 0.7537 - val_loss: 0.5183
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7624 - loss: 0.6171 - val_accuracy: 0.7164 - val_loss: 0.6525
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7576 - loss: 0.5757 - val_accuracy: 0.7239 - val_loss: 0.7106
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7432 - loss: 0.6066 - val_accuracy: 0.7612 - val_loss: 0.4573
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7544 - loss: 0.5678 - val_accuracy: 0.7687 - val_loss: 0.4779
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7560 - loss: 0.6093 - val_accuracy: 0.7948 - val_loss: 0.4664
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.7769 - loss: 0.5272 - val_accuracy: 0.7425 - val_loss: 0.5698
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.7624 - loss: 0.6105 - val_accuracy: 0.6418 - val_loss: 0.7890
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7592 - loss: 0.6007 - val_accuracy: 0.7425 - val_loss: 0.4859
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.7689 - loss: 0.5882 - val_accuracy: 0.7425 - val_loss: 0.6489
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7689 - loss: 0.6094 - val_accuracy: 0.7500 - val_loss: 0.4753
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7528 - loss: 0.6019 - val_accuracy: 0.4739 - val_loss: 1.3711
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.7496 - loss: 0.5776 - val_accuracy: 0.7761 - val_loss: 0.4943
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 786us/step - accuracy: 0.7689 - loss: 0.5787 - val_accuracy: 0.7836 - val_loss: 0.5363
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.7657 - loss: 0.5814 - val_accuracy: 0.7948 - val_loss: 0.5269
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7432 - loss: 0.5903 - val_accuracy: 0.7649 - val_loss: 0.4977
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7448 - loss: 0.6009 - val_accuracy: 0.7164 - val_loss: 0.6576
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7657 - loss: 0.6279 - val_accuracy: 0.7537 - val_loss: 0.5717
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.7833 - loss: 0.5205 - val_accuracy: 0.6866 - val_loss: 0.9017
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.7624 - loss: 0.5439 - val_accuracy: 0.5261 - val_loss: 0.9263
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.7464 - loss: 0.5749 - val_accuracy: 0.7052 - val_loss: 0.6661
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.7673 - loss: 0.5616 - val_accuracy: 0.7313 - val_loss: 0.6441
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7592 - loss: 0.5501 - val_accuracy: 0.7836 - val_loss: 0.4934
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7352 - loss: 0.6103 - val_accuracy: 0.7948 - val_loss: 0.5421
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.7432 - loss: 0.5729 - val_accuracy: 0.7761 - val_loss: 0.4882
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7721 - loss: 0.5299 - val_accuracy: 0.7575 - val_loss: 0.4896
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7689 - loss: 0.5595 - val_accuracy: 0.5149 - val_loss: 1.0226
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7705 - loss: 0.5804 - val_accuracy: 0.7761 - val_loss: 0.5076
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7881 - loss: 0.5189 - val_accuracy: 0.7836 - val_loss: 0.5076
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7769 - loss: 0.5675 - val_accuracy: 0.7873 - val_loss: 0.5692
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.7833 - loss: 0.5185 - val_accuracy: 0.7799 - val_loss: 0.5574
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7480 - loss: 0.5931 - val_accuracy: 0.7500 - val_loss: 0.5321
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7785 - loss: 0.5649 - val_accuracy: 0.7612 - val_loss: 0.4904
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7673 - loss: 0.5535 - val_accuracy: 0.7761 - val_loss: 0.4990
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7769 - loss: 0.5368 - val_accuracy: 0.7799 - val_loss: 0.4950
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7432 - loss: 0.5897 - val_accuracy: 0.7052 - val_loss: 0.8932
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.7528 - loss: 0.5727 - val_accuracy: 0.7500 - val_loss: 0.5971
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7480 - loss: 0.5854 - val_accuracy: 0.7649 - val_loss: 0.5764
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7384 - loss: 0.5680 - val_accuracy: 0.7575 - val_loss: 0.5879
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - accuracy: 0.7624 - loss: 0.5156 - val_accuracy: 0.5634 - val_loss: 0.8732
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.7673 - loss: 0.5464 - val_accuracy: 0.7761 - val_loss: 0.5075
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7721 - loss: 0.5759 - val_accuracy: 0.7687 - val_loss: 0.5099
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7769 - loss: 0.5229 - val_accuracy: 0.7724 - val_loss: 0.4968
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7544 - loss: 0.5529 - val_accuracy: 0.7052 - val_loss: 0.7837
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7528 - loss: 0.5737 - val_accuracy: 0.7649 - val_loss: 0.4835
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7881 - loss: 0.5128 - val_accuracy: 0.7724 - val_loss: 0.4938
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7769 - loss: 0.5289 - val_accuracy: 0.5858 - val_loss: 0.8779
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7640 - loss: 0.5522 - val_accuracy: 0.6828 - val_loss: 0.8608
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.7865 - loss: 0.5334 - val_accuracy: 0.7687 - val_loss: 0.4835
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7817 - loss: 0.5503 - val_accuracy: 0.7201 - val_loss: 0.6885
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7689 - loss: 0.5601 - val_accuracy: 0.7761 - val_loss: 0.4893
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.7849 - loss: 0.5173 - val_accuracy: 0.7836 - val_loss: 0.5130
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7705 - loss: 0.5550 - val_accuracy: 0.7649 - val_loss: 0.5375
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7608 - loss: 0.5342 - val_accuracy: 0.7500 - val_loss: 0.6543
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7881 - loss: 0.5131 - val_accuracy: 0.7575 - val_loss: 0.5889
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7624 - loss: 0.5361 - val_accuracy: 0.7463 - val_loss: 0.6631
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7673 - loss: 0.5498 - val_accuracy: 0.7724 - val_loss: 0.4863
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step - accuracy: 0.7913 - loss: 0.5038 - val_accuracy: 0.7761 - val_loss: 0.5084
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7849 - loss: 0.5416 - val_accuracy: 0.7649 - val_loss: 0.5896
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.7576 - loss: 0.5805 - val_accuracy: 0.7724 - val_loss: 0.4824
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.7673 - loss: 0.5361 - val_accuracy: 0.7537 - val_loss: 0.5792
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.7512 - loss: 0.5509 - val_accuracy: 0.7575 - val_loss: 0.6797
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7978 - loss: 0.5315 - val_accuracy: 0.6418 - val_loss: 0.7025
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7576 - loss: 0.5306 - val_accuracy: 0.7985 - val_loss: 0.5196
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7673 - loss: 0.5486 - val_accuracy: 0.7687 - val_loss: 0.5003
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7592 - loss: 0.5483 - val_accuracy: 0.6082 - val_loss: 0.8207
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7753 - loss: 0.5294 - val_accuracy: 0.7799 - val_loss: 0.5425
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7785 - loss: 0.5429 - val_accuracy: 0.7649 - val_loss: 0.4935
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7817 - loss: 0.5287 - val_accuracy: 0.5112 - val_loss: 1.1325
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.7657 - loss: 0.5302 - val_accuracy: 0.7724 - val_loss: 0.5663
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.7801 - loss: 0.5047 - val_accuracy: 0.7463 - val_loss: 0.6811
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7673 - loss: 0.5689 - val_accuracy: 0.7910 - val_loss: 0.5081
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7817 - loss: 0.4956 - val_accuracy: 0.7724 - val_loss: 0.6296
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.7640 - loss: 0.5381 - val_accuracy: 0.7873 - val_loss: 0.5481
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7657 - loss: 0.5346 - val_accuracy: 0.7649 - val_loss: 0.5481
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5445 - val_accuracy: 0.7612 - val_loss: 0.5983
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7544 - loss: 0.5498 - val_accuracy: 0.7873 - val_loss: 0.5122
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.7753 - loss: 0.5009 - val_accuracy: 0.7873 - val_loss: 0.4861
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7705 - loss: 0.5260 - val_accuracy: 0.7948 - val_loss: 0.4969
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.7801 - loss: 0.5156 - val_accuracy: 0.7687 - val_loss: 0.4916
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7560 - loss: 0.5377 - val_accuracy: 0.7612 - val_loss: 0.5921
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7705 - loss: 0.5381 - val_accuracy: 0.7799 - val_loss: 0.6082
Epoch 153/5000

wandb: Agent Starting Run: 7jpee644 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5345 - loss: 12.3597 - val_accuracy: 0.6866 - val_loss: 1.8301
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.6340 - loss: 2.6251 - val_accuracy: 0.6828 - val_loss: 1.4346
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6469 - loss: 1.4550 - val_accuracy: 0.6828 - val_loss: 1.0443
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6517 - loss: 0.9379 - val_accuracy: 0.6903 - val_loss: 0.8262
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.6388 - loss: 0.8612 - val_accuracy: 0.7090 - val_loss: 0.7686
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6324 - loss: 0.8265 - val_accuracy: 0.6866 - val_loss: 0.9946
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.6549 - loss: 0.7005 - val_accuracy: 0.7052 - val_loss: 0.7042
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6437 - loss: 0.9171 - val_accuracy: 0.7127 - val_loss: 0.6817
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6790 - loss: 0.6919 - val_accuracy: 0.6418 - val_loss: 0.8375
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.6244 - loss: 1.0346 - val_accuracy: 0.7276 - val_loss: 0.6618
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.6806 - loss: 0.7024 - val_accuracy: 0.7015 - val_loss: 0.7136
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6998 - loss: 0.6598 - val_accuracy: 0.6679 - val_loss: 0.7777
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.7159 - loss: 0.6212 - val_accuracy: 0.7276 - val_loss: 0.5938
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6549 - loss: 0.8848 - val_accuracy: 0.7090 - val_loss: 0.8252
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.6869 - val_accuracy: 0.6157 - val_loss: 0.7424
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.7194 - val_accuracy: 0.7537 - val_loss: 0.5517
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.7319 - loss: 0.5514 - val_accuracy: 0.7649 - val_loss: 0.5408
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.7576 - loss: 0.5450 - val_accuracy: 0.6754 - val_loss: 0.6676
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7111 - loss: 0.5839 - val_accuracy: 0.7537 - val_loss: 0.5447
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.7030 - loss: 0.6796 - val_accuracy: 0.7201 - val_loss: 0.6827
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7111 - loss: 0.6343 - val_accuracy: 0.7537 - val_loss: 0.6132
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7271 - loss: 0.6088 - val_accuracy: 0.7575 - val_loss: 0.6007
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7223 - loss: 0.6460 - val_accuracy: 0.7127 - val_loss: 0.6715
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7368 - loss: 0.5972 - val_accuracy: 0.6231 - val_loss: 0.9006
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7448 - loss: 0.5877 - val_accuracy: 0.7724 - val_loss: 0.5294
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7448 - loss: 0.5918 - val_accuracy: 0.6791 - val_loss: 0.6936
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7640 - loss: 0.5491 - val_accuracy: 0.7724 - val_loss: 0.5154
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7528 - loss: 0.5271 - val_accuracy: 0.7388 - val_loss: 0.5790
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7817 - loss: 0.5105 - val_accuracy: 0.7761 - val_loss: 0.5087
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.7384 - loss: 0.5767 - val_accuracy: 0.7351 - val_loss: 0.5454
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.7753 - loss: 0.5055 - val_accuracy: 0.7761 - val_loss: 0.5445
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7689 - loss: 0.5197 - val_accuracy: 0.7687 - val_loss: 0.5326
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7624 - loss: 0.5352 - val_accuracy: 0.7687 - val_loss: 0.5757
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7592 - loss: 0.5406 - val_accuracy: 0.7575 - val_loss: 0.5284
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.7640 - loss: 0.5270 - val_accuracy: 0.7724 - val_loss: 0.5237
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7271 - loss: 0.6381 - val_accuracy: 0.7724 - val_loss: 0.5150
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7207 - loss: 0.6666 - val_accuracy: 0.7575 - val_loss: 0.5897
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6806 - loss: 0.9182 - val_accuracy: 0.6716 - val_loss: 1.5477
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6934 - loss: 0.8843 - val_accuracy: 0.7910 - val_loss: 0.5747
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7560 - loss: 0.6416 - val_accuracy: 0.7537 - val_loss: 0.5161
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.7849 - loss: 0.5285 - val_accuracy: 0.7687 - val_loss: 0.5247
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7865 - loss: 0.5011 - val_accuracy: 0.7127 - val_loss: 0.7877
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7640 - loss: 0.5684 - val_accuracy: 0.5784 - val_loss: 0.9020
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7384 - loss: 0.6642 - val_accuracy: 0.7649 - val_loss: 0.5087
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7207 - loss: 0.7216 - val_accuracy: 0.7687 - val_loss: 0.5125
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7384 - loss: 0.6708 - val_accuracy: 0.7537 - val_loss: 0.5652
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7673 - loss: 0.5540 - val_accuracy: 0.7799 - val_loss: 0.5327
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7432 - loss: 0.6567 - val_accuracy: 0.7351 - val_loss: 0.7278
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7528 - loss: 0.6045 - val_accuracy: 0.6828 - val_loss: 0.8471
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7480 - loss: 0.6009 - val_accuracy: 0.7575 - val_loss: 0.5469
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7657 - loss: 0.5156 - val_accuracy: 0.7649 - val_loss: 0.5140
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7945 - loss: 0.5028 - val_accuracy: 0.7836 - val_loss: 0.5418
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7865 - loss: 0.5139 - val_accuracy: 0.7612 - val_loss: 0.5083
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7994 - loss: 0.4769 - val_accuracy: 0.7239 - val_loss: 0.6149
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7576 - loss: 0.6426 - val_accuracy: 0.7649 - val_loss: 0.5080
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7961 - loss: 0.4760 - val_accuracy: 0.7873 - val_loss: 0.5545
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7592 - loss: 0.5494 - val_accuracy: 0.7612 - val_loss: 0.5526
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7560 - loss: 0.5507 - val_accuracy: 0.7612 - val_loss: 0.5308
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7689 - loss: 0.5175 - val_accuracy: 0.7761 - val_loss: 0.5336
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7849 - loss: 0.5176 - val_accuracy: 0.7724 - val_loss: 0.5983
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7801 - loss: 0.5174 - val_accuracy: 0.7687 - val_loss: 0.5287
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7881 - loss: 0.4883 - val_accuracy: 0.7724 - val_loss: 0.5049
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.7801 - loss: 0.5274 - val_accuracy: 0.7799 - val_loss: 0.5218
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.7207 - loss: 0.6508 - val_accuracy: 0.7351 - val_loss: 0.6726
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7657 - loss: 0.5575 - val_accuracy: 0.7836 - val_loss: 0.5344
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7721 - loss: 0.5487 - val_accuracy: 0.7052 - val_loss: 0.7123
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7689 - loss: 0.5261 - val_accuracy: 0.7724 - val_loss: 0.5078
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7737 - loss: 0.5589 - val_accuracy: 0.7761 - val_loss: 0.5191
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7560 - loss: 0.5977 - val_accuracy: 0.7612 - val_loss: 0.5408
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7464 - loss: 0.5819 - val_accuracy: 0.7612 - val_loss: 0.5065
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7817 - loss: 0.5175 - val_accuracy: 0.7724 - val_loss: 0.5463
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7624 - loss: 0.6064 - val_accuracy: 0.7351 - val_loss: 0.6719
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7496 - loss: 0.6060 - val_accuracy: 0.7575 - val_loss: 0.5332
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7849 - loss: 0.5148 - val_accuracy: 0.7724 - val_loss: 0.5308
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.7657 - loss: 0.5450 - val_accuracy: 0.7313 - val_loss: 0.6745
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7480 - loss: 0.6733 - val_accuracy: 0.7649 - val_loss: 0.5034
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.8010 - loss: 0.4767 - val_accuracy: 0.7313 - val_loss: 0.6385
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7785 - loss: 0.5314 - val_accuracy: 0.7575 - val_loss: 0.5730
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7833 - loss: 0.4904 - val_accuracy: 0.7687 - val_loss: 0.5067
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7673 - loss: 0.5311 - val_accuracy: 0.7799 - val_loss: 0.5518
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 0.7624 - loss: 0.6052 - val_accuracy: 0.6866 - val_loss: 0.9765
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7624 - loss: 0.6589 - val_accuracy: 0.7649 - val_loss: 0.6306
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7881 - loss: 0.5583 - val_accuracy: 0.7351 - val_loss: 0.5978
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7640 - loss: 0.6227 - val_accuracy: 0.7612 - val_loss: 0.5082
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7994 - loss: 0.5061 - val_accuracy: 0.7799 - val_loss: 0.5910
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7560 - loss: 0.5956 - val_accuracy: 0.7724 - val_loss: 0.5299
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7640 - loss: 0.6137 - val_accuracy: 0.7500 - val_loss: 0.5363
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.7673 - loss: 0.5597 - val_accuracy: 0.7351 - val_loss: 0.7259
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7737 - loss: 0.5718 - val_accuracy: 0.7724 - val_loss: 0.5003
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7769 - loss: 0.5426 - val_accuracy: 0.6978 - val_loss: 0.9087
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7705 - loss: 0.5948 - val_accuracy: 0.7463 - val_loss: 0.5789
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7897 - loss: 0.5179 - val_accuracy: 0.7799 - val_loss: 0.5401
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7673 - loss: 0.5662 - val_accuracy: 0.6940 - val_loss: 0.8847
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7817 - loss: 0.4992 - val_accuracy: 0.7612 - val_loss: 0.5111
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7255 - loss: 0.6375 - val_accuracy: 0.7612 - val_loss: 0.5027
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7576 - loss: 0.7505 - val_accuracy: 0.6194 - val_loss: 0.8368
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7592 - loss: 0.6024 - val_accuracy: 0.7724 - val_loss: 0.5322
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.8026 - loss: 0.4897 - val_accuracy: 0.7687 - val_loss: 0.5282
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7817 - loss: 0.4854 - val_accuracy: 0.7575 - val_loss: 0.6253
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7897 - loss: 0.5110 - val_accuracy: 0.7724 - val_loss: 0.5062
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7978 - loss: 0.4974 - val_accuracy: 0.7799 - val_loss: 0.5487
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7881 - loss: 0.4648 - val_accuracy: 0.7687 - val_loss: 0.5027
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8138 - loss: 0.4685 - val_accuracy: 0.7687 - val_loss: 0.5365
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7737 - loss: 0.5612 - val_accuracy: 0.6940 - val_loss: 0.8265
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7913 - loss: 0.5480 - val_accuracy: 0.7799 - val_loss: 0.5240
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7913 - loss: 0.4892 - val_accuracy: 0.7724 - val_loss: 0.5105
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7705 - loss: 0.5549 - val_accuracy: 0.7724 - val_loss: 0.5166
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7753 - loss: 0.5278 - val_accuracy: 0.7761 - val_loss: 0.5077
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7785 - loss: 0.5231 - val_accuracy: 0.7687 - val_loss: 0.5073
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8010 - loss: 0.4990 - val_accuracy: 0.7687 - val_loss: 0.6100
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7897 - loss: 0.4838 - val_accuracy: 0.7761 - val_loss: 0.5042
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7865 - loss: 0.5184 - val_accuracy: 0.7724 - val_loss: 0.5280
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7785 - loss: 0.5430 - val_accuracy: 0.7575 - val_loss: 0.5459
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7705 - loss: 0.5485 - val_accuracy: 0.7724 - val_loss: 0.5284
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7929 - loss: 0.4895 - val_accuracy: 0.7687 - val_loss: 0.5249
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7881 - loss: 0.5114 - val_accuracy: 0.7761 - val_loss: 0.5905
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7512 - loss: 0.6461 - val_accuracy: 0.7164 - val_loss: 0.8282
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7448 - loss: 0.6073 - val_accuracy: 0.7537 - val_loss: 0.5729
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7785 - loss: 0.5779 - val_accuracy: 0.7687 - val_loss: 0.5181
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8026 - loss: 0.4914 - val_accuracy: 0.7836 - val_loss: 0.5588
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.8010 - loss: 0.4917 - val_accuracy: 0.6866 - val_loss: 0.7170
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7817 - loss: 0.5407 - val_accuracy: 0.7687 - val_loss: 0.4937
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7929 - loss: 0.4882 - val_accuracy: 0.7612 - val_loss: 0.5279
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7817 - loss: 0.5561 - val_accuracy: 0.7463 - val_loss: 0.5689
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7769 - loss: 0.5222 - val_accuracy: 0.7724 - val_loss: 0.4961
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.7849 - loss: 0.5363 - val_accuracy: 0.7463 - val_loss: 0.6782
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7849 - loss: 0.5329 - val_accuracy: 0.7724 - val_loss: 0.4986
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7817 - loss: 0.4898 - val_accuracy: 0.7687 - val_loss: 0.5199
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7881 - loss: 0.5040 - val_accuracy: 0.7537 - val_loss: 0.6192
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7512 - loss: 0.5134 - val_accuracy: 0.7463 - val_loss: 0.5880
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7721 - loss: 0.5449 - val_accuracy: 0.7425 - val_loss: 0.5725
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7512 - loss: 0.6305 - val_accuracy: 0.6903 - val_loss: 0.8513
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7608 - loss: 0.5648 - val_accuracy: 0.7724 - val_loss: 0.5016
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.7913 - loss: 0.4788 - val_accuracy: 0.6903 - val_loss: 0.6863
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7833 - loss: 0.5026 - val_accuracy: 0.6828 - val_loss: 0.7231
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7801 - loss: 0.5202 - val_accuracy: 0.7761 - val_loss: 0.5906
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7785 - loss: 0.5298 - val_accuracy: 0.7687 - val_loss: 0.4920
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 0.7801 - loss: 0.5062 - val_accuracy: 0.7276 - val_loss: 0.7593
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7785 - loss: 0.5545 - val_accuracy: 0.7724 - val_loss: 0.4958
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7624 - loss: 0.5761 - val_accuracy: 0.7463 - val_loss: 0.5892
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7978 - loss: 0.4730 - val_accuracy: 0.7724 - val_loss: 0.4948
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7769 - loss: 0.5662 - val_accuracy: 0.7612 - val_loss: 0.6050
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.8058 - loss: 0.4810 - val_accuracy: 0.7761 - val_loss: 0.5360
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7624 - loss: 0.5839 - val_accuracy: 0.7799 - val_loss: 0.5946
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7705 - loss: 0.6002 - val_accuracy: 0.7761 - val_loss: 0.5499
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.7592 - loss: 0.5880 - val_accuracy: 0.7127 - val_loss: 0.8090
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7335 - loss: 0.6424 - val_accuracy: 0.7500 - val_loss: 0.5681
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7978 - loss: 0.4767 - val_accuracy: 0.7724 - val_loss: 0.5194
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7865 - loss: 0.5083 - val_accuracy: 0.7649 - val_loss: 0.4975
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.8058 - loss: 0.4881 - val_accuracy: 0.5709 - val_loss: 0.9119
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7673 - loss: 0.5515 - val_accuracy: 0.7799 - val_loss: 0.5741
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7785 - loss: 0.5522 - val_accuracy: 0.7649 - val_loss: 0.4982
Epoch 153/5000

wandb: Agent Starting Run: g8u55kz9 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5891 - loss: 8.7684 - val_accuracy: 0.6306 - val_loss: 0.6917
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6132 - loss: 0.6979 - val_accuracy: 0.6343 - val_loss: 0.7041
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6116 - loss: 0.6887 - val_accuracy: 0.6306 - val_loss: 0.6863
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6148 - loss: 0.6853 - val_accuracy: 0.6306 - val_loss: 0.7215
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.6116 - loss: 0.6932 - val_accuracy: 0.6343 - val_loss: 0.7044
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6866 - val_accuracy: 0.6306 - val_loss: 0.6830
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6132 - loss: 0.6729 - val_accuracy: 0.6269 - val_loss: 0.6823
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6132 - loss: 0.6712 - val_accuracy: 0.6269 - val_loss: 0.6850
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6132 - loss: 0.6695 - val_accuracy: 0.6269 - val_loss: 0.6819
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6148 - loss: 0.6686 - val_accuracy: 0.6269 - val_loss: 0.6820
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6132 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6853
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6164 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.6869
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6269 - val_loss: 0.6838
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.6164 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.6860
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.6854
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6164 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.6861
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6231 - val_loss: 0.6813
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6231 - val_loss: 0.6861
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6269 - val_loss: 0.6894
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6231 - val_loss: 0.6859
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6164 - loss: 0.6636 - val_accuracy: 0.6231 - val_loss: 0.6859
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6164 - loss: 0.6632 - val_accuracy: 0.6269 - val_loss: 0.6892
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6132 - loss: 0.6656 - val_accuracy: 0.6269 - val_loss: 0.6873
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6164 - loss: 0.6648 - val_accuracy: 0.6194 - val_loss: 0.6821
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6194 - val_loss: 0.6827
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6180 - loss: 0.6636 - val_accuracy: 0.6269 - val_loss: 0.6946
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.6164 - loss: 0.6630 - val_accuracy: 0.6194 - val_loss: 0.6848
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6194 - val_loss: 0.6890
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6180 - loss: 0.6626 - val_accuracy: 0.6231 - val_loss: 0.6905
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.6164 - loss: 0.6627 - val_accuracy: 0.6194 - val_loss: 0.6857
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.6180 - loss: 0.6626 - val_accuracy: 0.6194 - val_loss: 0.6831
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6180 - loss: 0.6626 - val_accuracy: 0.6194 - val_loss: 0.6839
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6231 - val_loss: 0.6871
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.7083
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6180 - loss: 0.6629 - val_accuracy: 0.6231 - val_loss: 0.7040
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6231 - val_loss: 0.7020
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6231 - val_loss: 0.7008
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.6180 - loss: 0.6622 - val_accuracy: 0.6231 - val_loss: 0.7023
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6231 - val_loss: 0.6996
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6231 - val_loss: 0.6979
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6231 - val_loss: 0.6997
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6231 - val_loss: 0.7004
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6991
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6977
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6180 - loss: 0.6614 - val_accuracy: 0.6231 - val_loss: 0.6979
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6180 - loss: 0.6614 - val_accuracy: 0.6231 - val_loss: 0.6994
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6231 - val_loss: 0.7004
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6194 - val_loss: 0.7026
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6231 - val_loss: 0.7001
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6180 - loss: 0.6611 - val_accuracy: 0.6194 - val_loss: 0.7033
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6180 - loss: 0.6610 - val_accuracy: 0.6194 - val_loss: 0.7026
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6180 - loss: 0.6608 - val_accuracy: 0.6194 - val_loss: 0.7038
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6180 - loss: 0.6610 - val_accuracy: 0.6231 - val_loss: 0.7022
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6180 - loss: 0.6609 - val_accuracy: 0.6231 - val_loss: 0.7025
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.6180 - loss: 0.6608 - val_accuracy: 0.6231 - val_loss: 0.7000
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6180 - loss: 0.6606 - val_accuracy: 0.6194 - val_loss: 0.7024
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6196 - loss: 0.6607 - val_accuracy: 0.6194 - val_loss: 0.7034
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6180 - loss: 0.6608 - val_accuracy: 0.6194 - val_loss: 0.7021
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6180 - loss: 0.6604 - val_accuracy: 0.6194 - val_loss: 0.7012
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.6180 - loss: 0.6605 - val_accuracy: 0.6231 - val_loss: 0.7017
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6180 - loss: 0.6603 - val_accuracy: 0.6231 - val_loss: 0.7014
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6180 - loss: 0.6602 - val_accuracy: 0.6194 - val_loss: 0.7035
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6601 - val_accuracy: 0.6194 - val_loss: 0.7049
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.6180 - loss: 0.6600 - val_accuracy: 0.6231 - val_loss: 0.7034
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.6180 - loss: 0.6603 - val_accuracy: 0.6231 - val_loss: 0.7024
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6196 - loss: 0.6601 - val_accuracy: 0.6194 - val_loss: 0.7053
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6196 - loss: 0.6596 - val_accuracy: 0.6194 - val_loss: 0.7068
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.6196 - loss: 0.6601 - val_accuracy: 0.6194 - val_loss: 0.7051
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6228 - loss: 0.6597 - val_accuracy: 0.6231 - val_loss: 0.7058
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.6196 - loss: 0.6596 - val_accuracy: 0.6231 - val_loss: 0.7037
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6212 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7074
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.6244 - loss: 0.6593 - val_accuracy: 0.6194 - val_loss: 0.7071
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6228 - loss: 0.6594 - val_accuracy: 0.6157 - val_loss: 0.7063
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6228 - loss: 0.6595 - val_accuracy: 0.6157 - val_loss: 0.7079
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.6196 - loss: 0.6592 - val_accuracy: 0.6157 - val_loss: 0.7075
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6212 - loss: 0.6592 - val_accuracy: 0.6194 - val_loss: 0.7063
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6228 - loss: 0.6589 - val_accuracy: 0.6194 - val_loss: 0.7063
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.6228 - loss: 0.6591 - val_accuracy: 0.6194 - val_loss: 0.7080
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6244 - loss: 0.6587 - val_accuracy: 0.6157 - val_loss: 0.7072
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6212 - loss: 0.6584 - val_accuracy: 0.6119 - val_loss: 0.7113
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6212 - loss: 0.6588 - val_accuracy: 0.6157 - val_loss: 0.7087
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6212 - loss: 0.6589 - val_accuracy: 0.6157 - val_loss: 0.7067
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.6260 - loss: 0.6607 - val_accuracy: 0.6082 - val_loss: 0.7079
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6260 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.6990
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6308 - loss: 0.6590 - val_accuracy: 0.6194 - val_loss: 0.6996
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6340 - loss: 0.6579 - val_accuracy: 0.6194 - val_loss: 0.6977
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6292 - loss: 0.6572 - val_accuracy: 0.6157 - val_loss: 0.7044
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6308 - loss: 0.6573 - val_accuracy: 0.6157 - val_loss: 0.7036
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6308 - loss: 0.6564 - val_accuracy: 0.6157 - val_loss: 0.7035
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6324 - loss: 0.6565 - val_accuracy: 0.6157 - val_loss: 0.7025
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6308 - loss: 0.6560 - val_accuracy: 0.6157 - val_loss: 0.7012
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6308 - loss: 0.6560 - val_accuracy: 0.6157 - val_loss: 0.7025
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.6324 - loss: 0.6552 - val_accuracy: 0.6157 - val_loss: 0.6970
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.6308 - loss: 0.6561 - val_accuracy: 0.6157 - val_loss: 0.6971
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6308 - loss: 0.6548 - val_accuracy: 0.6157 - val_loss: 0.7002
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.6292 - loss: 0.6552 - val_accuracy: 0.6157 - val_loss: 0.6924
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6308 - loss: 0.6550 - val_accuracy: 0.6157 - val_loss: 0.6999
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6553 - val_accuracy: 0.6157 - val_loss: 0.6998
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6308 - loss: 0.6547 - val_accuracy: 0.6157 - val_loss: 0.7001
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.6540 - val_accuracy: 0.6194 - val_loss: 0.6947
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6292 - loss: 0.6545 - val_accuracy: 0.6194 - val_loss: 0.7063
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6308 - loss: 0.6536 - val_accuracy: 0.6157 - val_loss: 0.7064
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6308 - loss: 0.6545 - val_accuracy: 0.6157 - val_loss: 0.7069
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6292 - loss: 0.6532 - val_accuracy: 0.6157 - val_loss: 0.7044
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.6308 - loss: 0.6532 - val_accuracy: 0.6157 - val_loss: 0.7045
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.6324 - loss: 0.6532 - val_accuracy: 0.6157 - val_loss: 0.7128
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6308 - loss: 0.6531 - val_accuracy: 0.6119 - val_loss: 0.7134
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 0.6324 - loss: 0.6539 - val_accuracy: 0.6157 - val_loss: 0.7118
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - accuracy: 0.6308 - loss: 0.6529 - val_accuracy: 0.6157 - val_loss: 0.7092
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6308 - loss: 0.6530 - val_accuracy: 0.6157 - val_loss: 0.7129
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6324 - loss: 0.6532 - val_accuracy: 0.6157 - val_loss: 0.7258
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6324 - loss: 0.6527 - val_accuracy: 0.6157 - val_loss: 0.7171
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6308 - loss: 0.6528 - val_accuracy: 0.6157 - val_loss: 0.7195
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6308 - loss: 0.6527 - val_accuracy: 0.6157 - val_loss: 0.7210
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6324 - loss: 0.6524 - val_accuracy: 0.6157 - val_loss: 0.7138
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6340 - loss: 0.6526 - val_accuracy: 0.6194 - val_loss: 0.7205
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6324 - loss: 0.6524 - val_accuracy: 0.6194 - val_loss: 0.7195
Epoch 117: early stopping

wandb: Agent Starting Run: 2ukqr920 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 1.4077 - val_accuracy: 0.5299 - val_loss: 1.0442
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5987 - loss: 1.0971 - val_accuracy: 0.6679 - val_loss: 1.1903
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.8829 - val_accuracy: 0.6754 - val_loss: 0.7248
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6051 - loss: 0.9043 - val_accuracy: 0.4963 - val_loss: 0.8990
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.8567 - val_accuracy: 0.4590 - val_loss: 1.2034
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.6003 - loss: 0.8985 - val_accuracy: 0.5858 - val_loss: 0.7657
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6469 - loss: 0.8330 - val_accuracy: 0.6791 - val_loss: 0.6699
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.6404 - loss: 0.7943 - val_accuracy: 0.7015 - val_loss: 0.6282
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.6356 - loss: 0.7826 - val_accuracy: 0.6679 - val_loss: 0.7321
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.6421 - loss: 0.7851 - val_accuracy: 0.6567 - val_loss: 0.7247
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6613 - loss: 0.7780 - val_accuracy: 0.6828 - val_loss: 0.7757
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.7437 - val_accuracy: 0.4515 - val_loss: 1.1561
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6645 - loss: 0.7457 - val_accuracy: 0.7015 - val_loss: 0.6493
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6806 - loss: 0.7505 - val_accuracy: 0.7351 - val_loss: 0.6861
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6661 - loss: 0.6999 - val_accuracy: 0.6940 - val_loss: 0.7030
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6726 - loss: 0.7150 - val_accuracy: 0.6791 - val_loss: 0.6962
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6565 - loss: 0.7721 - val_accuracy: 0.7164 - val_loss: 0.6012
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6838 - loss: 0.6964 - val_accuracy: 0.7463 - val_loss: 0.5927
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6758 - loss: 0.6795 - val_accuracy: 0.6381 - val_loss: 1.0319
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.6774 - loss: 0.7147 - val_accuracy: 0.6716 - val_loss: 0.7051
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7047 - loss: 0.7092 - val_accuracy: 0.7649 - val_loss: 0.6096
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7303 - loss: 0.6655 - val_accuracy: 0.6604 - val_loss: 0.7513
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6838 - loss: 0.6949 - val_accuracy: 0.6978 - val_loss: 0.6889
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7014 - loss: 0.6526 - val_accuracy: 0.7201 - val_loss: 0.5970
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6950 - loss: 0.6760 - val_accuracy: 0.4813 - val_loss: 1.0541
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - accuracy: 0.7352 - loss: 0.6206 - val_accuracy: 0.6791 - val_loss: 0.7199
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.7384 - loss: 0.6001 - val_accuracy: 0.7313 - val_loss: 0.5842
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step - accuracy: 0.7319 - loss: 0.6802 - val_accuracy: 0.6306 - val_loss: 1.0611
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.7608 - loss: 0.5975 - val_accuracy: 0.6418 - val_loss: 0.8241
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6998 - loss: 0.6965 - val_accuracy: 0.7649 - val_loss: 0.5912
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.7480 - loss: 0.5892 - val_accuracy: 0.6269 - val_loss: 0.7506
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.7335 - loss: 0.6144 - val_accuracy: 0.7090 - val_loss: 0.6775
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7207 - loss: 0.6243 - val_accuracy: 0.7425 - val_loss: 0.5843
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7303 - loss: 0.6104 - val_accuracy: 0.7649 - val_loss: 0.5775
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7207 - loss: 0.6117 - val_accuracy: 0.6604 - val_loss: 0.8455
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.7207 - loss: 0.6687 - val_accuracy: 0.6903 - val_loss: 0.7981
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.7352 - loss: 0.6002 - val_accuracy: 0.7052 - val_loss: 0.7071
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 786us/step - accuracy: 0.7464 - loss: 0.6030 - val_accuracy: 0.7425 - val_loss: 0.5749
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.7335 - loss: 0.5787 - val_accuracy: 0.6754 - val_loss: 0.8604
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7384 - loss: 0.6092 - val_accuracy: 0.7761 - val_loss: 0.6013
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.6420 - val_accuracy: 0.7351 - val_loss: 0.5879
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5936 - val_accuracy: 0.7500 - val_loss: 0.6553
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7303 - loss: 0.6029 - val_accuracy: 0.7687 - val_loss: 0.5801
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7352 - loss: 0.6104 - val_accuracy: 0.6791 - val_loss: 0.7951
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7335 - loss: 0.5815 - val_accuracy: 0.7276 - val_loss: 0.6378
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7640 - loss: 0.5596 - val_accuracy: 0.6604 - val_loss: 0.9474
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7448 - loss: 0.5868 - val_accuracy: 0.7724 - val_loss: 0.6104
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7448 - loss: 0.5987 - val_accuracy: 0.7612 - val_loss: 0.6446
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7673 - loss: 0.5462 - val_accuracy: 0.7537 - val_loss: 0.6734
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7528 - loss: 0.5859 - val_accuracy: 0.7313 - val_loss: 0.6233
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7496 - loss: 0.5631 - val_accuracy: 0.7276 - val_loss: 0.6622
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.7560 - loss: 0.5636 - val_accuracy: 0.6866 - val_loss: 0.8066
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7624 - loss: 0.5675 - val_accuracy: 0.7201 - val_loss: 0.6998
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7592 - loss: 0.5587 - val_accuracy: 0.6231 - val_loss: 0.8010
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7576 - loss: 0.5682 - val_accuracy: 0.7649 - val_loss: 0.6058
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7464 - loss: 0.6141 - val_accuracy: 0.7313 - val_loss: 0.6994
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.7560 - loss: 0.6037 - val_accuracy: 0.6791 - val_loss: 0.9038
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7512 - loss: 0.5822 - val_accuracy: 0.5000 - val_loss: 1.2240
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.7624 - loss: 0.5277 - val_accuracy: 0.7239 - val_loss: 0.7176
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.6084 - val_accuracy: 0.7276 - val_loss: 0.6645
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.7705 - loss: 0.5533 - val_accuracy: 0.7276 - val_loss: 0.6846
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5557 - val_accuracy: 0.6866 - val_loss: 0.8711
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5646 - val_accuracy: 0.7575 - val_loss: 0.5867
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7496 - loss: 0.5782 - val_accuracy: 0.7500 - val_loss: 0.5849
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7721 - loss: 0.5530 - val_accuracy: 0.7500 - val_loss: 0.5711
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5845 - val_accuracy: 0.7351 - val_loss: 0.7314
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7544 - loss: 0.5523 - val_accuracy: 0.6231 - val_loss: 0.8569
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7335 - loss: 0.6069 - val_accuracy: 0.7351 - val_loss: 0.6556
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.7705 - loss: 0.5560 - val_accuracy: 0.7575 - val_loss: 0.5702
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.7480 - loss: 0.5524 - val_accuracy: 0.7649 - val_loss: 0.6165
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7592 - loss: 0.5124 - val_accuracy: 0.7313 - val_loss: 0.7293
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7528 - loss: 0.5835 - val_accuracy: 0.6381 - val_loss: 0.7989
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7785 - loss: 0.5265 - val_accuracy: 0.6940 - val_loss: 0.8305
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7624 - loss: 0.5576 - val_accuracy: 0.6791 - val_loss: 0.7720
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7464 - loss: 0.5798 - val_accuracy: 0.7649 - val_loss: 0.5836
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.7673 - loss: 0.6008 - val_accuracy: 0.7799 - val_loss: 0.5863
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.7785 - loss: 0.5036 - val_accuracy: 0.6828 - val_loss: 0.8366
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7576 - loss: 0.5757 - val_accuracy: 0.6231 - val_loss: 0.8511
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7464 - loss: 0.5593 - val_accuracy: 0.7612 - val_loss: 0.5967
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7689 - loss: 0.5267 - val_accuracy: 0.7761 - val_loss: 0.5751
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7817 - loss: 0.5242 - val_accuracy: 0.7687 - val_loss: 0.5825
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7576 - loss: 0.5781 - val_accuracy: 0.6940 - val_loss: 0.8520
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5411 - val_accuracy: 0.7537 - val_loss: 0.5882
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7592 - loss: 0.5638 - val_accuracy: 0.7351 - val_loss: 0.7031
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7785 - loss: 0.5183 - val_accuracy: 0.7388 - val_loss: 0.6479
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7881 - loss: 0.5180 - val_accuracy: 0.7687 - val_loss: 0.5749
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7865 - loss: 0.5131 - val_accuracy: 0.7388 - val_loss: 0.6758
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7817 - loss: 0.5198 - val_accuracy: 0.7127 - val_loss: 0.7870
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7801 - loss: 0.5300 - val_accuracy: 0.7500 - val_loss: 0.6518
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.7560 - loss: 0.5506 - val_accuracy: 0.7687 - val_loss: 0.5688
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.7929 - loss: 0.4914 - val_accuracy: 0.7612 - val_loss: 0.6138
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.7608 - loss: 0.5519 - val_accuracy: 0.7649 - val_loss: 0.5651
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7753 - loss: 0.5636 - val_accuracy: 0.7052 - val_loss: 0.8177
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7673 - loss: 0.5264 - val_accuracy: 0.7761 - val_loss: 0.5763
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7624 - loss: 0.5439 - val_accuracy: 0.7537 - val_loss: 0.6714
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7657 - loss: 0.5260 - val_accuracy: 0.6754 - val_loss: 0.7817
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7657 - loss: 0.5464 - val_accuracy: 0.7799 - val_loss: 0.5966
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7897 - loss: 0.4951 - val_accuracy: 0.7425 - val_loss: 0.6595
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7929 - loss: 0.5131 - val_accuracy: 0.7836 - val_loss: 0.6141
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7737 - loss: 0.5361 - val_accuracy: 0.6493 - val_loss: 0.8014
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.7576 - loss: 0.5249 - val_accuracy: 0.7649 - val_loss: 0.5830
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5910 - val_accuracy: 0.7313 - val_loss: 0.7635
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7689 - loss: 0.5088 - val_accuracy: 0.6493 - val_loss: 0.8139
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5313 - val_accuracy: 0.7575 - val_loss: 0.6224
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7753 - loss: 0.5345 - val_accuracy: 0.7649 - val_loss: 0.5819
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7945 - loss: 0.4773 - val_accuracy: 0.7575 - val_loss: 0.5843
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7721 - loss: 0.5479 - val_accuracy: 0.7612 - val_loss: 0.5748
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7817 - loss: 0.5030 - val_accuracy: 0.7724 - val_loss: 0.5889
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7865 - loss: 0.5296 - val_accuracy: 0.7425 - val_loss: 0.6568
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7673 - loss: 0.5169 - val_accuracy: 0.7687 - val_loss: 0.5765
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7721 - loss: 0.5428 - val_accuracy: 0.7687 - val_loss: 0.5996
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7849 - loss: 0.5173 - val_accuracy: 0.7799 - val_loss: 0.5757
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7833 - loss: 0.5421 - val_accuracy: 0.7836 - val_loss: 0.5974
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7640 - loss: 0.5224 - val_accuracy: 0.7500 - val_loss: 0.6439
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7785 - loss: 0.5397 - val_accuracy: 0.7761 - val_loss: 0.6446
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5293 - val_accuracy: 0.7724 - val_loss: 0.6062
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5292 - val_accuracy: 0.7724 - val_loss: 0.5774
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.7657 - loss: 0.5017 - val_accuracy: 0.7799 - val_loss: 0.6343
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7689 - loss: 0.5256 - val_accuracy: 0.7649 - val_loss: 0.6406
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7849 - loss: 0.5123 - val_accuracy: 0.6903 - val_loss: 0.9537
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7753 - loss: 0.5334 - val_accuracy: 0.7575 - val_loss: 0.6111
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7785 - loss: 0.5231 - val_accuracy: 0.7687 - val_loss: 0.5802
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7913 - loss: 0.4874 - val_accuracy: 0.7537 - val_loss: 0.6962
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7592 - loss: 0.5615 - val_accuracy: 0.7201 - val_loss: 0.7713
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7833 - loss: 0.4900 - val_accuracy: 0.7687 - val_loss: 0.5786
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7913 - loss: 0.4773 - val_accuracy: 0.7799 - val_loss: 0.6304
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7753 - loss: 0.5203 - val_accuracy: 0.7836 - val_loss: 0.5799
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7961 - loss: 0.4783 - val_accuracy: 0.7351 - val_loss: 0.6951
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7945 - loss: 0.5077 - val_accuracy: 0.7612 - val_loss: 0.6532
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.8010 - loss: 0.4957 - val_accuracy: 0.7873 - val_loss: 0.5862
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5150 - val_accuracy: 0.7537 - val_loss: 0.6167
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.8026 - loss: 0.4689 - val_accuracy: 0.7948 - val_loss: 0.6052
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.7833 - loss: 0.5262 - val_accuracy: 0.7351 - val_loss: 0.6951
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7769 - loss: 0.5189 - val_accuracy: 0.7724 - val_loss: 0.5966
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7769 - loss: 0.5377 - val_accuracy: 0.7313 - val_loss: 0.7491
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7769 - loss: 0.5070 - val_accuracy: 0.7500 - val_loss: 0.6783
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7464 - loss: 0.5293 - val_accuracy: 0.7724 - val_loss: 0.5804
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7881 - loss: 0.4773 - val_accuracy: 0.7500 - val_loss: 0.6228
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4684 - val_accuracy: 0.7836 - val_loss: 0.6120
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7929 - loss: 0.4981 - val_accuracy: 0.7612 - val_loss: 0.5909
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.8042 - loss: 0.4833 - val_accuracy: 0.7575 - val_loss: 0.5745
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7785 - loss: 0.5353 - val_accuracy: 0.7425 - val_loss: 0.6677
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4905 - val_accuracy: 0.7799 - val_loss: 0.6173
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.7913 - loss: 0.4892 - val_accuracy: 0.7687 - val_loss: 0.5790
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7865 - loss: 0.4838 - val_accuracy: 0.7873 - val_loss: 0.6174
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7705 - loss: 0.5298 - val_accuracy: 0.7649 - val_loss: 0.5927
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7961 - loss: 0.4864 - val_accuracy: 0.7649 - val_loss: 0.6075
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7817 - loss: 0.5084 - val_accuracy: 0.7799 - val_loss: 0.5931
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7705 - loss: 0.4826 - val_accuracy: 0.7612 - val_loss: 0.6577
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7849 - loss: 0.4892 - val_accuracy: 0.7425 - val_loss: 0.7144
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7994 - loss: 0.4823 - val_accuracy: 0.7724 - val_loss: 0.6063
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7881 - loss: 0.4892 - val_accuracy: 0.7649 - val_loss: 0.6279
Epoch 153/5000

wandb: Agent Starting Run: k1lkbss0 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4960 - loss: 2.7500 - val_accuracy: 0.4403 - val_loss: 1.8941
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5650 - loss: 1.1696 - val_accuracy: 0.6679 - val_loss: 0.8381
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 0.8231 - val_accuracy: 0.6306 - val_loss: 0.8160
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6404 - loss: 0.7843 - val_accuracy: 0.6978 - val_loss: 0.6533
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6549 - loss: 0.6683 - val_accuracy: 0.7015 - val_loss: 0.6288
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.6885 - val_accuracy: 0.7276 - val_loss: 0.5939
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.6388 - loss: 0.7191 - val_accuracy: 0.7276 - val_loss: 0.5998
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.6447 - val_accuracy: 0.7090 - val_loss: 0.6810
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.6651 - val_accuracy: 0.6978 - val_loss: 0.6134
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.5815 - val_accuracy: 0.7127 - val_loss: 0.5825
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.5657 - val_accuracy: 0.7239 - val_loss: 0.5474
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.7143 - loss: 0.5859 - val_accuracy: 0.7351 - val_loss: 0.5432
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.6726 - loss: 0.6176 - val_accuracy: 0.6978 - val_loss: 0.6181
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.5773 - val_accuracy: 0.7201 - val_loss: 0.5297
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.6357 - val_accuracy: 0.7910 - val_loss: 0.5765
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.6790 - loss: 0.6237 - val_accuracy: 0.7612 - val_loss: 0.5291
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.7095 - loss: 0.5649 - val_accuracy: 0.7575 - val_loss: 0.5166
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.7239 - loss: 0.5455 - val_accuracy: 0.7239 - val_loss: 0.5838
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.7416 - loss: 0.5159 - val_accuracy: 0.7948 - val_loss: 0.5618
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7496 - loss: 0.5201 - val_accuracy: 0.7127 - val_loss: 0.5725
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7448 - loss: 0.5256 - val_accuracy: 0.7985 - val_loss: 0.5313
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7416 - loss: 0.5329 - val_accuracy: 0.6754 - val_loss: 0.6486
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7448 - loss: 0.5672 - val_accuracy: 0.7799 - val_loss: 0.4988
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7624 - loss: 0.5341 - val_accuracy: 0.7500 - val_loss: 0.5063
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7689 - loss: 0.5048 - val_accuracy: 0.7799 - val_loss: 0.5036
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7528 - loss: 0.5571 - val_accuracy: 0.7575 - val_loss: 0.5136
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7737 - loss: 0.5168 - val_accuracy: 0.7612 - val_loss: 0.5978
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7657 - loss: 0.5250 - val_accuracy: 0.8022 - val_loss: 0.5210
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7560 - loss: 0.5097 - val_accuracy: 0.7351 - val_loss: 0.5201
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7657 - loss: 0.5015 - val_accuracy: 0.7127 - val_loss: 0.5953
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7865 - loss: 0.4916 - val_accuracy: 0.7276 - val_loss: 0.5996
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7368 - loss: 0.5780 - val_accuracy: 0.7985 - val_loss: 0.5141
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.7464 - loss: 0.5943 - val_accuracy: 0.5746 - val_loss: 0.8560
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.7657 - loss: 0.5125 - val_accuracy: 0.7873 - val_loss: 0.4960
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7432 - loss: 0.5514 - val_accuracy: 0.7910 - val_loss: 0.5027
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7640 - loss: 0.5352 - val_accuracy: 0.7799 - val_loss: 0.5081
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7881 - loss: 0.4833 - val_accuracy: 0.5410 - val_loss: 0.9983
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7576 - loss: 0.5319 - val_accuracy: 0.7724 - val_loss: 0.4926
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.8042 - loss: 0.4782 - val_accuracy: 0.7649 - val_loss: 0.5005
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7961 - loss: 0.4695 - val_accuracy: 0.7836 - val_loss: 0.5030
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.7785 - loss: 0.5058 - val_accuracy: 0.7388 - val_loss: 0.5655
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7817 - loss: 0.4893 - val_accuracy: 0.7836 - val_loss: 0.5037
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7817 - loss: 0.4875 - val_accuracy: 0.7313 - val_loss: 0.5615
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7913 - loss: 0.4939 - val_accuracy: 0.7873 - val_loss: 0.4928
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.8106 - loss: 0.4552 - val_accuracy: 0.7761 - val_loss: 0.5568
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7705 - loss: 0.5292 - val_accuracy: 0.7575 - val_loss: 0.5332
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4559 - val_accuracy: 0.7612 - val_loss: 0.5147
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4884 - val_accuracy: 0.7873 - val_loss: 0.4930
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7592 - loss: 0.5389 - val_accuracy: 0.7612 - val_loss: 0.5443
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7769 - loss: 0.4903 - val_accuracy: 0.7873 - val_loss: 0.5196
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7961 - loss: 0.4559 - val_accuracy: 0.7799 - val_loss: 0.5051
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.8106 - loss: 0.4590 - val_accuracy: 0.7836 - val_loss: 0.5226
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7994 - loss: 0.4640 - val_accuracy: 0.6530 - val_loss: 0.7323
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7817 - loss: 0.5294 - val_accuracy: 0.7799 - val_loss: 0.5032
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7994 - loss: 0.4719 - val_accuracy: 0.7649 - val_loss: 0.5012
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7994 - loss: 0.4555 - val_accuracy: 0.7948 - val_loss: 0.5041
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.8010 - loss: 0.4512 - val_accuracy: 0.7687 - val_loss: 0.5293
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7994 - loss: 0.4662 - val_accuracy: 0.7388 - val_loss: 0.6003
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7737 - loss: 0.5064 - val_accuracy: 0.7425 - val_loss: 0.5515
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7384 - loss: 0.7096 - val_accuracy: 0.7388 - val_loss: 0.6195
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.7817 - loss: 0.4748 - val_accuracy: 0.7687 - val_loss: 0.5109
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7994 - loss: 0.4688 - val_accuracy: 0.7761 - val_loss: 0.5199
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4494 - val_accuracy: 0.7649 - val_loss: 0.5328
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8010 - loss: 0.4744 - val_accuracy: 0.7612 - val_loss: 0.5283
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8074 - loss: 0.4567 - val_accuracy: 0.7687 - val_loss: 0.5119
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8106 - loss: 0.4393 - val_accuracy: 0.7799 - val_loss: 0.5399
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.8026 - loss: 0.4764 - val_accuracy: 0.7724 - val_loss: 0.5221
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7576 - loss: 0.5204 - val_accuracy: 0.7351 - val_loss: 0.6516
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7945 - loss: 0.4790 - val_accuracy: 0.7724 - val_loss: 0.5132
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.8090 - loss: 0.4509 - val_accuracy: 0.7649 - val_loss: 0.5202
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.8010 - loss: 0.4736 - val_accuracy: 0.7799 - val_loss: 0.5168
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7913 - loss: 0.4641 - val_accuracy: 0.7351 - val_loss: 0.6191
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7721 - loss: 0.5208 - val_accuracy: 0.7799 - val_loss: 0.5265
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.8058 - loss: 0.4535 - val_accuracy: 0.7761 - val_loss: 0.6089
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7978 - loss: 0.4486 - val_accuracy: 0.7687 - val_loss: 0.5190
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.8058 - loss: 0.4487 - val_accuracy: 0.7649 - val_loss: 0.5256
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7576 - loss: 0.5481 - val_accuracy: 0.7799 - val_loss: 0.5546
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7849 - loss: 0.5200 - val_accuracy: 0.7612 - val_loss: 0.6354
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.8058 - loss: 0.4709 - val_accuracy: 0.7761 - val_loss: 0.5985
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7480 - loss: 0.6386 - val_accuracy: 0.7201 - val_loss: 0.6964
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4782 - val_accuracy: 0.7799 - val_loss: 0.5664
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.8074 - loss: 0.4668 - val_accuracy: 0.7761 - val_loss: 0.5317
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.8010 - loss: 0.4382 - val_accuracy: 0.7687 - val_loss: 0.5297
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.8106 - loss: 0.4449 - val_accuracy: 0.7836 - val_loss: 0.5301
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7913 - loss: 0.4464 - val_accuracy: 0.7164 - val_loss: 0.6837
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7897 - loss: 0.5061 - val_accuracy: 0.7761 - val_loss: 0.5232
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4875 - val_accuracy: 0.7463 - val_loss: 0.6656
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7994 - loss: 0.4753 - val_accuracy: 0.7836 - val_loss: 0.5846
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7785 - loss: 0.5276 - val_accuracy: 0.7724 - val_loss: 0.5692
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7978 - loss: 0.4701 - val_accuracy: 0.7612 - val_loss: 0.5342
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.8106 - loss: 0.4651 - val_accuracy: 0.7873 - val_loss: 0.5533
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7897 - loss: 0.4781 - val_accuracy: 0.7724 - val_loss: 0.5523
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.8106 - loss: 0.4406 - val_accuracy: 0.7761 - val_loss: 0.5612
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7913 - loss: 0.4730 - val_accuracy: 0.7724 - val_loss: 0.5447
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7961 - loss: 0.4489 - val_accuracy: 0.6343 - val_loss: 0.8202
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.7961 - loss: 0.4954 - val_accuracy: 0.7761 - val_loss: 0.5405
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7929 - loss: 0.4577 - val_accuracy: 0.7575 - val_loss: 0.5760
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.8170 - loss: 0.4439 - val_accuracy: 0.7873 - val_loss: 0.5846
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.7994 - loss: 0.4427 - val_accuracy: 0.7761 - val_loss: 0.5519
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8170 - loss: 0.4301 - val_accuracy: 0.7687 - val_loss: 0.5457
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.8058 - loss: 0.4448 - val_accuracy: 0.7724 - val_loss: 0.5453
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.8010 - loss: 0.4555 - val_accuracy: 0.7761 - val_loss: 0.5754
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7961 - loss: 0.4700 - val_accuracy: 0.7761 - val_loss: 0.6370
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.8090 - loss: 0.4341 - val_accuracy: 0.7575 - val_loss: 0.5546
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.8138 - loss: 0.4345 - val_accuracy: 0.7612 - val_loss: 0.5461
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7881 - loss: 0.4606 - val_accuracy: 0.7724 - val_loss: 0.5702
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7961 - loss: 0.4583 - val_accuracy: 0.7649 - val_loss: 0.5485
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4388 - val_accuracy: 0.7687 - val_loss: 0.5649
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.8026 - loss: 0.4532 - val_accuracy: 0.7351 - val_loss: 0.6531
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.7528 - loss: 0.5433 - val_accuracy: 0.7276 - val_loss: 0.7304
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4595 - val_accuracy: 0.7761 - val_loss: 0.5625
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.7753 - loss: 0.5540 - val_accuracy: 0.7500 - val_loss: 0.6082
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.8090 - loss: 0.4559 - val_accuracy: 0.7649 - val_loss: 0.5508
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.8090 - loss: 0.4475 - val_accuracy: 0.7575 - val_loss: 0.6691
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.8026 - loss: 0.4758 - val_accuracy: 0.7537 - val_loss: 0.6672
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7961 - loss: 0.4799 - val_accuracy: 0.7724 - val_loss: 0.5702
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.8074 - loss: 0.4600 - val_accuracy: 0.7575 - val_loss: 0.5779
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.8202 - loss: 0.4278 - val_accuracy: 0.7799 - val_loss: 0.5756
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.8026 - loss: 0.4677 - val_accuracy: 0.7687 - val_loss: 0.5745
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.8106 - loss: 0.4387 - val_accuracy: 0.7687 - val_loss: 0.5616
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.8042 - loss: 0.4483 - val_accuracy: 0.7687 - val_loss: 0.5863
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.8122 - loss: 0.4411 - val_accuracy: 0.7761 - val_loss: 0.5752
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4818 - val_accuracy: 0.7687 - val_loss: 0.5928
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.7865 - loss: 0.4796 - val_accuracy: 0.7724 - val_loss: 0.5869
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5591 - val_accuracy: 0.7799 - val_loss: 0.6372
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.8074 - loss: 0.4489 - val_accuracy: 0.7724 - val_loss: 0.5890
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8122 - loss: 0.4315 - val_accuracy: 0.7649 - val_loss: 0.5725
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7978 - loss: 0.4413 - val_accuracy: 0.7575 - val_loss: 0.6124
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7929 - loss: 0.4924 - val_accuracy: 0.7724 - val_loss: 0.5850
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.8154 - loss: 0.4311 - val_accuracy: 0.7724 - val_loss: 0.5793
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.8122 - loss: 0.4269 - val_accuracy: 0.7687 - val_loss: 0.5756
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.8058 - loss: 0.4335 - val_accuracy: 0.7799 - val_loss: 0.6384
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8042 - loss: 0.4314 - val_accuracy: 0.7612 - val_loss: 0.5723
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.8058 - loss: 0.4438 - val_accuracy: 0.7724 - val_loss: 0.5938
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7496 - loss: 0.6020 - val_accuracy: 0.7575 - val_loss: 0.5924
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7785 - loss: 0.5064 - val_accuracy: 0.7687 - val_loss: 0.5665
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7978 - loss: 0.4448 - val_accuracy: 0.7724 - val_loss: 0.5890
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.8138 - loss: 0.4531 - val_accuracy: 0.7649 - val_loss: 0.5661
Epoch 138: early stopping

wandb: Agent Starting Run: jcif4nnh with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5795 - loss: 1.6582 - val_accuracy: 0.6194 - val_loss: 0.7229
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5859 - loss: 0.7127 - val_accuracy: 0.6381 - val_loss: 0.7012
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.6196 - loss: 0.6983 - val_accuracy: 0.6269 - val_loss: 0.7085
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.6148 - loss: 0.6891 - val_accuracy: 0.6306 - val_loss: 0.6907
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6196 - loss: 0.6820 - val_accuracy: 0.6231 - val_loss: 0.6967
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.6132 - loss: 0.6772 - val_accuracy: 0.6306 - val_loss: 0.6729
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6116 - loss: 0.6809 - val_accuracy: 0.6269 - val_loss: 0.6897
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6751 - val_accuracy: 0.6231 - val_loss: 0.6947
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.6180 - loss: 0.6724 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6100 - loss: 0.6722 - val_accuracy: 0.6269 - val_loss: 0.6813
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.6164 - loss: 0.6716 - val_accuracy: 0.6306 - val_loss: 0.6674
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6132 - loss: 0.6740 - val_accuracy: 0.6269 - val_loss: 0.6870
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6132 - loss: 0.6736 - val_accuracy: 0.6269 - val_loss: 0.6678
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.6180 - loss: 0.6679 - val_accuracy: 0.6231 - val_loss: 0.6868
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.6212 - loss: 0.6679 - val_accuracy: 0.6306 - val_loss: 0.6693
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.6180 - loss: 0.6680 - val_accuracy: 0.6306 - val_loss: 0.6666
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6180 - loss: 0.6713 - val_accuracy: 0.6269 - val_loss: 0.6692
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6686 - val_accuracy: 0.6306 - val_loss: 0.6659
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6687 - val_accuracy: 0.6306 - val_loss: 0.6639
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6726 - val_accuracy: 0.6269 - val_loss: 0.6693
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6164 - loss: 0.6678 - val_accuracy: 0.6306 - val_loss: 0.6908
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.6148 - loss: 0.6719 - val_accuracy: 0.6194 - val_loss: 0.6877
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6212 - loss: 0.6715 - val_accuracy: 0.6231 - val_loss: 0.6815
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6196 - loss: 0.6694 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6228 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.6650
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6132 - loss: 0.6660 - val_accuracy: 0.6269 - val_loss: 0.6675
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6212 - loss: 0.6672 - val_accuracy: 0.6269 - val_loss: 0.6882
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6244 - loss: 0.6660 - val_accuracy: 0.6343 - val_loss: 0.6655
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.6897
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6180 - loss: 0.6673 - val_accuracy: 0.6269 - val_loss: 0.6743
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6148 - loss: 0.6678 - val_accuracy: 0.6231 - val_loss: 0.6851
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6212 - loss: 0.6703 - val_accuracy: 0.6231 - val_loss: 0.6849
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6196 - loss: 0.6698 - val_accuracy: 0.6269 - val_loss: 0.6641
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6180 - loss: 0.6684 - val_accuracy: 0.6306 - val_loss: 0.6665
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6196 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.6730
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.6196 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6835
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6196 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6678
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6196 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6650
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6180 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.6691
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6228 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6753
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6244 - loss: 0.6631 - val_accuracy: 0.6306 - val_loss: 0.6648
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6180 - loss: 0.6643 - val_accuracy: 0.6343 - val_loss: 0.6851
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6212 - loss: 0.6774 - val_accuracy: 0.6157 - val_loss: 0.6728
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6180 - loss: 0.6687 - val_accuracy: 0.6231 - val_loss: 0.6776
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6132 - loss: 0.6676 - val_accuracy: 0.6306 - val_loss: 0.6875
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.6164 - loss: 0.6669 - val_accuracy: 0.6194 - val_loss: 0.6692
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6676 - val_accuracy: 0.6231 - val_loss: 0.6666
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6196 - loss: 0.6669 - val_accuracy: 0.6269 - val_loss: 0.6856
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6180 - loss: 0.6654 - val_accuracy: 0.6194 - val_loss: 0.6691
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6180 - loss: 0.6662 - val_accuracy: 0.6231 - val_loss: 0.6766
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6180 - loss: 0.6651 - val_accuracy: 0.6194 - val_loss: 0.6686
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6164 - loss: 0.6652 - val_accuracy: 0.6231 - val_loss: 0.6829
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6196 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6767
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6180 - loss: 0.6656 - val_accuracy: 0.6269 - val_loss: 0.6785
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6231 - val_loss: 0.6680
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6164 - loss: 0.6672 - val_accuracy: 0.6231 - val_loss: 0.6674
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6180 - loss: 0.6635 - val_accuracy: 0.6343 - val_loss: 0.6945
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6180 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6696
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6194 - val_loss: 0.6735
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6212 - loss: 0.6655 - val_accuracy: 0.6269 - val_loss: 0.6772
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6164 - loss: 0.6648 - val_accuracy: 0.6194 - val_loss: 0.6724
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6180 - loss: 0.6660 - val_accuracy: 0.6231 - val_loss: 0.6760
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.6212 - loss: 0.6650 - val_accuracy: 0.6231 - val_loss: 0.6696
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.6196 - loss: 0.6675 - val_accuracy: 0.6194 - val_loss: 0.6697
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6212 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.6799
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6196 - loss: 0.6649 - val_accuracy: 0.6231 - val_loss: 0.6685
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6869
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.6132 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.6772
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6212 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.6679
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6196 - loss: 0.6656 - val_accuracy: 0.6194 - val_loss: 0.6726
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6180 - loss: 0.6646 - val_accuracy: 0.6194 - val_loss: 0.6755
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6196 - loss: 0.6662 - val_accuracy: 0.6194 - val_loss: 0.6737
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6180 - loss: 0.6656 - val_accuracy: 0.6194 - val_loss: 0.6747
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6148 - loss: 0.6668 - val_accuracy: 0.6231 - val_loss: 0.6789
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6180 - loss: 0.6650 - val_accuracy: 0.6231 - val_loss: 0.6761
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6641 - val_accuracy: 0.6231 - val_loss: 0.6689
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6228 - loss: 0.6646 - val_accuracy: 0.6231 - val_loss: 0.6736
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.6212 - loss: 0.6637 - val_accuracy: 0.6194 - val_loss: 0.6707
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6180 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.6834
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6231 - val_loss: 0.6794
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6194 - val_loss: 0.6716
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6785
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6212 - loss: 0.6645 - val_accuracy: 0.6194 - val_loss: 0.6728
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.6821
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6116 - loss: 0.6647 - val_accuracy: 0.6231 - val_loss: 0.6781
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6180 - loss: 0.6641 - val_accuracy: 0.6231 - val_loss: 0.6735
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6196 - loss: 0.6634 - val_accuracy: 0.6269 - val_loss: 0.6888
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6194 - val_loss: 0.6779
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.6720
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6148 - loss: 0.6674 - val_accuracy: 0.6194 - val_loss: 0.6737
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.6180 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.6825
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6196 - loss: 0.6655 - val_accuracy: 0.6231 - val_loss: 0.6809
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6196 - loss: 0.6647 - val_accuracy: 0.6231 - val_loss: 0.6741
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6196 - loss: 0.6637 - val_accuracy: 0.6194 - val_loss: 0.6744
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6196 - loss: 0.6658 - val_accuracy: 0.6194 - val_loss: 0.6715
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6244 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6739
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6644 - val_accuracy: 0.6269 - val_loss: 0.6858
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6196 - loss: 0.6665 - val_accuracy: 0.6231 - val_loss: 0.6759
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6180 - loss: 0.6635 - val_accuracy: 0.6269 - val_loss: 0.6834
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6180 - loss: 0.6666 - val_accuracy: 0.6231 - val_loss: 0.6806
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6231 - val_loss: 0.6727
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6180 - loss: 0.6632 - val_accuracy: 0.6194 - val_loss: 0.6753
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6231 - val_loss: 0.6772
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6231 - val_loss: 0.6740
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6196 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.6773
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6228 - loss: 0.6632 - val_accuracy: 0.6157 - val_loss: 0.6742
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6180 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.6783
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6180 - loss: 0.6628 - val_accuracy: 0.6231 - val_loss: 0.6738
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6212 - loss: 0.6634 - val_accuracy: 0.6269 - val_loss: 0.6856
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6212 - loss: 0.6657 - val_accuracy: 0.6194 - val_loss: 0.6737
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6231 - val_loss: 0.6762
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6212 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.6755
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6244 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6849
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6640 - val_accuracy: 0.6194 - val_loss: 0.6749
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6196 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.6736
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6269 - val_loss: 0.6843
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6244 - loss: 0.6644 - val_accuracy: 0.6194 - val_loss: 0.6747
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6148 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.6732
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6212 - loss: 0.6655 - val_accuracy: 0.6269 - val_loss: 0.6835
Epoch 119: early stopping

wandb: Agent Starting Run: ya1evmeu with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4960 - loss: 1.2148 - val_accuracy: 0.6455 - val_loss: 0.8277
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5971 - loss: 0.7498 - val_accuracy: 0.6343 - val_loss: 0.9374
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5987 - loss: 0.7324 - val_accuracy: 0.6381 - val_loss: 0.8589
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6067 - loss: 0.7159 - val_accuracy: 0.6567 - val_loss: 0.7401
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.6212 - loss: 0.7284 - val_accuracy: 0.7090 - val_loss: 0.6772
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.6340 - loss: 0.6841 - val_accuracy: 0.7201 - val_loss: 0.6528
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.6501 - loss: 0.6838 - val_accuracy: 0.6978 - val_loss: 0.6416
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.6668 - val_accuracy: 0.4552 - val_loss: 0.9067
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.6629 - val_accuracy: 0.6903 - val_loss: 0.6333
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.6388 - loss: 0.6731 - val_accuracy: 0.7090 - val_loss: 0.6335
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.6468 - val_accuracy: 0.6642 - val_loss: 0.6453
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.6719 - val_accuracy: 0.7276 - val_loss: 0.6201
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6565 - loss: 0.6573 - val_accuracy: 0.7090 - val_loss: 0.6060
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6613 - loss: 0.6389 - val_accuracy: 0.7127 - val_loss: 0.6420
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.6308 - loss: 0.6741 - val_accuracy: 0.6642 - val_loss: 0.6489
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.6629 - loss: 0.6350 - val_accuracy: 0.7090 - val_loss: 0.5975
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6742 - loss: 0.6235 - val_accuracy: 0.7239 - val_loss: 0.6334
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.6581 - loss: 0.6364 - val_accuracy: 0.7164 - val_loss: 0.6227
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6485 - loss: 0.6358 - val_accuracy: 0.7015 - val_loss: 0.6010
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6372 - loss: 0.6564 - val_accuracy: 0.6866 - val_loss: 0.6100
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6822 - loss: 0.6362 - val_accuracy: 0.7276 - val_loss: 0.6133
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6356 - loss: 0.6627 - val_accuracy: 0.7164 - val_loss: 0.5875
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6356 - loss: 0.6406 - val_accuracy: 0.6716 - val_loss: 0.6249
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6726 - loss: 0.6212 - val_accuracy: 0.7164 - val_loss: 0.6078
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.5965 - val_accuracy: 0.6978 - val_loss: 0.5994
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.6677 - loss: 0.6238 - val_accuracy: 0.7052 - val_loss: 0.5927
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6758 - loss: 0.6037 - val_accuracy: 0.7313 - val_loss: 0.5917
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6645 - loss: 0.6206 - val_accuracy: 0.7239 - val_loss: 0.5953
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6645 - loss: 0.6178 - val_accuracy: 0.6604 - val_loss: 0.6815
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6645 - loss: 0.6178 - val_accuracy: 0.7015 - val_loss: 0.6336
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6838 - loss: 0.6023 - val_accuracy: 0.7351 - val_loss: 0.5805
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6806 - loss: 0.6055 - val_accuracy: 0.5224 - val_loss: 0.8404
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.6870 - loss: 0.5867 - val_accuracy: 0.7164 - val_loss: 0.5921
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6806 - loss: 0.5994 - val_accuracy: 0.6455 - val_loss: 0.6890
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.6709 - loss: 0.6119 - val_accuracy: 0.7201 - val_loss: 0.5861
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6998 - loss: 0.5944 - val_accuracy: 0.7090 - val_loss: 0.5789
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7127 - loss: 0.5754 - val_accuracy: 0.6679 - val_loss: 0.6713
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7014 - loss: 0.5977 - val_accuracy: 0.7276 - val_loss: 0.5709
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7063 - loss: 0.5615 - val_accuracy: 0.6903 - val_loss: 0.6040
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7047 - loss: 0.5854 - val_accuracy: 0.6978 - val_loss: 0.5889
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6870 - loss: 0.5895 - val_accuracy: 0.7351 - val_loss: 0.5676
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7047 - loss: 0.5674 - val_accuracy: 0.5410 - val_loss: 0.7895
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6870 - loss: 0.5960 - val_accuracy: 0.6679 - val_loss: 0.6199
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7143 - loss: 0.5649 - val_accuracy: 0.6866 - val_loss: 0.6384
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7111 - loss: 0.5660 - val_accuracy: 0.7239 - val_loss: 0.5626
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5545 - val_accuracy: 0.6679 - val_loss: 0.6515
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7191 - loss: 0.5611 - val_accuracy: 0.7388 - val_loss: 0.5513
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7191 - loss: 0.5647 - val_accuracy: 0.6903 - val_loss: 0.5937
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7175 - loss: 0.5573 - val_accuracy: 0.7201 - val_loss: 0.5569
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7239 - loss: 0.5599 - val_accuracy: 0.7239 - val_loss: 0.5648
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7255 - loss: 0.5491 - val_accuracy: 0.7164 - val_loss: 0.5398
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7384 - loss: 0.5420 - val_accuracy: 0.7649 - val_loss: 0.5945
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7352 - loss: 0.5368 - val_accuracy: 0.7201 - val_loss: 0.5665
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7448 - loss: 0.5172 - val_accuracy: 0.7873 - val_loss: 0.5744
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7673 - loss: 0.5304 - val_accuracy: 0.7276 - val_loss: 0.5356
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7480 - loss: 0.5384 - val_accuracy: 0.7910 - val_loss: 0.5911
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.7624 - loss: 0.5260 - val_accuracy: 0.7948 - val_loss: 0.5671
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.7592 - loss: 0.5150 - val_accuracy: 0.7649 - val_loss: 0.5416
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7496 - loss: 0.5349 - val_accuracy: 0.7724 - val_loss: 0.5534
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7640 - loss: 0.4992 - val_accuracy: 0.6754 - val_loss: 0.6850
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7833 - loss: 0.5139 - val_accuracy: 0.7575 - val_loss: 0.5253
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5218 - val_accuracy: 0.7537 - val_loss: 0.5300
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7737 - loss: 0.5001 - val_accuracy: 0.7500 - val_loss: 0.5255
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7640 - loss: 0.5162 - val_accuracy: 0.7836 - val_loss: 0.5833
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7705 - loss: 0.5157 - val_accuracy: 0.7575 - val_loss: 0.5374
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7849 - loss: 0.5050 - val_accuracy: 0.7724 - val_loss: 0.5320
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7673 - loss: 0.4983 - val_accuracy: 0.6530 - val_loss: 0.6976
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7640 - loss: 0.5083 - val_accuracy: 0.7239 - val_loss: 0.5571
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7833 - loss: 0.4970 - val_accuracy: 0.7164 - val_loss: 0.5774
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7865 - loss: 0.4956 - val_accuracy: 0.7724 - val_loss: 0.5337
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7881 - loss: 0.5046 - val_accuracy: 0.7761 - val_loss: 0.5315
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7737 - loss: 0.5059 - val_accuracy: 0.7127 - val_loss: 0.5692
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7640 - loss: 0.5067 - val_accuracy: 0.7500 - val_loss: 0.5299
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7849 - loss: 0.4896 - val_accuracy: 0.7052 - val_loss: 0.6344
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7689 - loss: 0.5125 - val_accuracy: 0.7276 - val_loss: 0.6101
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7817 - loss: 0.5101 - val_accuracy: 0.7500 - val_loss: 0.5445
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7721 - loss: 0.4996 - val_accuracy: 0.7612 - val_loss: 0.5250
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7897 - loss: 0.5060 - val_accuracy: 0.7575 - val_loss: 0.5244
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7769 - loss: 0.4901 - val_accuracy: 0.7351 - val_loss: 0.5653
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7849 - loss: 0.4856 - val_accuracy: 0.7836 - val_loss: 0.5823
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7897 - loss: 0.4910 - val_accuracy: 0.7201 - val_loss: 0.5979
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7640 - loss: 0.5016 - val_accuracy: 0.7425 - val_loss: 0.5493
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7913 - loss: 0.4752 - val_accuracy: 0.7724 - val_loss: 0.5347
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4977 - val_accuracy: 0.7276 - val_loss: 0.5726
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7913 - loss: 0.4908 - val_accuracy: 0.7313 - val_loss: 0.5796
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7833 - loss: 0.4919 - val_accuracy: 0.7575 - val_loss: 0.6142
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.7833 - loss: 0.4722 - val_accuracy: 0.6642 - val_loss: 0.7806
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.8042 - loss: 0.4672 - val_accuracy: 0.7687 - val_loss: 0.5269
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7897 - loss: 0.5020 - val_accuracy: 0.7463 - val_loss: 0.5273
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7978 - loss: 0.4779 - val_accuracy: 0.7687 - val_loss: 0.5322
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.8026 - loss: 0.4682 - val_accuracy: 0.7351 - val_loss: 0.5656
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7897 - loss: 0.4868 - val_accuracy: 0.7761 - val_loss: 0.5679
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8042 - loss: 0.4638 - val_accuracy: 0.7724 - val_loss: 0.5323
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7913 - loss: 0.4782 - val_accuracy: 0.7687 - val_loss: 0.5293
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.8026 - loss: 0.4976 - val_accuracy: 0.7649 - val_loss: 0.5288
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.8042 - loss: 0.4727 - val_accuracy: 0.7612 - val_loss: 0.5243
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7897 - loss: 0.4928 - val_accuracy: 0.7313 - val_loss: 0.6306
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.7961 - loss: 0.4723 - val_accuracy: 0.7463 - val_loss: 0.5444
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.8090 - loss: 0.4664 - val_accuracy: 0.7649 - val_loss: 0.5276
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7913 - loss: 0.4881 - val_accuracy: 0.7575 - val_loss: 0.5126
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7833 - loss: 0.4761 - val_accuracy: 0.7463 - val_loss: 0.5320
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7945 - loss: 0.4665 - val_accuracy: 0.7612 - val_loss: 0.5181
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.8042 - loss: 0.4721 - val_accuracy: 0.7612 - val_loss: 0.5194
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7833 - loss: 0.4751 - val_accuracy: 0.7575 - val_loss: 0.5276
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4652 - val_accuracy: 0.7724 - val_loss: 0.5939
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7945 - loss: 0.4923 - val_accuracy: 0.7164 - val_loss: 0.6456
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8010 - loss: 0.4851 - val_accuracy: 0.7687 - val_loss: 0.5525
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7897 - loss: 0.4783 - val_accuracy: 0.7687 - val_loss: 0.5518
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7961 - loss: 0.4659 - val_accuracy: 0.7276 - val_loss: 0.5777
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.8026 - loss: 0.4740 - val_accuracy: 0.7239 - val_loss: 0.6166
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7913 - loss: 0.4743 - val_accuracy: 0.7575 - val_loss: 0.5412
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.8106 - loss: 0.4527 - val_accuracy: 0.7239 - val_loss: 0.6343
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7961 - loss: 0.4787 - val_accuracy: 0.7649 - val_loss: 0.5440
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7994 - loss: 0.4653 - val_accuracy: 0.7127 - val_loss: 0.6933
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7897 - loss: 0.4936 - val_accuracy: 0.7537 - val_loss: 0.5242
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.7961 - loss: 0.4627 - val_accuracy: 0.7649 - val_loss: 0.5136
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4819 - val_accuracy: 0.7649 - val_loss: 0.5180
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.8154 - loss: 0.4527 - val_accuracy: 0.7575 - val_loss: 0.5481
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.8010 - loss: 0.4659 - val_accuracy: 0.7239 - val_loss: 0.6143
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7897 - loss: 0.4731 - val_accuracy: 0.7873 - val_loss: 0.5990
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.8026 - loss: 0.4843 - val_accuracy: 0.6567 - val_loss: 0.7239
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4775 - val_accuracy: 0.7164 - val_loss: 0.6105
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7929 - loss: 0.4608 - val_accuracy: 0.7575 - val_loss: 0.5159
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.8026 - loss: 0.4746 - val_accuracy: 0.7500 - val_loss: 0.5657
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7913 - loss: 0.4670 - val_accuracy: 0.7799 - val_loss: 0.5743
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.8042 - loss: 0.4609 - val_accuracy: 0.7575 - val_loss: 0.5190
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.7897 - loss: 0.4789 - val_accuracy: 0.7649 - val_loss: 0.5581
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.7945 - loss: 0.4730 - val_accuracy: 0.7612 - val_loss: 0.5281
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.8010 - loss: 0.4720 - val_accuracy: 0.7649 - val_loss: 0.5173
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7897 - loss: 0.4705 - val_accuracy: 0.7612 - val_loss: 0.5211
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7833 - loss: 0.4897 - val_accuracy: 0.7724 - val_loss: 0.5455
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7881 - loss: 0.4745 - val_accuracy: 0.7239 - val_loss: 0.6342
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8026 - loss: 0.4696 - val_accuracy: 0.7276 - val_loss: 0.6379
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.8042 - loss: 0.4708 - val_accuracy: 0.7687 - val_loss: 0.5349
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.8026 - loss: 0.4677 - val_accuracy: 0.7649 - val_loss: 0.5269
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.8074 - loss: 0.4569 - val_accuracy: 0.7612 - val_loss: 0.5163
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4822 - val_accuracy: 0.7687 - val_loss: 0.5522
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4618 - val_accuracy: 0.7351 - val_loss: 0.5935
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4670 - val_accuracy: 0.7649 - val_loss: 0.4945
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7994 - loss: 0.4555 - val_accuracy: 0.7612 - val_loss: 0.5194
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7913 - loss: 0.4548 - val_accuracy: 0.7687 - val_loss: 0.5399
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.8058 - loss: 0.4605 - val_accuracy: 0.7649 - val_loss: 0.5220
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.8058 - loss: 0.4667 - val_accuracy: 0.7463 - val_loss: 0.5567
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4685 - val_accuracy: 0.7612 - val_loss: 0.5226
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7897 - loss: 0.4628 - val_accuracy: 0.7649 - val_loss: 0.5220
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7994 - loss: 0.4563 - val_accuracy: 0.7724 - val_loss: 0.5171
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.8010 - loss: 0.4582 - val_accuracy: 0.7687 - val_loss: 0.5065
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.8042 - loss: 0.4709 - val_accuracy: 0.7649 - val_loss: 0.5562
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.8058 - loss: 0.4614 - val_accuracy: 0.7612 - val_loss: 0.5238
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4704 - val_accuracy: 0.7351 - val_loss: 0.5864
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4683 - val_accuracy: 0.7687 - val_loss: 0.5079
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.7994 - loss: 0.4702 - val_accuracy: 0.7649 - val_loss: 0.5163
Epoch 153/5000

wandb: Sweep Agent: Waiting for job.
wandb: Ctrl + C detected. Stopping sweep.

In [47]:
# グリッドサーチで得た最適なパラメータ値でモデルを作り直す
# （wandbは利用しない）
# テストデータによる予測も行なう
def train_model():
    # モデルの初期化とレイヤー定義
    model = tf.keras.Sequential([
        # 入力層
        tf.keras.Input(shape=(11,)),
        tf.keras.layers.Dense(16, activation='relu'),
        # 隠れ層
        tf.keras.layers.Dense(16, activation='relu'),
        # 出力層
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    # モデルの構築
    model.compile(optimizer='rmsprop',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    # 学習の実施
    log = model.fit(X_train, Y_train,
                    epochs=5000,
                    batch_size=64,
                    verbose=True,
                    callbacks=[
                        tf.keras.callbacks.EarlyStopping(
                            monitor='val_loss',
                            min_delta=0,
                            patience=100,
                            verbose=1
                        )
                    ],
                    validation_data=(X_valid, Y_valid))

    # テストデータによる予測
    Y_pred_proba = model.predict(X_test)
    Y_pred = (Y_pred_proba > 0.5).astype("int32")

    # Y_predを返す
    return Y_pred

In [48]:
# train_modelを実行する
Y_pred = train_model()
Y_pred

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6132 - loss: 26.9702 - val_accuracy: 0.6157 - val_loss: 8.6524
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6035 - loss: 2.7771 - val_accuracy: 0.6828 - val_loss: 0.9899
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 1.0793 - val_accuracy: 0.6157 - val_loss: 2.6175
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5795 - loss: 1.4083 - val_accuracy: 0.6418 - val_loss: 1.4326
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6276 - loss: 1.1358 - val_accuracy: 0.6903 - val_loss: 0.9277
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5730 - loss: 1.3508 - val_accuracy: 0.5597 - val_loss: 1.2702
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6003 - loss: 1.1716 - val_accuracy: 0.6828 - val_loss: 1.1160
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 1.1657 - val_accuracy: 0.6418 - val_loss: 1.0880
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6035 - loss: 1.2760 - val_accuracy: 0.7015 - val_loss: 0.9209
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5762 - loss: 1.3339 - val_accuracy: 0.6604 - val_loss: 1.3132
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6003 - loss: 1.1500 - val_accuracy: 0.6567 - val_loss: 1.3612
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 1.1356 - val_accuracy: 0.6231 - val_loss: 1.6449
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6308 - loss: 1.0764 - val_accuracy: 0.7090 - val_loss: 0.8169
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 1.2749 - val_accuracy: 0.6940 - val_loss: 0.9295
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6035 - loss: 1.1670 - val_accuracy: 0.5261 - val_loss: 1.1063
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5987 - loss: 1.3166 - val_accuracy: 0.5933 - val_loss: 1.0485
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.9891 - val_accuracy: 0.6828 - val_loss: 0.8329
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5891 - loss: 1.2541 - val_accuracy: 0.6604 - val_loss: 0.8679
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5907 - loss: 1.3359 - val_accuracy: 0.6157 - val_loss: 1.3441
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6019 - loss: 1.2117 - val_accuracy: 0.6157 - val_loss: 1.1085
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5843 - loss: 1.2372 - val_accuracy: 0.6978 - val_loss: 1.0871
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 1.0739 - val_accuracy: 0.6978 - val_loss: 0.8949
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.9379 - val_accuracy: 0.6940 - val_loss: 0.7457
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 1.3115 - val_accuracy: 0.6157 - val_loss: 1.2826
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6340 - loss: 1.0360 - val_accuracy: 0.6306 - val_loss: 0.8168
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5859 - loss: 1.3270 - val_accuracy: 0.6940 - val_loss: 0.7851
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.8915 - val_accuracy: 0.6157 - val_loss: 2.5426
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 1.0608 - val_accuracy: 0.6231 - val_loss: 1.3397
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 1.2508 - val_accuracy: 0.6903 - val_loss: 0.8587
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 1.1311 - val_accuracy: 0.4403 - val_loss: 1.7587
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6035 - loss: 1.2545 - val_accuracy: 0.7201 - val_loss: 0.6737
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6469 - loss: 1.0837 - val_accuracy: 0.6679 - val_loss: 0.7820
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5891 - loss: 1.1538 - val_accuracy: 0.4515 - val_loss: 1.5971
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6308 - loss: 1.1925 - val_accuracy: 0.6978 - val_loss: 0.7545
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 0.9701 - val_accuracy: 0.6194 - val_loss: 1.4292
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 1.2616 - val_accuracy: 0.7239 - val_loss: 0.7371
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 1.0304 - val_accuracy: 0.6679 - val_loss: 0.7658
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.9788 - val_accuracy: 0.6828 - val_loss: 0.6962
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5811 - loss: 1.2721 - val_accuracy: 0.6231 - val_loss: 2.1212
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6742 - loss: 0.9912 - val_accuracy: 0.6306 - val_loss: 0.8702
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6404 - loss: 1.0594 - val_accuracy: 0.6157 - val_loss: 2.1475
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6693 - loss: 1.0658 - val_accuracy: 0.5560 - val_loss: 0.9793
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 1.2626 - val_accuracy: 0.6194 - val_loss: 1.5922
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6597 - loss: 0.9653 - val_accuracy: 0.5075 - val_loss: 1.1741
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 1.0560 - val_accuracy: 0.6754 - val_loss: 0.9399
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 0.9625 - val_accuracy: 0.6530 - val_loss: 0.8164
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 1.3143 - val_accuracy: 0.5075 - val_loss: 1.2075
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 1.1650 - val_accuracy: 0.5410 - val_loss: 1.0875
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 1.0487 - val_accuracy: 0.7351 - val_loss: 0.6432
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.9941 - val_accuracy: 0.6157 - val_loss: 1.0139
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 1.2051 - val_accuracy: 0.5784 - val_loss: 0.9459
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6597 - loss: 0.9850 - val_accuracy: 0.7388 - val_loss: 0.6044
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 1.1605 - val_accuracy: 0.7276 - val_loss: 0.6687
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 0.8778 - val_accuracy: 0.6194 - val_loss: 1.6738
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 1.1936 - val_accuracy: 0.6978 - val_loss: 1.0599
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 1.0137 - val_accuracy: 0.7239 - val_loss: 0.7240
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 1.0022 - val_accuracy: 0.6157 - val_loss: 1.6869
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 1.1281 - val_accuracy: 0.6045 - val_loss: 0.9384
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 1.0824 - val_accuracy: 0.7276 - val_loss: 0.6820
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.9708 - val_accuracy: 0.6866 - val_loss: 0.7581
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 1.0225 - val_accuracy: 0.6194 - val_loss: 2.4791
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 1.1293 - val_accuracy: 0.7351 - val_loss: 0.6370
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.9271 - val_accuracy: 0.7201 - val_loss: 0.7087
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 1.0134 - val_accuracy: 0.7052 - val_loss: 0.7413
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.9092 - val_accuracy: 0.6119 - val_loss: 1.9284
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 1.0725 - val_accuracy: 0.6157 - val_loss: 1.6482
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7030 - loss: 0.7817 - val_accuracy: 0.6194 - val_loss: 2.3808
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 1.1175 - val_accuracy: 0.6119 - val_loss: 1.3540
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6404 - loss: 1.0854 - val_accuracy: 0.7052 - val_loss: 0.8490
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6854 - loss: 0.9285 - val_accuracy: 0.6045 - val_loss: 0.8037
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 1.1748 - val_accuracy: 0.5037 - val_loss: 1.1541
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 1.1098 - val_accuracy: 0.5448 - val_loss: 1.0423
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6597 - loss: 0.9762 - val_accuracy: 0.6343 - val_loss: 0.7851
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.9907 - val_accuracy: 0.6940 - val_loss: 0.7569
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 1.0030 - val_accuracy: 0.6157 - val_loss: 1.3692
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 1.0648 - val_accuracy: 0.7052 - val_loss: 0.7580
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6790 - loss: 0.9400 - val_accuracy: 0.6828 - val_loss: 0.8057
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 1.0351 - val_accuracy: 0.7164 - val_loss: 0.6827
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 1.1888 - val_accuracy: 0.7276 - val_loss: 0.7039
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7063 - loss: 0.8647 - val_accuracy: 0.7351 - val_loss: 0.5853
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6469 - loss: 1.0764 - val_accuracy: 0.7164 - val_loss: 0.6970
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6742 - loss: 0.8461 - val_accuracy: 0.7127 - val_loss: 0.6097
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 1.0894 - val_accuracy: 0.4963 - val_loss: 1.2605
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.9043 - val_accuracy: 0.6082 - val_loss: 2.3304
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6902 - loss: 1.0633 - val_accuracy: 0.6791 - val_loss: 0.8064
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6742 - loss: 0.9620 - val_accuracy: 0.5896 - val_loss: 0.9398
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.9858 - val_accuracy: 0.7388 - val_loss: 0.6822
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6934 - loss: 1.0045 - val_accuracy: 0.7090 - val_loss: 0.8073
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6260 - loss: 1.1490 - val_accuracy: 0.7127 - val_loss: 0.6850
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7063 - loss: 0.8920 - val_accuracy: 0.7090 - val_loss: 0.7690
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 0.9557 - val_accuracy: 0.7239 - val_loss: 0.7103
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.8726 - val_accuracy: 0.4104 - val_loss: 2.6089
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.9875 - val_accuracy: 0.7276 - val_loss: 0.6087
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.9319 - val_accuracy: 0.4963 - val_loss: 1.1981
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6790 - loss: 0.8073 - val_accuracy: 0.7351 - val_loss: 0.6392
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 1.0829 - val_accuracy: 0.5187 - val_loss: 1.1040
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 1.0482 - val_accuracy: 0.7351 - val_loss: 0.6229
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6950 - loss: 0.8878 - val_accuracy: 0.7090 - val_loss: 0.7170
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 1.0619 - val_accuracy: 0.7201 - val_loss: 0.6910
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7014 - loss: 0.7775 - val_accuracy: 0.6082 - val_loss: 2.0675
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5987 - loss: 1.3080 - val_accuracy: 0.7276 - val_loss: 0.6417
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.9100 - val_accuracy: 0.6978 - val_loss: 0.9661
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7095 - loss: 0.7672 - val_accuracy: 0.5037 - val_loss: 1.1564
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6838 - loss: 0.7892 - val_accuracy: 0.4813 - val_loss: 1.3068
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 1.0578 - val_accuracy: 0.7351 - val_loss: 0.6952
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7063 - loss: 0.8017 - val_accuracy: 0.6418 - val_loss: 0.8279
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 1.1599 - val_accuracy: 0.6866 - val_loss: 0.7683
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 1.0013 - val_accuracy: 0.5336 - val_loss: 1.0635
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6726 - loss: 0.9762 - val_accuracy: 0.6343 - val_loss: 1.3208
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7030 - loss: 0.8171 - val_accuracy: 0.6866 - val_loss: 0.7179
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 1.0675 - val_accuracy: 0.5373 - val_loss: 1.0604
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7111 - loss: 0.7896 - val_accuracy: 0.7500 - val_loss: 0.6328
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 1.0306 - val_accuracy: 0.7276 - val_loss: 0.7097
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.9571 - val_accuracy: 0.7127 - val_loss: 0.7465
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 1.0155 - val_accuracy: 0.7052 - val_loss: 0.7815
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7014 - loss: 0.8655 - val_accuracy: 0.7463 - val_loss: 0.6858
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6998 - loss: 0.8421 - val_accuracy: 0.5448 - val_loss: 1.0118
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6276 - loss: 1.0640 - val_accuracy: 0.5373 - val_loss: 1.0693
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6726 - loss: 1.0030 - val_accuracy: 0.7239 - val_loss: 0.6188
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6966 - loss: 0.8515 - val_accuracy: 0.7239 - val_loss: 0.6410
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7271 - loss: 0.7748 - val_accuracy: 0.4552 - val_loss: 1.5907
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 1.0835 - val_accuracy: 0.5261 - val_loss: 1.1328
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.8698 - val_accuracy: 0.6119 - val_loss: 1.6819
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 1.0055 - val_accuracy: 0.7388 - val_loss: 0.7097
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.7687 - val_accuracy: 0.7164 - val_loss: 0.6523
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6966 - loss: 0.8561 - val_accuracy: 0.6828 - val_loss: 0.7500
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 1.0613 - val_accuracy: 0.7313 - val_loss: 0.5999
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.9264 - val_accuracy: 0.7687 - val_loss: 0.5877
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.9234 - val_accuracy: 0.7351 - val_loss: 0.6109
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.9539 - val_accuracy: 0.7463 - val_loss: 0.6193
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7111 - loss: 0.7985 - val_accuracy: 0.6866 - val_loss: 0.7830
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6918 - loss: 0.8743 - val_accuracy: 0.7276 - val_loss: 0.5775
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7030 - loss: 0.8957 - val_accuracy: 0.6119 - val_loss: 2.0331
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.9784 - val_accuracy: 0.4888 - val_loss: 1.3188
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.9355 - val_accuracy: 0.7276 - val_loss: 0.5853
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7512 - loss: 0.6761 - val_accuracy: 0.6194 - val_loss: 1.3644
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.9333 - val_accuracy: 0.6343 - val_loss: 1.2263
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7014 - loss: 0.9073 - val_accuracy: 0.6194 - val_loss: 1.5342
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 1.0297 - val_accuracy: 0.6679 - val_loss: 0.8516
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7159 - loss: 0.9281 - val_accuracy: 0.7276 - val_loss: 0.6262
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7448 - loss: 0.6457 - val_accuracy: 0.6978 - val_loss: 0.7866
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 1.0943 - val_accuracy: 0.7239 - val_loss: 0.6868
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 1.0185 - val_accuracy: 0.7313 - val_loss: 0.6207
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7191 - loss: 0.7522 - val_accuracy: 0.7313 - val_loss: 0.6086
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.8798 - val_accuracy: 0.6157 - val_loss: 2.2191
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.8576 - val_accuracy: 0.7313 - val_loss: 0.5604
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.8231 - val_accuracy: 0.7388 - val_loss: 0.5705
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.9106 - val_accuracy: 0.7239 - val_loss: 0.5923
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.8817 - val_accuracy: 0.7276 - val_loss: 0.6455
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6950 - loss: 0.8653 - val_accuracy: 0.7500 - val_loss: 0.7088
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6822 - loss: 0.9579 - val_accuracy: 0.6791 - val_loss: 0.9679
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7544 - loss: 0.6321 - val_accuracy: 0.6306 - val_loss: 1.1534
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7063 - loss: 0.8697 - val_accuracy: 0.6455 - val_loss: 1.2797
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7079 - loss: 0.9135 - val_accuracy: 0.7239 - val_loss: 0.5649
Epoch 155/5000

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0]], dtype=int32)

In [49]:
# X_testをDataFrameに戻し、X_test2に格納
X_test2 = pd.DataFrame(X_test, columns=test2.columns)

In [50]:
# Kaggleへ提出するためのデータが入ったDataFrameを作成
submission_data = pd.DataFrame()
submission_data["PassengerId"] = X_test2["PassengerId"].astype("int32")
submission_data["Survived"] = Y_pred
submission_data

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [51]:
# Kaggleに提出するためのCSVファイルを作成
submission_data.to_csv("my_submission_titanic.csv", index=False)